nyaruka/rapidpro

media/test_imports/rule-first-ivr.json
temba/flows/models.py
temba/ivr/tests.py

IVR flow handling wasn't dealing with having a leading ruleset. This now executes the leading ruleset first before moving on to the next actionset.
Also added a test case for this one.
Plz review @ericnewcomer

Rule first ivr

---

temba/contacts/tests.py
temba/contacts/views.py

FIx for https://app.getsentry.com/nyaruka/textit/group/45513195/

throw 404 instead of 500 when a contact does not exist

---

static/coffee/flows/controllers.coffee
templates/flows/flow_editor.haml

A couple of minor issues:
* Fix for occasional "[[error]]" flashing on flow loading
* Fix for not saving when ruleset webhook urls are changed.

Minor flow editor bugs

---

temba/api/serializers.py
temba/api/views.py

fix for https://app.getsentry.com/nyaruka/rapidpro/group/52430605/

fix to show broadcasts API docs and update API explorer

---

media/test_flows/substitution.json
temba/flows/tests.py
temba/msgs/models.py

Fixes missing step.contact variable when flows are started

---

static/less/style.less
temba/msgs/models.py
temba/msgs/views.py
templates/msgs/message_box.haml

proposition for https://github.com/rapidpro/rapidpro/issues/86

show flow that handled a message

---

temba/flows/models.py

add pk to order_by fields on flow exports

---

temba/api/tests.py
temba/channels/models.py

This adds a new ```max_tps``` configuration option on channel types, and implements a max of 5 tps for nexmo so they don't get all pissy about us hitting them too fast.
plz review.

add ability to throttle different channel types

---

temba/settings_common.py
templates/channels/channel_claim_verboice.haml

Makes sure our permissions are correct for both Verboice and Twitter. 
Adds a template for the verboice page so it isn't so ugly. :)
plz review @ericnewcomer

Enable verboice for admins, as well as twitter

---

temba/api/tests.py
temba/api/views.py

fix https://app.getsentry.com/nyaruka/textit/group/52773123/

Invalid params

---

static/coffee/flows/services.coffee
static/coffee/temba.coffee
templates/flows/flow_editor.haml
templates/partials/ivr_editor.haml

Fixes for bugs reported by Asch:
* Don't show 'true' rule on ivr editor
* Fix double clicking to add new notes

Editor bugs

---

temba/flows/models.py
temba/flows/tests.py
temba/ivr/tests.py

Remove changes handling incoming sms triggers inside voice flows.

trigger messages for ivr flows should actually not be part of flow

---

static/less/style.less
templates/smartmin/users/user_update.haml

Tried to hit all the pages to make sure this doesn't break anything else and it looks good.

fixes minor form styling spacing problems

---

media/test_imports/call-me-maybe.json
temba/api/views.py
temba/ivr/models.py
temba/ivr/tests.py

* Add contact_urn when creating incoming call

Fix for inbound call trigger

---

temba/api/serializers.py
temba/api/tests.py
temba/flows/models.py
temba/flows/tasks.py
temba/flows/tests.py
temba/utils/cache.py

Also adds caching for `Flow.get_terminal_nodes` and `Flow.get_category_nodes`

Expose is_completed in API runs endpoint

---

temba/api/serializers.py
temba/contacts/models.py
temba/contacts/tests.py

fix https://github.com/rapidpro/rapidpro/issues/11

Valid contact fields from api

---

static/coffee/flows/widgets.coffee
temba/contacts/models.py
temba/flows/tasks.py
templates/partials/action_editor.haml

Allow @extra.asdf in add and remove group, fix method signature for flow cache

---

temba/api/serializers.py
temba/api/tests.py
temba/api/views.py
temba/utils/__init__.py
temba/utils/tests.py
temba/values/models.py

Also tidied up json date functions to ease testing of such endpoints

Added response_type to serialized rulesets from flows API endpoint

---

static/coffee/flows/controllers.coffee

mark dirty when removing a webhook action

---

static/coffee/flows/services.coffee
temba/flows/migrations/0012_auto_20150302_1734.py

Hopefully we have it right this time. 
@nicpottier

Munged categories redux

---

temba/api/serializers.py
temba/api/tests.py

Fixes https://github.com/rapidpro/rapidpro/issues/129

Runs api fix

---

temba/contacts/views.py
temba/msgs/views.py
temba/orgs/urls.py
temba/orgs/views.py

This changed in Django 1.7 and now we get an attribute error when trying to access `form.util.ErrorList`

Replaced form.util.ErrorList with form.utils.ErrorList 

---

temba/channels/models.py
temba/channels/tasks.py
temba/channels/tests.py
temba/channels/urls.py
temba/channels/views.py
temba/utils/mage.py

I also pushed this to staging from it's own branch and tested communication with Mage
Nice thing about this is that finally disabling "auto-follow" on the channel config page works.

Notify Mage when config for a Twitter channel is updated

---

temba/orgs/models.py
temba/orgs/tasks.py
temba/settings_common.py
temba/utils/cache.py

move to calculating active topups in a task every three days

---

temba/api/serializers.py
temba/api/tests.py
temba/api/urls.py
temba/api/views.py
temba/contacts/tests.py
temba/flows/models.py
temba/flows/tests.py
temba/msgs/migrations/0004_label_uuid.py
temba/msgs/migrations/0005_populate_label_uuid.py
temba/msgs/migrations/0006_auto_20150312_0827.py
temba/msgs/migrations/0007_auto_20150312_1024.py
temba/msgs/migrations/0008_remove_label_label_type.py
temba/msgs/migrations/0009_auto_20150312_1113.py
temba/msgs/models.py
temba/msgs/tests.py
temba/msgs/views.py
temba/perf_tests.py
temba/settings_common.py
templates/msgs/message_box.haml

* Removes `label_type` field as this is no longer used ('P' types became `FlowLabel`)
* Adds UUID to `Label`
* Converts Label to `SmartModel` to get recording of user changes
* Adds _labels.json_ endpoint for listing, adding and creating of labels

Label model upgrades and API endpoint

---

temba/orgs/migrations/0002_topup_used.py
temba/orgs/models.py

This just adds the ```used``` field to TopUp, we'll populate the field in another push due to this taking the db down.

Topup triggers 1

---

temba/orgs/migrations/0003_auto_20150313_1624.py
temba/orgs/models.py
temba/orgs/tests.py

This installs our trigger for when msgs_msg is inserted, deleted or updated, increment our decrementing our topup.used accordingly. Also populates used.

Topup triggers 2

---

static/coffee/flows/services.coffee
temba/flows/migrations/0015_auto_20150320_0417.py
temba/flows/models.py
temba/flows/tests.py
temba/orgs/views.py
templates/orgs/org_languages.haml

* Don't require a primary language for orgs even after they've selected one
* Fix dragging bug for freshly imported localized flows
* Let imported flows update base language
* Migrate flows affected by above import bug

Language bugs

---

temba/api/serializers.py
temba/api/tests.py

fix for https://app.getsentry.com/nyaruka/rapidpro/group/58898040/
plz review

validate the group names posted

---

media/test_imports/ruleset_loop.json
temba/flows/models.py
temba/flows/tests.py

fixes https://app.getsentry.com/nyaruka/textit/group/59541983/

Fix ruleset loop

---

temba/api/tests.py
temba/channels/models.py
temba/msgs/models.py

This switches from stuffing the global keyspace in Redis with msg_send_[id] to using daily sets that we stuff instead. This is slightly more complicated in that we have to two check two sets for inclusion, but I think the benefits outweigh that small cost.

Dont stuff our global key space with msg send tokens

---

temba/flows/views.py
temba/values/tests.py

fix for https://app.getsentry.com/nyaruka/rapidpro/group/60374853/
please review

chrolopleth should not throw when no data is yet avalaible for the map

---

temba/flows/views.py
temba/values/tests.py

Fixes case where most recent flow wasn't appearing.

Make sure most recent flow appears in analytics

---

temba/channels/models.py

Switches to sending messages on the HighConnection channel as UTF-8.
plz glance at it someone. :)

Switch to sending UNICODE for HighConnection channels

---

temba/api/serializers.py
temba/api/tests.py
temba/api/urls.py
temba/api/views.py
temba/msgs/models.py
temba/msgs/tests.py
temba/msgs/views.py

Yo review @ericnewcomer @nicpottier

API endpoint for bulk message actions

---

temba/api/tests.py
temba/api/views.py
temba/utils/__init__.py
temba/utils/tests.py

* Searching by text
* Reversing order of results

Messages API additions

---

temba/campaigns/models.py
temba/contacts/views.py
temba/flows/migrations/0018_auto_20150417_1835.py
temba/flows/models.py
temba/flows/tests.py
templates/contacts/contact_history.haml

This more deliberately sets the timestamps on FlowSteps to make ordering of those events easier when viewing a contact's history.

FlowStep timestamp tweaks

---

templates/contacts/contact_read.haml
templates/flows/flow_results_contact.haml

a few links to helps an easy navigation from flow to contact or vice versa

More navigation

---

temba/campaigns/models.py
temba/campaigns/tests.py

Fix for: https://app.getsentry.com/nyaruka/textit/group/63369100/

Campaign dates

---

temba/orgs/tests.py
temba/orgs/views.py
temba/tests.py

Connect Twilio test use mock client
and Add check for primary auth token from Twilio API

Handle twilio secondary tokens

---

temba/api/serializers.py
temba/api/tests.py
temba/api/views.py

* Deleted messages should not be returned
* Archived status should be included in serialized messages
* Archived should be filterable

Messages API endpoint should consider message visibility

---

temba/contacts/migrations/0016_remove_exportcontactstask_filename.py
temba/contacts/models.py
temba/flows/migrations/0020_remove_exportflowresultstask_filename.py
temba/flows/models.py
temba/flows/views.py
temba/msgs/migrations/0011_remove_exportmessagestask_filename.py
temba/msgs/models.py
temba/msgs/views.py

This is no longer used since we added the assets app

Removed filename field from the 3 export task classes

---

temba/channels/models.py
temba/channels/tasks.py

Also adds a max time for the send-message task.

Adds a missing timeout on a channel send for Kannel

---

temba/api/tests.py
temba/api/views.py

Allow api flow results by ruleset uuid

---

temba/api/serializers.py
temba/api/tests.py
temba/api/views.py
temba/perf_tests.py

* Expose Msg.broadcast
* Added select_related optimizations
* Removed 2 deprecated fields that were slow (relayer_phone, phone)

Messages API updates

---

pip-freeze.txt

Use latest celery and django-celery.

Updrade celery to latest

---

temba/msgs/models.py
temba/msgs/tests.py
temba/perf_tests.py

Include anon ids in message exports

---

karma/flows/test_services.coffee
media/test_flows/loop_detection.json
static/coffee/flows/services.coffee

While the engine supports it, we probably don't want people linking up two user input nodes in a row.

Disallow two pausing rulesets in a row

---

static/coffee/flows/controllers.coffee
static/less/flow_editor.less
templates/partials/node_editor.haml

A few hotfixes to address issues from last weeks big push:
* Double dialog issue on Firefox fixed
* Disable dialog flipping on IE, it doesn't work
* Clicking on rulesets inside IVR flows didn't always show the dialog
* Valid route checking on saving rulesets wasn't quite right
I'm planning to push this tonight whether or not I get a review in time given the importance of the above and timezones.

Firefox flipping ie hack

---

static/coffee/flows/controllers.coffee
templates/partials/translate_rules.haml

Fixes a bug whereby the rules translation dialog was incomplete.

Fix translation rules dialog

---

temba/api/serializers.py
temba/api/tests.py
temba/api/views.py
temba/campaigns/migrations/0005_auto_20150604_0723.py
temba/campaigns/models.py
temba/campaigns/tests.py
temba/contacts/models.py
temba/contacts/tests.py
temba/flows/tests.py
temba/values/models.py

* Adds UUID fields to `Campaign` and `CampaignEvent`
* Allows use of UUIDs in the API endpoints
* Adds convenience create methods to `CampaignEvent`

Campaigns API and model improvements

---

temba/contacts/models.py
temba/contacts/tests.py

Fixes Chile case of regions names showing up for date fields.

Fix field display

---

static/coffee/flows/services.coffee
temba/flows/models.py
temba/flows/tests.py

* Use the same logic for looking for step in both operands and rules
* Look in expression for step in the flow editor when cycle checking
*We should consider removing the check on rules as it may not fit the world view for flows v3*

Make requires_step() consider expressions

---

temba/flows/migrations/0021_actionset_destination_uuid.py
temba/flows/models.py
temba/flows/tests.py

Fix for:
https://app.getsentry.com/nyaruka/textit/group/68162068/

Fix bug with numbertest requires_step()

---

karma/flows/test_services.coffee
static/coffee/flows/services.coffee
templates/flows/flow_editor.haml

* loop detection edge case
* dragging to new rulesets from previous connections
* actionset offsets on action addition/removal

A few editor bugs

---

static/coffee/flows/controllers.coffee
templates/partials/action_editor.haml

https://app.getsentry.com/nyaruka/textit/group/68368647/

Proper text when switching from sms to email

---

temba/api/views.py
temba/campaigns/models.py
temba/channels/tests.py
temba/flows/models.py
temba/middleware.py
temba/msgs/tests.py
temba/orgs/models.py
temba/orgs/tests.py
temba/orgs/views.py
temba/settings.py.dev
temba/settings_common.py
temba/triggers/models.py
templates/api/api_explorer.haml
templates/channels/email/base.html
templates/channels/email/connected_alert.html
templates/channels/email/connected_alert.txt
templates/channels/email/disconnected_alert.html
templates/channels/email/disconnected_alert.txt
templates/channels/email/power_alert.html
templates/channels/email/power_alert.txt
templates/channels/email/power_charging_alert.html
templates/channels/email/power_charging_alert.txt
templates/channels/email/sms_alert.html
templates/channels/email/sms_alert.txt

Fixes textit.in URLs showing up on the API explorer page.

Move API_URL to be a brand specific item

---

temba/api/tests.py
temba/api/views.py

Also change our custom assert() to check that going forward.
plz review @rowanseymour

Fix results endpoint to expose errors as lists

---

temba/flows/models.py
temba/msgs/tests.py
temba/msgs/views.py
temba/tests.py

* Don't include test messages in filter by label view
* Don't list label folders in Add Label actions

Msg labelling fixes

---

temba/flows/models.py
temba/msgs/models.py
temba/msgs/tests.py
temba/orgs/models.py
temba/utils/__init__.py

Fixes the case where in a broadcast some contacts were getting the wrongly translated text.

Fix wrong language being used in large broadcasts

---

temba/msgs/tasks.py

There is potential for badness if we are processing two messages that are triggers at the same time.. turns out because of network delays this is more common than you might think. This makes sure we obtain a lock on the contact before processing the message.
plz review @rowanseymour

Synchronous processing of messages for single contacts

---

temba/api/tests.py
temba/channels/models.py

Automatically fails contacts on Vumi and Twitter who we know either no longer exist or who have explicitly opted out by unfollowing or sending "stop"

Fail contacts on Vumi and Twitter who have opted out

---

temba/api/tests.py
temba/channels/migrations/0016_channelcount.py
temba/channels/migrations/0016_dailychannelcount.py
temba/channels/migrations/0017_install_channel_count_triggers.py
temba/channels/migrations/0018_auto_20150710_2047.py
temba/channels/migrations/0019_update_channellog_triggers.py
temba/channels/models.py
temba/channels/tests.py
temba/channels/views.py
temba/msgs/models.py
templates/channels/channel_read.haml

Add DailyChannelCount model, population migration and triggers 

---

static/examples/flows/01_simple_poll.json
static/examples/flows/02_satisfaction_survey.json
static/examples/flows/03_order_status_checker.json
static/examples/flows/04_group_chat.json

Update sample flows

---

temba/api/serializers.py
temba/api/tests.py
temba/api/views.py
temba/flows/models.py

Backfill response_type for backwards compatibility on flow api endpoint

Add response_type for backwards compat for api

---

media/test_flows/webhook_rule_first.json
temba/flows/migrations/0024_advance_stuck_runs.py
temba/flows/models.py
temba/flows/tests.py

Fixes for flows that start with a webhook.

Start with webhook

---

temba/msgs/migrations/0027_create_outgoing_indexes.py
temba/msgs/migrations/0028_populate_system_labels.py

Message system labels part 2

---

temba/msgs/migrations/0028_populate_system_labels.py

Rework populate_system_labels to not filter by created_on

Message system labels part 3

---

temba/msgs/migrations/0028_populate_system_labels.py
temba/msgs/migrations/0029_auto_20150803_2254.py
temba/msgs/models.py

Same treatment as before, just for system labels.

Move to using INSERT/DELETE triggers for system labels

---

karma/flows/test_services.coffee
static/coffee/flows/controllers.coffee
static/coffee/flows/services.coffee

We weren't recovering once a save failed due to poor connections. This makes sure we try again with backdown.

Handle poor network connections in the editor

---

karma/flows/test_controllers.coffee
static/coffee/flows/controllers.coffee
static/coffee/flows/directives.coffee
templates/flows/flow_editor.haml

* Fix selection of current language on initial load
* Fix localization of categories on rulesets
* Don't allow setting base language if translation categories are missing

Fixes a few bugs with localization

---

temba/flows/migrations/0007_auto_20150115_1926.py
temba/flows/migrations/0027_auto_20150820_2030.py
temba/flows/models.py
temba/flows/tests.py

This also fixes a bug where flow expirations weren't getting updated on new steps + test

Add org and modified_on fields to FlowRun so we can do a live migration

---

temba/api/serializers.py
temba/api/views.py
temba/flows/models.py

Switches to using the new modified_on and org indexes now that they are populated.

Start using new org and modified_on indexes

---

temba/flows/models.py
temba/flows/tests.py

This makes debugging SMS forms a hell of a lot more obvious.

Add debugging messages in the simulator to show flow values

---

media/test_flows/ivr_child_flow.json
temba/flows/models.py
temba/ivr/tests.py

Good old passing None then testing against array case..

Fix start flow action being broken for IVR flows

---

temba/campaigns/models.py
temba/campaigns/tests.py

Properly gets rid of old events when archiving.

Properly remove events when archiving events

---

temba/flows/models.py
temba/flows/tests.py

Allow contact fields up to 640 chars since our DB supports that anyways

---

static/coffee/flows/controllers.coffee
temba/flows/tests.py

Since some people need periods, might as well support it.

Add option to use period as delimiter for forms

---

temba/contacts/migrations/0022_auto_20150815_0003.py
temba/msgs/migrations/0030_auto_20150815_0003.py
temba/orgs/migrations/0006_topupcredits.py
temba/orgs/migrations/0007_remove_topup_used.py
temba/orgs/models.py
temba/orgs/tests.py
templates/orgs/topup_list.haml

Uses INSERT trigger so there's no contention on modifying the TopUp row when decrementing credits.

Credit optimizations

---

temba/msgs/models.py
temba/msgs/tests.py
temba/orgs/models.py
temba/utils/__init__.py

When a channel gives us 100s of thousands of failed messages, this was timing out.

Chunk big retry sends

---

temba/api/tests.py
temba/channels/models.py

Stupid .find() usage by my part..

Dont fail vumi messages that aren't stops

---

temba/middleware.py
temba/orgs/migrations/0009_org_surveyors.py
temba/orgs/models.py
temba/orgs/tests.py
temba/orgs/views.py
temba/settings_common.py
templates/orgs/org_manage_accounts.haml

* New user role that can be invited to an org.
* Doesn't have any website privileges other than logging in
* Can be used with the Android client

Add surveyor role, can't do anything on the website

---

karma/flows/test_controllers.coffee
media/test_flows/favorites.json
static/coffee/flows/controllers.coffee
static/coffee/flows/services.coffee
temba/flows/models.py
temba/flows/tests.py
temba/flows/views.py

Add a new flow editor type for Survey. Only show appropriate actions and rulesets.

Survey type

---

temba/api/serializers.py
temba/api/tests.py
temba/flows/models.py
temba/orgs/tests.py
temba/orgs/views.py
temba/settings_common.py
temba/tests.py
templates/orgs/org_surveyor.haml

Before reviewing, first merge: https://github.com/nyaruka/rapidpro/pull/331
Fixes a bug whereby activity was not being appropriated correctly when come from an rule during survey submission.

Fix survey activity

---

temba/api/views.py
templates/orgs/org_surveyor.haml
templates/public/public_deploy.haml

* Make sure the api token is created at login if it isn't there yet
* Fix links for surveyor download

Ensure token

---

static/coffee/simulator.coffee
static/less/simulator.less
temba/flows/migrations/0032_auto_20150916_0757.py
temba/flows/migrations/0034_action_log_levels.py
temba/flows/models.py
temba/msgs/models.py
temba/msgs/tests.py

Added warning level for actions that proceed despite expression errors (e.g. SaveToContact) and error level for actions that can't proceed (e.g. AddToGroup when group name is invalid). For example:
Checking how everyone feels about the general idea before adding more log events.

Added error and warning level action logging

---

temba/api/views.py
temba/contacts/models.py
temba/contacts/views.py
temba/utils/exporter.py
temba/utils/tests.py

Should reduce contact exports from ~20 hours to less than 1 for nigeria.

Speed up contact exports by 20x

---

static/less/flow_editor.less
templates/flows/flow_editor.haml

A nicer revision browser.
* Scrolling less awkward, handles large number of revisions better
* Fix mask on long flows
* Make revision browser moveable for when it blocks viewing the flow
Video:
https://monosnap.com/file/8SlOcKtpvqXDAEN5jbuwjEt1QR8EnJ

Nicer revision browser

---

temba/api/serializers.py
temba/api/tests.py
temba/contacts/models.py
temba/contacts/tests.py

Also tidied up field validation

Allow creating of contact fields with specific keys

---

temba/flows/flow_migrations.py

Now with passing tests and everything.

Only pop rulesets if its there

---

temba/msgs/models.py

Fixes https://app.getsentry.com/nyaruka/rapidpro/group/88470913/

Fix for create_outgoing when channel is None and loop detected

---

temba/api/serializers.py
temba/api/tests.py
temba/api/views.py
temba/contacts/migrations/0026_add_org_non_active_index.py

Add ability filter contacts by deleted on API, new index

---

karma.conf.coffee
karma/helpers.coffee
karma/test_temba.coffee
package.json
static/coffee/temba.coffee
templates/frame.haml
templates/modal.haml

* Stores the button text on modax.show()
* Use button text form smartmin form if present
* Use ng-haml2js for haml fixtures

Fix modax action button text on failure

---

temba/channels/migrations/0025_auto_20151021_1619.py

Just updates channel_type so migrations are happy.

Update migration for yo channel type

---

temba/ivr/clients.py
temba/ivr/models.py
temba/ivr/tests.py

Provides feedback when Twilio returns an authentication error during call creation when simulating.

Surface twilio exceptions when creating calls during simulation

---

static/less/style.less

Tweak the font size and spacing for completion.

tweak styling for completion

---

temba/flows/models.py
temba/triggers/tests.py
temba/triggers/views.py
templates/frame.haml
templates/msgs/msg_send_modal.haml

Fixes some bugs with triggers.
* Don't show single message flows as options for trigger forms
* Fix creating join group triggers on orgs with a primary language
* Fix broken reference to AutoComplete module

Fixes for triggers

---

temba/channels/views.py

Plivo confirmed ZA is supported and PK will be removed soon, I update those even though I am waiting to see if they provide the full updated list

update plivo supportted countries

---

static/less/flow_editor.less
static/less/style.less
temba/flows/tests.py
temba/flows/views.py
templates/flows/flow_editor.haml
templates/flows/flow_list.haml

Tweaks for survey ui
* Show Android icon on list page and editor page for survey flows
* Remove Start Flow button on survey flows
* Remove beta-gate

Survey styling

---

temba/contacts/tests.py
temba/contacts/views.py

Previous fix for this forgot to check form submission...

Fixed submitting update form when contact is blocked

---

temba/flows/models.py
temba/flows/tests.py
temba/msgs/models.py
temba/utils/__init__.py

Took a while to figure out a way to test this, but printing the highest memory point did the trick.
This should bring the memory needed to start gigantic flow starts way down.

Tweaks to allow huge flow starts to work under low mem conditions

---

temba/msgs/models.py
temba/msgs/tests.py

Msg exports are failing on fairly small exports at the minute because the old export was trying to load every message in memory.
This fixes that.

Dont try to load all messages in memory at once for msg exports

---

karma.conf.coffee
karma/flows/test_directives.coffee
package.json
static/coffee/flows/widgets.coffee
static/less/flow_editor.less
templates/flows/flow_editor.haml
templates/partials/sms_directive.haml

Handle empty replies more gracefully. Add test for sms directive.

Empty replies

---

temba/msgs/migrations/0037_backfill_recipient_counts.py

Migration to set recipient_counts... they aren't really used anywhere but better to keep models up to date.

Fix recipient counts

---

temba/flows/models.py
temba/flows/tests.py

Fixes https://github.com/rapidpro/rapidpro/issues/156b

@extra.flow should be populated for StartFlow same as TriggerFlow

---

temba/orgs/tests.py
templates/orgs/email/alert_email.html
templates/orgs/email/alert_email.txt

Remove if block inside blocktrans block in credits alert email template

---

temba/api/v1/views.py
temba/channels/models.py
temba/channels/views.py
temba/flows/migrations/0011_auto_20150227_1823.py
temba/flows/models.py
temba/flows/views.py
temba/middleware.py
temba/orgs/models.py
temba/orgs/views.py
temba/schedules/tasks.py
temba/tests.py
temba/values/models.py

Since there's nowhere in RapidPro where we'd actually want to catch something like a `KeyboardInterrupt`

No more empty except statements

---

temba/channels/models.py
temba/channels/tests.py
temba/channels/views.py
temba/msgs/views.py
temba/orgs/models.py
temba/orgs/tests.py
temba/orgs/views.py
temba/perf_tests.py
templates/channels/channel_claim.haml
templates/channels/channel_read.haml
templates/frame.haml
templates/orgs/org_twilio_account.haml

* Moves viewing and removing of Twilio credentials to account page with ability to edit them
* Bump code coverage in channels/views.py

Update Twilio Settings

---

pip-freeze.txt
pip-requires.txt
temba/api/__init__.py
temba/api/renderers.py
temba/api/tests.py
temba/api/v1/serializers.py
temba/api/v1/views.py
temba/contacts/tests.py
temba/settings_common.py
temba/utils/__init__.py

This is reworking of our current API v1 to use the latest REST framework 3.x. 
Git hub is not showing the diff for _temba/api/v1/serializers.py_ (there are loads...) so you may have to pull to see changes.

API v2 Part II

---

temba/orgs/models.py
temba/orgs/tests.py

fixes https://app.getsentry.com/nyaruka/textit/issues/98398908/

return zero for low credits threshold if no active topup

---

temba/flows/models.py
temba/flows/tests.py

https://app.getsentry.com/nyaruka/textit/issues/100801243/

clean label prepended by [_NEW_] from import

---

temba/channels/tests.py
temba/channels/views.py

Handle relayer getting messages from empty URNs

---

temba/channels/tests.py
templates/channels/channel_read.haml
templates/channels/email/connected_alert.html
templates/channels/email/connected_alert.txt
templates/channels/email/disconnected_alert.html
templates/channels/email/disconnected_alert.txt
templates/channels/email/power_alert.html
templates/channels/email/power_alert.txt
templates/channels/email/power_charging_alert.html
templates/channels/email/power_charging_alert.txt
templates/channels/email/sms_alert.html
templates/channels/email/sms_alert.txt

Fixed channel read urls that were still using pk rather than UUID

---

media/test_flows/too_old.json
temba/orgs/models.py
temba/orgs/tests.py
temba/orgs/views.py
temba/tests.py
temba/triggers/models.py

#FullCoverageFridays
* Tests for the orgs app
* Refactors OrgCRUDL.Import to use proper validation approach
* Fixes a bug whereby partial imports were possible

Coverage for orgs

---

temba/contacts/search.py
temba/contacts/tests.py

Prevents https://app.getsentry.com/nyaruka/textit/issues/104689350/

Contact search shouldn't blow up if dates are not parseable

---

temba/contacts/models.py
temba/msgs/models.py

Small tweak to for faster query for scheduled messages on the contact page.

Contact read optimization

---

temba/msgs/migrations/0040_auto_20151205_0206.py

Some options to speed up manual migration runs

Add optional parameters to purge migration

---

pip-freeze.txt
temba/public/urls.py
temba/public/views.py

Required fixing some wildcard imports

Update to latest smartmin

---

temba/api/tests/test_v2.py
temba/api/v2/serializers.py
temba/api/v2/views.py

* Limit ways of filtering messages
* Return channel with name for consistency

API v2 tweaks

---

temba/contacts/tests.py

- Update comments in tests
- Add helper method to improve DRY
No coverage changed just coveralls seems to not like less lines in tests

DRY contact import and update comments in tests

---

temba/api/tests/test_v1.py
temba/api/v1/serializers.py
temba/api/v1/views.py

* Fixed not being able to change a contact's URNs via the API
* Fixed messages endpoint returning test contact messages

API v1 fixes

---

temba/channels/handlers.py
temba/channels/tests.py

Handles https://app.getsentry.com/nyaruka/rapidpro/issues/105804265/

Create msg with empty text if Start Mobile give us empty body element

---

temba/assets/tests.py
temba/assets/views.py

Fix https://app.getsentry.com/nyaruka/rapidpro/issues/110078150/

only stream assets for authenticated users

---

temba/contacts/models.py
temba/contacts/tests.py

Fix for exporting contacts when at least one of them has an email URN.
Related: https://app.getsentry.com/nyaruka/textit/issues/110159533/

Fix contact email export

---

temba/contacts/models.py
temba/contacts/tests.py

same as #542 for Telegram scheme

Fix Telegram URN Export

---

temba/flows/models.py
temba/flows/tests.py
temba/msgs/models.py
temba/msgs/tests.py

Add contact UUID column on messages exports and flow results exports sheets

Results export contact uuid

---

temba/api/tests/test_v1.py
temba/api/v1/serializers.py
temba/api/v1/views.py
temba/flows/models.py
temba/flows/tests.py
temba/flows/views.py
temba/ivr/tests.py
temba/ivr/views.py
templates/flows/flow_broadcast.haml
templates/flows/flow_list.haml

Removes old ```get_total_contacts``` and now uses flow run counts everywhere instead.

Use flow counts

---

temba/flows/models.py
temba/flows/tests.py

Fixes: 
https://app.getsentry.com/nyaruka/rapidpro/issues/110413177/

Fixes failing flow export when there are dynamic groups

---

temba/contacts/tests.py
temba/utils/__init__.py
temba/values/tests.py

Fixes:
https://app.getsentry.com/nyaruka/rapidpro/issues/109937499/

Fix us trying to parse UUIDs into invalid dates by catching bad offsets

---

karma/test_completions.coffee
static/coffee/completions.coffee

- Fixes completions bug to now show pop up for variables after quote
- Fixes issue of removing next character when balancing paratheses

Fix js completions

---

temba/api/tests/test_v2.py
temba/api/v1/serializers.py
temba/api/v1/views.py
temba/api/v2/serializers.py
temba/api/v2/views.py
temba/channels/tasks.py
temba/msgs/migrations/0043_auto_20160222_2212.py
temba/msgs/migrations/0044_auto_20160222_2214.py
temba/msgs/migrations/0045_populate_modified_on.py
temba/msgs/models.py

Migration to populate modified_on for null items.
(the delivered-to-modified branch will be merged and pushed first)

Populate modified

---

static/coffee/completions.coffee
static/coffee/flows/controllers.coffee
static/coffee/flows/services.coffee
static/coffee/temba.coffee
templates/msgs/msg_send_modal.haml

Follow up on https://github.com/nyaruka/rapidpro/pull/562#issuecomment-183108759
- Disable ESC to close modal so ESC will be closing popup if pop up is shown

Disable modal to close on ESC key

---

temba/api/tests/test_v2.py
temba/api/v2/serializers.py
temba/api/v2/urls.py
temba/api/v2/views.py
temba/msgs/models.py
temba/settings_common.py

* Tweaked rate limits so that messages and contacts are throttled separately
* Added org and broadcasts listing endpoints
* Moar testing

API v2 Part 6 (?)

---

temba/api/tests/test_v1.py
temba/api/v1/serializers.py
temba/api/v1/views.py
temba/msgs/models.py

Added action to bulk contact action endpoint for archiving all of a contact's incoming messages

Archive contact messages over API

---

temba/channels/models.py
temba/channels/tests.py

according to docs https://www.clickatell.com/developers/api-docs/http-overview/

turn on unicode flag when sending with clickatell

---

temba/msgs/management/commands/msg_console.py
temba/msgs/tests.py

So that one can luanch it like..
`./manage.py msg_console --org "Nyaruka RS" --urn twitter:kinyarwandanet`

Some tweaks to the message console

---

temba/api/v1/serializers.py
temba/api/v2/views.py
temba/campaigns/models.py
temba/campaigns/tests.py
temba/campaigns/views.py
temba/contacts/fields.py
temba/contacts/models.py
temba/contacts/tests.py
temba/contacts/views.py
temba/flows/models.py
temba/flows/tests.py
temba/flows/views.py
temba/values/models.py

FIxes released group that craches the flow editor, api flow list
- https://app.getsentry.com/nyaruka/textit/issues/112091636/
- https://app.getsentry.com/nyaruka/textit/issues/112090513/
- https://app.getsentry.com/nyaruka/textit/issues/112090514/

Prevent possible undo delete group by flow

---

temba/channels/models.py
temba/channels/tests.py
temba/msgs/models.py
temba/orgs/models.py
temba/schedules/models.py
temba/schedules/tests.py
templates/channels/channel_claim_external.haml

Needed for one of our integrations..

Ability to configure external channels to replace numbers with no leading +

---

.travis.yml
temba/flows/models.py
temba/flows/tests.py

Fixes: https://app.getsentry.com/nyaruka/rapidpro/issues/117827814/

Fix case where in memory model is not up to date with db

---

setup.cfg
temba/campaigns/tasks.py
temba/campaigns/tests.py
temba/campaigns/views.py
temba/channels/models.py
temba/channels/tests.py
temba/channels/views.py
temba/contacts/tests.py
temba/contacts/views.py
temba/flows/models.py
temba/flows/tests.py
temba/flows/views.py
temba/msgs/models.py
temba/orgs/models.py
temba/perf_tests.py
temba/schedules/models.py
temba/triggers/tests.py
temba/triggers/views.py
temba/utils/__init__.py
temba/utils/models.py
temba/utils/tests.py

PEP cleanup part IX

---

setup.cfg
temba/api/models.py
temba/api/tasks.py
temba/api/tests/test_v2.py
temba/api/v1/views.py
temba/api/views.py
temba/campaigns/models.py
temba/channels/models.py
temba/channels/tests.py
temba/channels/views.py
temba/contacts/models.py
temba/contacts/tests.py
temba/contacts/views.py
temba/flows/models.py
temba/flows/tests.py
temba/orgs/models.py
temba/orgs/views.py
temba/values/tests.py

Pep cleanup part XI

---

temba/channels/handlers.py
temba/channels/tests.py
temba/contacts/models.py

Add facebook profile lookup for new contacts for non-anon orgs

---

setup.cfg
temba/api/tests/test_models.py
temba/api/tests/test_v1.py
temba/api/tests/test_v2.py
temba/channels/handlers.py
temba/channels/models.py
temba/channels/tasks.py
temba/channels/tests.py
temba/channels/views.py
temba/contacts/tests.py
temba/contacts/views.py
temba/flows/models.py
temba/flows/tasks.py
temba/flows/tests.py
temba/flows/views.py
temba/ivr/tests.py
temba/msgs/models.py
temba/msgs/tests.py
temba/nexmo.py
temba/orgs/models.py
temba/orgs/tests.py
temba/orgs/views.py
temba/schedules/tasks.py
temba/triggers/tests.py
temba/values/models.py
temba/values/tests.py

Final instalment (F841 is unused variables)

PEP cleanup part 13

---

templates/flows/flow_list.haml
templates/flows/flow_results.haml

Add new export dialog to results page

---

.travis.yml
temba/auth_tweaks/migrations/0001_initial.py
temba/auth_tweaks/models.py
temba/auth_tweaks/tests.py
temba/channels/migrations/0031_auto_20160414_0642.py
temba/contacts/migrations/0035_auto_20160414_0642.py
temba/flows/migrations/0053_auto_20160414_0642.py
temba/ivr/migrations/0009_auto_20160414_0642.py
temba/locations/migrations/0005_auto_20160414_0642.py
temba/msgs/migrations/0050_auto_20160414_0642.py
temba/orgs/tests.py

Adds all the missing migrations (typically updating `choices` or `help_text`) and adds check to Travis for new missing migrations.

Missing migrations

---

temba/api/tests/test_v1.py
temba/api/tests/test_v2.py
temba/api/v1/serializers.py
temba/api/v1/views.py
temba/api/v2/serializers.py
temba/api/v2/views.py
temba/contacts/views.py
temba/flows/views.py
temba/msgs/models.py
temba/msgs/tests.py
temba/msgs/views.py

* Namespace the visibility constants to simplify imports
* Fixes v2 messages endpoint to not return archive messages when fetching by label

Message visibility

---

temba/api/v1/serializers.py
temba/channels/models.py
temba/channels/tests.py
temba/channels/views.py
temba/contacts/models.py
temba/flows/models.py
temba/ivr/models.py
temba/ivr/tests.py
temba/orgs/models.py

The main catch is that we can't normalize numbers that don't have country code and don't start with + if we have two channels from different countries, but lots of other small changes, especially in IVR land.

first cut at having multiple channels with different countries on one org

---

temba/api/management/__init__.py
temba/api/management/commands/apiaudit.py

Returns status code, time taken, and main index used

Management command for auditing API requests

---

temba/triggers/models.py
temba/triggers/tests.py

Fixes: https://app.getsentry.com/nyaruka/rapidpro/issues/124326143/

Fix trigger imports when they reference a channel

---

temba/flows/models.py
temba/flows/tests.py

Fixes: https://app.getsentry.com/nyaruka/textit/issues/126741732/

Fix us blowing up when a msg is added more than once to a flowstep

---

karma/flows/test_directives.coffee
static/coffee/flows/app.coffee
static/coffee/flows/controllers.coffee
static/coffee/flows/services.coffee
static/less/flow_editor.less

Turn off angular debug which is on by default

Angular debug

---

temba/contacts/tests.py
temba/contacts/views.py
templates/contacts/contact_history.haml

Shows Failed, No Answer, Busy, and Canceled calls on contact history.

Show failed calls on contact history

---

temba/channels/handlers.py
temba/channels/tests.py

This makes sure we deal with them in either state (long int or string)

Facebook is changing their ids to come across as strings

---

temba/flows/models.py
temba/flows/tests.py

Fixes https://app.getsentry.com/nyaruka/rapidpro/issues/129032612/

Fix ward lookup when using aliases

---

karma/flows/test_controllers.coffee
static/coffee/flows/controllers.coffee

Add isRuleComplete tests and fix bug

---

temba/contacts/models.py
temba/flows/tests.py
temba/utils/models.py

Also cleans up dupe values that exist when being set.

Fix export error when there are dupe Value rows for a contact.

---

temba/flows/views.py

Updates terminology from 'text messaging' to 'messaging' to gel with new channel types and clarifies Flow.Survey creates a Surveyor flow.

Update Flow Creation Terminology

---

temba/contacts/models.py
temba/flows/models.py
temba/flows/tests.py
temba/msgs/models.py
templates/partials/action_editor.haml

Even across schemes
Fix minor styling on flow editor

Centralize setting of affinity, make sure incoming messages switch channel

---

temba/channels/handlers.py
temba/channels/tests.py

These were blowing up since this is a format FB doesn't document.

Fix incoming FB links

---

temba/channels/handlers.py
temba/channels/tests.py
temba/contacts/models.py
temba/contacts/tests.py

Fixes:
https://app.getsentry.com/nyaruka/textit/issues/142310760/
And:
https://app.getsentry.com/nyaruka/textit/issues/142004502/

Fix a few telegram issues

---

temba/flows/models.py
temba/flows/tests.py
temba/nexmo.py
temba/triggers/tests.py

Also adds a couple updates for coverage

Tweak expiry

---

media/test_flows/migrate_to_9.json
media/test_flows/triggered.json
temba/flows/flow_migrations.py
temba/flows/models.py
temba/flows/tests.py

* Migrate @extra.contact to @parent.contact
* Fix replacement regexes in migrate_to_9
* Add tests for referencing webhook data after a start flow and trigger flow
Fixes rapidpro/rapidpro#285

Migrate @extra.contact to @parent.contact

---

temba/flows/models.py
temba/flows/tests.py
temba/flows/views.py

Tweak messaging when setting simulator URNs, add mailto to completions

---

pip-freeze.txt
pip-requires.txt

Update phone numbers library to latest

---

temba/channels/tests.py
temba/channels/views.py

Fixes https://github.com/rapidpro/rapidpro/issues/295

Ignore message missing text from Android

---

temba/orgs/migrations/0020_auto_20160726_1510.py
temba/orgs/models.py
temba/orgs/tests.py
templates/orgs/topup_list.haml

Addresses https://github.com/rapidpro/rapidpro/issues/283

Allow nullable topup price

---

temba/msgs/models.py
temba/msgs/tests.py

Addresses https://github.com/rapidpro/rapidpro/issues/293

Add message status in the message exports

---

templates/flows/flow_editor.haml

Show variables in add and del group actions

---

templates/triggers/trigger_schedule.haml

Fixes rapidpro/rapidpro#301
Sentry: fbe4ad10a40c4bc9ba4b3c80c72536a4

Ensure omnibox is initialized when reloaded in formax

---

temba/channels/tests.py
templates/flows/flow_results.haml

Shows a '-' instead of 'null'.

Change display on flow results with null urns

---

temba/contacts/models.py
temba/contacts/tests.py

Don't add + when trying to normalize numbers that lead with 0

---

media/test_flows/flow_starts.json
static/examples/sample_flows.json
temba/api/tests/test_v2.py
temba/campaigns/tests.py
temba/flows/migrations/0060_exit_flowruns.py
temba/flows/models.py
temba/flows/tests.py

Exit Flows

---

temba/settings_common.py

Go to our rebranded docs instead.
Fixes rapidpro/rapidpro#315

Fix docs link for RapidPro

---

templates/frame.haml

* Honor command click on org name
* Don't show toggle if there's only one org

Allow meta clicks on org, only show toggle for more than one org

---

temba/flows/flow_migrations.py
temba/flows/models.py
temba/ivr/tests.py

Fixes: https://app.getsentry.com/nyaruka/textit/issues/150959385/

IVR calls should ensure latest flow version

---

temba/orgs/models.py

Add a line in the ledger to show expired credits

Show expired credits in ledger

---

temba/channels/tests.py
temba/channels/views.py
temba/orgs/views.py
templates/channels/channel_claim_viber.haml
templates/channels/channel_read.haml

When we don't know the service id.

Tweaks to link to viber claim page instead of read 

---

temba/flows/flow_migrations.py
temba/flows/migrations/0068_fix_empty_flow_starts.py
temba/flows/models.py
temba/flows/tests.py

Takes a different approach of rewriting the definition (adding some utility migration methods in the process) then migration that definition forward.
@ericnewcomer plz review

Fixes empty replies by using revision definitions

---

temba/api/tests/test_v2.py
temba/api/v2/serializers.py
temba/api/v2/views.py

There are no request level transactions in API v2 so this explicitly puts a transaction around the `save` and `post_save` methods of our write serializers.

Explicit transactions for API v2 writes

---

templates/contacts/contact_read.haml

Show stopped status on contact read page, add rollover to explain icon

---

temba/orgs/models.py

Show initial credits in ledger

---

temba/api/tests/test_v2.py
temba/api/v2/views.py

Also updates the resthook subscribers endpoint to use new delete functionality

Contact deleting over API v2

---

temba/channels/models.py
temba/contacts/models.py
temba/flows/models.py
temba/msgs/models.py

Reduce our logging around squashing

---

temba/flows/models.py

Do resumption in same thread for test contacts

---

temba/channels/handlers.py
temba/ivr/tests.py

Fix for https://sentry.io/nyaruka/textit/issues/96672866/

Don't blow up if there isn't a valid channel for incoming call

---

temba/api/tests/test_v2.py
temba/api/v2/serializers.py
temba/api/v2/urls.py
temba/api/v2/views.py

* Fixes some docstring mistakes
* Fixes some missing param filtering
* Adds some prefetches
Goes with https://github.com/rapidpro/rapidpro-python/pull/26

Tweaks to resthook related endpoints

---

media/test_flows/parent_child_loop.json
temba/flows/models.py
temba/flows/tests.py

Deal with spurious flow exits originating from illegitimate child flows.

Don't exit ancestors for other contacts

---

temba/channels/handlers.py
temba/channels/tests.py

Addresses https://sentry.io/nyaruka/rapidpro/issues/159089775/

ignore Viber status requests for incoming messages

---

pip-freeze.txt
pip-requires.txt
temba/channels/views.py
temba/contacts/tests.py
temba/contacts/views.py
temba/flows/tests.py
temba/flows/views.py
temba/msgs/models.py
temba/triggers/views.py
templates/campaigns/campaign_read.haml
templates/campaigns/campaignevent_read.haml
templates/contacts/contact_history.haml
templates/contacts/contact_read.haml
templates/flows/flow_export.haml
templates/flows/flow_results.haml
templates/flows/flow_results_contact.haml
templates/msgs/message_box.haml
templates/triggers/trigger_list.haml

Address https://github.com/rapidpro/rapidpro/issues/313
Also switches contact and channel read pages to use new lookup by slug functionality added in latest smartmin.

Use flow UUID in flow editor URLs

---

locale/en_US/LC_MESSAGES/django.po

New base po file as a result of running
```% python manage.py makemessages -l en_US ```
We haven't updated this file since 2014 which can lead to lost translations if transifex updates from source control.

Update base po file

---

templates/flows/flow_list.haml

fix flow list

---

templates/flows/flow_list.haml

Small fix to use proper id or uuid depending on location

Use the flow id for id-focused views

---

temba/channels/models.py

https://textit.uservoice.com/admin/tickets/3965

Don't include response ids if it's been 12 hours for chikka

---

temba/api/tests/test_v2.py
temba/api/v2/serializers.py
temba/api/v2/views.py
temba/contacts/models.py

```
POST /api/v2/fields.json
{
"label": "Nick name",
"value_type": "text"
}
POST /api/v2/fields.json?key=nick_name
{
"label": "New label",
"value_type": "numeric"
}
```

API v2 field creating and updating

---

temba/channels/models.py
temba/channels/tests.py

Only REPLY within 24 hours, fall back to SEND when REPLY fails

Update Chikka Replies

---

temba/flows/tests.py
temba/flows/views.py

Fixes https://github.com/rapidpro/rapidpro/issues/352

display time in proper org timezone on recent messages tooltip

---

temba/campaigns/tasks.py
temba/channels/tasks.py
temba/contacts/tasks.py
temba/flows/tasks.py

Doesn't change all possible tasks yet - trying to limit the changes so it's easier to keep and eye on the modified tasks and verify that everything is working as expected.

Switch more suitable tasks to use @nonoverlapping_task

---

.bowerrc
.gitignore
.travis.yml
bower.json
package.json
static/less/style.less
temba/campaigns/tests.py
temba/flows/migrations/0073_auto_20161019_0146.py
temba/flows/models.py
temba/flows/views.py
temba/settings_common.py
templates/flows/flow_list.haml
templates/frame.haml
templates/smartmin/base.html

* Disallow archiving of campaign flows
* Add toastr for short user notices
* Add bower for managing web dependencies

Archived campaign flows

---

static/less/style.less
templates/contacts/contact_update.haml

* Flow create dialog now can grow to hold the entire default set of widgets
* Fix urn wrapping on contact edit dialog

Styling tweaks

---

temba/flows/models.py
temba/flows/tests.py

* Fixes interrupted child flows to also interrupt their parents
Fixes rapidpro/rapidpro#309

Interrupted Child Flows

---

temba/orgs/tests.py
templates/orgs/org_accounts.haml

Add detailed summary for accounts in an org

---

temba/api/tests/test_v2.py
temba/api/v2/serializers.py
temba/api/v2/views.py

UReport is now using values/path so this can be removed

API v2: no more steps on runs endpoint

---

temba/contacts/models.py
temba/contacts/tests.py

Fixes: https://textit.uservoice.com/admin/tickets/4152

Make query field references case insensitive

---

temba/flows/tasks.py
temba/msgs/tasks.py
temba/orgs/models.py

This should prevent the case where we spiral out of control when there's an issue with messages going out slowly.

Check our queue size before requeuing

---

temba/channels/handlers.py
temba/channels/models.py
temba/flows/views.py
temba/ivr/tests.py
temba/triggers/tests.py
temba/triggers/views.py
templates/flows/flow_broadcast.haml
templates/flows/flow_editor.haml
templates/flows/flow_list.haml
templates/triggers/trigger_list.haml

Don't auto-archive IVR flows when the last calling channel is released. Likewise, adjust this behavior for triggers. Also returns a 200 to Twilio when no channel is found with a message instead of a 400.

Ungated IVR

---

templates/partials/split_editor.haml

https://textit.uservoice.com/admin/tickets/4316

Remove maxlength on webhook

---

temba/flows/migrations/0049_install_flowcount_triggers.py
temba/sql/0049_flows.sql
temba/sql/current_flows.sql

Moving the flow triggers to their own files with the current sow so that when I update them, the changes will be reviewable.

Move flow triggers to discrete files

---

templates/frame.haml

load remote js files asynchronously to prevent cross-origin blocking

---

static/coffee/analytics.coffee

Fixes https://github.com/rapidpro/rapidpro/issues/393

Fix open ended responses counts on analytics

---

temba/channels/models.py
temba/channels/tests.py

Automatically stop twilio contacts who have opted out

---

temba/flows/migrations/0076_auto_20161215_2209.py
temba/flows/migrations/0077_auto_20161215_2232.py
temba/flows/models.py

New and improved path count backfill that includes null destinations.

Backfill FlowPathCount

---

temba/contacts/tests.py
temba/contacts/views.py
templates/campaigns/campaign_read.haml
templates/contacts/contact_import.haml
templates/contacts/contact_list.haml
templates/contacts/contact_read.haml

Fixes https://github.com/rapidpro/rapidpro/issues/416

Contact filter page should use group UUID to help API users

---

temba/channels/handlers.py
temba/channels/tests.py
temba/channels/views.py

Globe uses various shortcodes on different networks and handles mapping them for us.. this just accepts them on the same channel.

Allow any incoming msgs on Globe channels since they do number mapping

---

static/less/style.less
templates/frame.haml

Option for brand name in lieu of a logo.

No Logo Branding

---

temba/channels/handlers.py
temba/channels/tests.py

Fixes https://github.com/rapidpro/rapidpro/issues/422. Also adds some real test coverage

Don't throw exception if external handler is asked to update incoming message

---

temba/channels/handlers.py

Just a small change to avoid a second database write when saving a Nexmo message

Nexmo handler tweak

---

temba/contacts/tests.py
temba/orgs/tests.py
templates/campaigns/campaign_read.haml
templates/schedules/schedule_update.haml

* Fix use of = for equality in template
* Fix test which tries to re-use initial form data in submission

Django 1.10 tweaks

---

temba/flows/views.py
temba/ivr/views.py
temba/locations/views.py
temba/orgs/views.py
temba/reports/views.py
temba/utils/__init__.py

Django 1.7 added JsonResponse. Requires https://github.com/nyaruka/textit/pull/60

Simpler json responses

---

temba/flows/views.py

Flow results performance fix

---

templates/channels/channel_claim_facebook.haml
templates/channels/channel_configuration.haml

Without it we can't start a conversation after 24 hours have passed

Tell user to get pages_messaging_subscriptions permission for FB

---

karma/flows/test_controllers.coffee
media/test_flows/favorites.json
package.json
temba/flows/models.py
temba/flows/tests.py
temba/flows/views.py

And add tests for that
Fixes https://sentry.io/nyaruka/textit/issues/207265888/

Fix RecentMessages no longer supporting requests with multiple rules

---

temba/contacts/search.py

By fetching locations in separate query

Improve performance of contact searches by location

---

temba/channels/handlers.py
temba/flows/models.py
temba/flows/tests.py
temba/ivr/migrations/0014_add_twilio_status_callback.py
temba/ivr/models.py
temba/ivr/tests.py
temba/orgs/models.py

This fixes the issue of inbound calls getting stuck as in-progress in some cases.
* Set the optional status callback url for our twiml apps
* Add migration to update existing twiml apps under our control to add these callbacks

IVR Fixes 1: Fix open calls

---

temba/channels/tests.py
temba/channels/views.py
temba/tests.py

No tests for this previously so didn't catch the regression error.
Fixes https://sentry.io/nyaruka/textit/issues/209331472/

Twilio: fix number searching

---

temba/api/tests/test_v1.py
temba/flows/models.py

Fixes https://sentry.io/nyaruka/rapidpro/issues/209017818/

API v1: fix run serialization when step messages are purged

---

pip-freeze.txt
pip-requires.txt
temba/settings_common.py

Remove no longer needed django-modeltranslation

---

temba/locations/management/commands/import_geojson.py

Changes in Django management commands..

Fix import-geojson management command

---

media/test_flows/multi_timeout.json
media/test_flows/timeout_loop.json
temba/flows/models.py
temba/flows/tests.py

This is somewhat treating a symptom of having two active runs active at once (likely due to a race of campaigns with flow starts) but prevents us blowing up when we reach a timeout and the most active step is not actually the timeout step.

Fix broken timeout handling when there is a race

---

pip-freeze.txt

To get https://github.com/rapidpro/expressions/pull/19

Update to latest expressions

---

temba/settings.py.perf
temba/utils/management/commands/perf_test.py

* Switch to milliseconds
* Add custom settings file which enables compression etc
* Split up results by org

perf_test update

---

pip-freeze.txt
temba/channels/handlers.py

Can't ship this without running ansible on machines first.

Determine file type from libmagic

---

temba/ivr/models.py
temba/msgs/models.py

Don't link to channel logs if the channel isn't active.
Needs unit test, waiting for https://github.com/nyaruka/rapidpro/pull/1132 first.

Inactive channel logs

---

README.md
temba/channels/handlers.py
temba/channels/models.py
temba/channels/tests.py
temba/channels/views.py
temba/ivr/clients.py
temba/ivr/tests.py
temba/ivr/views.py
temba/orgs/views.py
temba/tests.py
temba/utils/http.py
temba/utils/nexmo.py
temba/utils/twilio.py
temba/utils/twitter.py
templates/channels/channellog_list.haml

Also allows logging details of Twilio requests.

Clean up logging for channels

---

temba/utils/management/commands/perf_test.py

* Improve error handling when response is not 200
* Make contact searches a bit more comprehensive

perf_test tweaks

---

temba/flows/tests.py
temba/flows/views.py

Fix https://github.com/rapidpro/rapidpro/issues/428

exclude test contact from flow results

---

temba/flows/models.py
temba/flows/tests.py

More adjustment to https://github.com/nyaruka/rapidpro/pull/1152 to address https://github.com/rapidpro/rapidpro/issues/440

fix export flow results messages ordering

---

temba/contacts/search.py
temba/contacts/tests.py

... where there is more than one condition on name/URN. Doh. Fixes these https://sentry.io/nyaruka/textit/issues/235246368/

Search: fix queries like "foo bar" 

---

temba/utils/management/commands/make_test_db.py
temba/utils/management/commands/perf_test.py
temba/utils/tests.py

Still a work in progress and there are some limitations to bear in mind:
- No non-flow messages
- It's not setting recent messages or counts for path segments
- No broadcasts - i.e. no flow starts against groups

Performance: create runs, steps and messages in the testing database

---

temba/utils/__init__.py
temba/utils/tests.py

* Expand base64 charset
* Fix decode validity heuristic

More twilio base64 fixes tweaks

---

static/coffee/simulator.coffee
temba/flows/models.py
temba/flows/tests.py
temba/flows/views.py
templates/flows/flow_editor.haml

Give some better feedback to user 
And fixes https://sentry.io/nyaruka/textit/issues/205392646/

Ussd simulation

---

temba/channels/models.py
temba/channels/tests.py
temba/contacts/models.py
temba/contacts/tests.py
temba/flows/models.py
temba/flows/tests.py
temba/msgs/models.py
temba/msgs/tests.py
temba/utils/tests.py

Want to test this a bit more but making PR to discuss some of the changes

Context building improvements (WIP)

---

temba/msgs/tasks.py

Can't figure out a way to unit test this since it is threaded.. but we found a case where unsurprisingly us just skipping the message entirely (because of the `if`) led to shitty behavior because we only processed the message 10 minutes later when it timed out as an unhandled message.
This locks until we can access the message, which does tie up a handler thread, but since message processing tends to be quick and it is at a contact level seems reasonably safe.

Block on handling incoming msgs so we dont process them forever away

---

media/test_flows/stacked_exits.json
media/test_flows/stacked_response_exits.json
media/test_flows/stacked_webhook_exits.json
temba/flows/models.py
temba/flows/tests.py

Also known as, this is why we are refactoring our engine..

Fix subflow case where multiples stacked immediate exits wouldn't continue

---

static/less/formax.less
templates/flows/flow_export_results.haml
templates/orgs/org_credits.haml
templates/orgs/org_languages.haml
templates/orgs/org_manage_accounts.haml
templates/orgs/org_nexmo_connect.haml
templates/orgs/org_plivo_connect.haml
templates/orgs/org_resthooks.haml
templates/orgs/org_twilio_connect.haml
templates/smartmin/form.html
templates/triggers/trigger_create.haml

Change default forms to be vertical and remove anywhere horizontal-form was restyled to appear vertical.

Vertical forms as default

---

temba/flows/tests.py
temba/triggers/models.py

This will let us mark the trigger as fired immediately (in the case of schedules) so we don't double start really giant flow starts.

Use flow starts for triggers that operate on groups

---

temba/flows/models.py
temba/orgs/tests.py

Fix https://github.com/rapidpro/rapidpro/issues/539

Voice flows import shoudl keep the expiration time at 15 min at most

---

templates/channels/channellog_list.haml
templates/channels/channellog_log.haml

Fix https://github.com/rapidpro/rapidpro/issues/540

Hide invalid channel log request time

---

temba/msgs/models.py
temba/msgs/tests.py
temba/msgs/views.py

Fixes https://sentry.io/nyaruka/rapidpro/issues/262161071/activity/

Fix exporting messages by a label folder

---

static/coffee/flows/widgets.coffee
static/coffee/temba.coffee

Select2s should show "Add new" option even if there is partial match

---

temba/channels/models.py

Fix https://sentry.io/nyaruka/rapidpro/issues/276347548/

Switch Msg.media to Msg.attachments

---

temba/api/tests/test_v2.py
temba/api/v2/views.py

Expose org credit information on API org endpoint

---

temba/channels/tests.py
temba/msgs/models.py
temba/msgs/tests.py

To avoid https://sentry.io/nyaruka/rapidpro/issues/299477490/

Clean incoming message text

---

temba/channels/models.py
temba/contacts/models.py
temba/flows/models.py
temba/msgs/models.py

* Include channels in flow server requests
* Include preferred channel with contact
* Don't expect msg_received events to be repeated in server output
* Fix urn selection for send_msg events

New engine tweaks

---

temba/channels/handlers.py
temba/channels/tests.py
temba/channels/urls.py

Will allow stopping of contacts by Courier

Stop contact

---

temba/channels/models.py
temba/contacts/models.py
temba/flows/models.py
temba/msgs/models.py
temba/utils/goflow.py

For https://github.com/nyaruka/goflow/pull/62 and also introduces a request builder to the goflow client. Seems useful to keep as much of the goflow code in a few places as possible for now.

New engine changes

---

temba/api/v1/tests.py
temba/flows/models.py

This will fix https://sentry.io/nyaruka/rapidpro/issues/312163157/

Fix surveyor

---

temba/orgs/models.py
temba/triggers/tests.py
temba/triggers/views.py

Fixes bug where we currently claim the trigger already exists

Allow editing of conversation triggers

---

temba/api/v1/serializers.py
temba/api/v1/tests.py

* Allow empty contact names but make them null

Handle Surveyor submissions with empty contact names

---

temba/channels/handlers.py
temba/channels/models.py
temba/contacts/models.py
temba/contacts/views.py
temba/msgs/models.py
temba/orgs/models.py
temba/public/views.py
temba/utils/__init__.py
temba/utils/export.py
temba/utils/management/commands/collect_sql.py
temba/utils/profiler.py
temba/utils/tests.py
temba/utils/text.py

Move clean string to its own module

---

temba/channels/handlers.py
temba/channels/models.py
temba/channels/tests.py
temba/channels/types/clickatell/__init__.py
temba/channels/types/clickatell/tests.py
temba/channels/types/clickatell/type.py
temba/channels/types/clickatell/views.py
temba/channels/views.py
temba/settings_common.py
templates/channels/channel_claim.haml
templates/channels/types/clickatell/claim.haml

Dynamic channels 3

---

temba/flows/models.py
temba/flows/tests.py

Fix for https://github.com/rapidpro/rapidpro/issues/636

Support text ending in number as a number E.G:  should match 250

---

temba/channels/migrations/0079_auto_20170910_1731.py

the reason on the TwiML errors was this, Fixed them on prod servers already

Fix TwiML migrations queryset

---

temba/flows/models.py
temba/flows/tests.py

Addresses https://github.com/rapidpro/rapidpro/issues/627

Prevent creating contact group at flow run time

---

temba/msgs/migrations/0094_auto_20170501_1641.py

Stepped through each rev that added a migration in the msgs app and the problems appear to start with this one. Recreating the sql function appears to fix it, and maybe removing fields is the thing that causes problems?

Fix SQL function after removing fields in migration

---

temba/api/v2/serializers.py
temba/api/v2/tests.py
temba/contacts/models.py
temba/contacts/tests.py
temba/contacts/views.py

This bug is blocking everything that need to create a group like signups and contact imports

Should filter user groups by org before limiting to 250

---

temba/channels/tests.py
temba/triggers/tasks.py
temba/triggers/tests.py

Fix https://sentry.io/nyaruka/rapidpro/issues/369638817/

Create channel event only for active channels

---

temba/contacts/models.py
temba/contacts/tests.py

Fixed https://github.com/resistbot/rapidbot/issues/14
And likely https://github.com/resistbot/rapidbot/issues/32 as well

fixes viber validation, can be up to 24 chars

---

media/test_flows/dependencies.json
temba/utils/expressions.py

See: https://sentry.io/nyaruka/textit/issues/388647770/

Fix dates blowing up contact field extraction

---

pip-freeze.txt

Fixes https://code.djangoproject.com/ticket/28441 amongst other things, which I ran into after a brew update.

Update to latest Django 1.11.6

---

CHANGELOG.md
temba/channels/models.py
temba/channels/tests.py

We were showing all channelogs here instead of those only for the channel or msg.

only show single channellog in cases where there is no msg

---

temba/utils/management/commands/test_db.py

So the command doesn't take an hour with default settings..

Tweak test_db command defaults

---

temba/api/v2/serializers.py
temba/api/v2/tests.py
temba/api/v2/views.py

https://github.com/rapidpro/rapidpro/issues/675

Add archived field to campaings API endpoint

---

temba/api/v2/tests.py
temba/api/v2/views.py

Fixes https://github.com/rapidpro/rapidpro/issues/676

Flows API endpoint should filter out campaign message flow type

---

temba/channels/handlers.py
temba/channels/tests.py

Fixes https://sentry.io/nyaruka/rapidpro/issues/399451873/

Ignore requests missing text for incoming message from Infobip

---

temba/channels/types/twilio/tests.py
temba/channels/types/twilio/views.py
temba/channels/types/twilio_messaging_service/tests.py
temba/channels/types/twilio_messaging_service/views.py

This fixes a bug of saving wrong config introduced in #1452

Fix twilio config

---

temba/flows/views.py
templates/flows/flow_activity_chart.haml
templates/flows/flow_results.haml
templates/smartmin/list.haml

* Disable flow results for now
* Show "no results" case
* Fix a couple small console errors

Temporarily disable new flow results

---

temba/orgs/models.py
temba/orgs/tasks.py
temba/orgs/tests.py
temba/orgs/views.py

* Do work in background task
* Avoid contact table join
* Tweaks to org update admin page

Perform apply_topups as a task

---

temba/campaigns/models.py

Do not create FlowStart object if we have exactly one contact

---

temba/api/v1/serializers.py
temba/campaigns/models.py
temba/channels/handlers.py
temba/contacts/models.py
temba/flows/models.py
temba/flows/tests.py
temba/msgs/models.py
temba/msgs/tests.py
temba/orgs/models.py

Share objects and cache things

Reduce queries during flow starts

---

temba/flows/models.py
temba/flows/tasks.py
temba/flows/tests.py
temba/utils/profiler.py

* Move some stuff into helper methods
* Don't pre-calculate number of sheets needed but add as needed
* Removes SegmentProfiler which has been replaced by QueryTracker and wasn't actually doing anything in our tests

Simplications to ExportFlowResultsTask

---

temba/utils/dates.py
temba/utils/tests.py

Fixes https://sentry.io/nyaruka/textit/issues/421752876/

Time parsing fix

---

temba/api/models.py
temba/orgs/tests.py

https://sentry.io/nyaruka/textit/issues/173510215/

Fix deleting resthooks

---

temba/msgs/tasks.py

https://sentry.io/nyaruka/rapidpro/issues/427117861/

Tweak process_message_task to not blow up if message doesn't exist

---

temba/contacts/search/parser.py
temba/contacts/tests.py

Tweaks contact searching so that these conditions check the type specific column

Search fix for set/not-set conditions

---

temba/channels/types/twitter_activity/tests.py
temba/channels/types/twitter_activity/type.py
temba/channels/types/twitter_activity/views.py
temba/utils/twitter.py

Tweaks to current twitter activity to support current "beta" API endpoints.

tweaks to rapidpro side for current twitter activity APIs

---

temba/settings_common.py
templates/includes/nav.haml

Fixes: rapidpro/rapidpro/issues/723

Show dashboard link even if org is chosen

---

temba/orgs/tests.py
temba/orgs/views.py

Fixes: rapidpro/rapidpro/issues/724

Order transfer credit options by name

---

media/test_flows/action_packed.json
temba/contacts/models.py
temba/flows/models.py
temba/flows/tests.py
temba/tests.py

Lots o' flow-based action tests

Action packed

---

temba/channels/models.py
temba/channels/types/arabiacell/__init__.py
temba/channels/types/arabiacell/tests.py
temba/channels/types/arabiacell/type.py
temba/channels/types/arabiacell/views.py
temba/channels/types/mtarget/type.py
temba/channels/views.py
temba/settings_common.py
templates/channels/channel_configuration.haml

Continuing to try to make these as easy to add as possible, moved recommended and available as attributes on channel type.

add arabia cell channel type

---

temba/flows/models.py
temba/ivr/tests.py

https://sentry.io/nyaruka/textit/issues/464847420/

Fix using PlayAction in simulator and add tests

---

temba/channels/courier.py
temba/channels/types/external/tests.py
temba/channels/types/external/views.py

Fixes: https://sentry.io/nyaruka/textit/issues/470059657/

fix external claim page, rename auth_urn for courier

---

temba/orgs/models.py
temba/orgs/tests.py

fixes https://sentry.io/nyaruka/rapidpro/issues/476973148/

fix negative cache ttl for topups

---

temba/contacts/models.py
temba/contacts/tests.py
temba/utils/urns/__init__.py
temba/utils/urns/tests.py
temba/utils/urns/urns.py

See https://github.com/nyaruka/gocommon/pull/11

Update URN parsing to match gocommon changes

---

.travis.yml
media/test_flows/action_packed.json
static/coffee/simulator_go.coffee
temba/api/tests.py
temba/channels/models.py
temba/flows/models.py
temba/flows/tests.py
temba/flows/views.py
temba/settings_common.py
temba/settings_travis.py
temba/tests/base.py
temba/utils/goflow/client.py
temba/utils/goflow/serialize.py
temba/utils/goflow/tests.py

* use a broadcast for broadcast_created, a msg for msg_created
* add a fake channel to channel assets for simulator use so all messages get "sent"

Latest goflow

---

.travis.yml
static/coffee/simulator_go.coffee
temba/flows/models.py
temba/flows/tests.py
temba/tests/base.py
temba/utils/goflow/client.py

No more log entries / logs.. just events

Update to latest goflow

---

temba/contacts/tests.py
temba/utils/__init__.py
temba/utils/tests.py

Saw we had a few turds in our values. This makes sure they don't blow stuff up.

do the right thing when we are presented with NaN decimals

---

temba/flows/tests.py
temba/flows/views.py
temba/settings_common.py
templates/channels/channel_claim.haml

Allows brands to specify which flow types they support

Configurable flow types on brand

---

temba/contacts/models.py
temba/contacts/tests.py
temba/utils/dates.py
temba/utils/tests.py

Fixes: https://sentry.io/nyaruka/rapidpro/issues/509015050/

support ISO dates (not just datetimes)

---

temba/contacts/search/parser.py
temba/contacts/tests.py

Signed-off-by: Dražen Odobašić <dodobas@quaternion.co>

Evaluate contact field with no value as False

---

temba/flows/models.py
temba/orgs/models.py

* more python3 fixes for errors reported by sentry

Fix not supported operators

---

temba/flows/migrations/0150_populate_run_events.py

https://sentry.io/nyaruka/rapidpro/issues/509995607/?referrer=slack

Use force_text on uuids read from redis

---

temba/channels/handlers.py

First step to ripping these all out, double check non are not being remapped via nginx.

log any calls to non-courier-handles

---

temba/utils/goflow/serialize.py
temba/utils/goflow/tests.py

to go with: https://github.com/nyaruka/goflow/pull/213

serialize contact field label as name instead

---

templates/flows/flow_list.haml

FIx https://sentry.io/nyaruka/textit/issues/511868704/?query=is:unresolved

Fix plural tag count on flow list page

---

temba/locations/models.py
temba/locations/tests.py

* pass all `kwargs` to the base objects.create method

Fix Location geojson import

---

temba/contacts/views.py

Good to push if you are doing that anyways

dont eggbeater unless more than one egg broke

---

temba/channels/handlers.py
temba/channels/tests.py
temba/channels/types/junebug/type.py
temba/channels/types/junebug_ussd/type.py
temba/channels/urls.py
temba/ussd/tests.py

These are all remapped or forwarded now.. will merge once a day goes by with no new sentries.

Remove Twilio message handling now that it isn't called anymore

---

temba/contacts/views.py

Two things that make a big difference:
1. Use our trigger based counts on all groups to calculate pagination, not just system groups
2. Calculate test contacts and exclude them by id instead of doing a giant join

optimize group views

---

temba/flows/models.py
temba/flows/tests.py
temba/flows/views.py

allow reading, just not writing of sends with groups

Send to group redux

---

temba/contacts/management/commands/audit_es_group.py

Useful for the debuggings.. a unit test for this would really only be testing mocks..

add admin command to help audit ES and DB discrepencies

---

pip-freeze.txt
pip-requires.txt
temba/utils/goflow/tests.py
temba/utils/goflow/trial.py

added jsondiff which should give us some clue as to where the problem lies.

better output when blowing up due to goflow differences

---

temba/utils/goflow/serialize.py

https://sentry.io/nyaruka/textit/issues/542057502/

Always use channel.name for goflow channel assets

---

temba/contacts/tasks.py
temba/contacts/tests.py
temba/settings.py.dev
temba/settings_common.py

Just checks that we don't have contacts in the db that are 5 minutes newer than what we have in elasticsearch.

add canary task for elasticsearch

---

temba/flows/models.py

e.g. https://sentry.io/nyaruka/textit/issues/557142939/
this is a real JSON field so it can be null, string, whatever

Don't blow up when FlowRun.events is null

---

temba/flows/models.py

https://sentry.io/nyaruka/rapidpro/issues/558512513/

Don't blow up if msg event has uuid="None"

---

temba/contacts/tests.py
temba/flows/tests.py
temba/msgs/models.py
temba/msgs/tests.py

As they are only needed for purged broadcasts and we no longer purge broadcasts

Don't write broadcast recipients

---

temba/flows/management/commands/run_audit.py
temba/flows/management/commands/tests.py

Check for the dreaded `"None"`s

Rework run_audit command to check JSON fields and not worry about steps

---

temba/channels/types/facebook/tests.py
temba/channels/types/facebook/views.py
templates/channels/types/facebook/claim.haml

FIxes https://github.com/rapidpro/rapidpro/issues/753

Update Facebook claim to ask for Page ID and Page name from the user

---

temba/flows/models.py
temba/flows/tests.py

Fixes https://sentry.io/nyaruka/rapidpro/issues/563422218/

Handle when contact sends message, whilst also being started in a flow

---

temba/contacts/tests.py
temba/flows/tests.py
temba/msgs/tests.py
temba/settings_common.py

Re-enable consent

---

temba/campaigns/models.py
temba/orgs/tests.py

Fixes https://github.com/rapidpro/rapidpro/issues/755

Fix the campaign events fields to be datetime fields

---

static/coffee/temba.coffee
templates/frame.haml
templates/public/public_deploy.haml

Instead looks for presence of an intercom widget and falls back to invoking a mailto

Remove explicit use of uservoice

---

temba/api/v2/tests.py
temba/api/v2/views.py
temba/archives/models.py
temba/archives/views.py
templates/archives/archive_list.haml

- Use daily and monthly everywhere for api filters
- Fix queries and templates to match model changes for archive ui

Tweak archive

---

temba/contacts/models.py
temba/contacts/tests.py

- moves degrouping to be part of deactivate, adds test

Test degroup contacts on release

---

temba/urls.py

Fixes broken intercom widget for logged out users

Don't try to report details on logged out users

---

temba/channels/models.py
temba/channels/types/burstsms/type.py
temba/channels/views.py
templates/channels/channel_claim_form.haml

Tweaks to allow channel types to more easily customize the claim page.

Burst sms tweaks

---

temba/flows/models.py
temba/flows/tests.py
temba/flows/views.py

Exciting new feature for users - simpler flow result exports without the Contacts sheet or Groups column

Simpler result exports

---

temba/flows/views.py

Not sure what the right fix is, but this makes it work for now.

🔥 🔥 🔥 HOTFIX: Make flow updates work 🔥 🔥 🔥 

---

temba/flows/views.py

📅 Add option for two day expiration

---

temba/contacts/tests.py
temba/contacts/views.py

FIx https://sentry.io/nyaruka/rapidpro/issues/593529148/

❕ Fix supported scheme display lookup

---

temba/archives/models.py
temba/archives/tests.py
temba/archives/views.py
temba/contacts/tests.py
temba/contacts/views.py
temba/flows/views.py
temba/msgs/tests.py
temba/msgs/views.py
temba/orgs/models.py
temba/settings_common.py
temba/utils/management/commands/test_db.py
templates/archives/archive_message.haml
templates/archives/archive_run.haml
templates/contacts/contact_history.haml
templates/contacts/contact_read.haml
templates/flows/flow_results.haml
templates/flows/flow_run_table.haml
templates/msgs/message_box.haml
templates/smartmin/sidebar_pagination.haml

Adds messaging to the messages, runs, and contact history pages about archives if the org has deleted archives.

🗃️ Archive messaging

---

temba/channels/models.py
temba/channels/types/twilio/tests.py
temba/channels/types/twilio/type.py
temba/channels/views.py

See: https://sentry.io/nyaruka/textit/issues/593782600/

☎️ Don't fail twilio channel releases on auth failure

---

media/test_flows/send_msg_to_urnless.json
temba/flows/models.py
temba/flows/tests.py

Fixes https://sentry.io/nyaruka/textit/issues/595066726/

📇  Change VariableContactAction to create contacts even without URNs

---

temba/flows/server/tests.py
temba/flows/server/trial.py

Fixes flow server trials like https://sentry.io/nyaruka/rapidpro/issues/593031849/

💉 When comparing msg events in flowserver trials, make attachments relative again

---

temba/msgs/models.py
temba/utils/export.py

Addresses https://github.com/rapidpro/rapidpro/issues/766

🚤 Switch message export to use XLSLite

---

temba/api/v2/serializers.py
temba/api/v2/tests.py
temba/api/v2/views.py

Addresses https://github.com/rapidpro/rapidpro/issues/777

ℹ️ Add name and input to runs API v2 endpoint

---

static/coffee/flows/controllers.coffee

Addresses https://github.com/rapidpro/rapidpro/issues/779

📻 Allow Editor to support all the audio formats that we can play

---

.travis.yml
temba/flows/models.py
temba/flows/server/client.py
temba/flows/server/serialize.py
temba/flows/server/tests.py
temba/flows/server/trial.py
temba/flows/tests.py
temba/flows/views.py
temba/tests/base.py
temba/tests/http.py

* Expose resthook configs as assets
* Run trials against flows with resthooks

🤙 Add support for resthook rulesets in goflow

---

temba/api/v1/serializers.py
temba/api/v1/tests.py
temba/flows/models.py

Might fix the surveyor problems... also just adding more testing and reworking things to be easier to grok.

Allow surveyor submissions to match rules on old revisions

---

temba/contacts/omnibox.py
temba/contacts/tests.py
temba/tests/base.py

Fixes https://github.com/rapidpro/rapidpro/issues/781

🌬 Use ES when searching for contacts in Omnibox

---

temba/contacts/omnibox.py
temba/contacts/tests.py

This was caught by Sentry: https://sentry.io/nyaruka/textit/issues/625922640/events/

📳 Ignore SearchException in Omnibox

---

templates/channels/channelevent_calls.haml
templates/contacts/contact_list.haml
templates/msgs/message_box.haml

Fix https://sentry.io/nyaruka/textit/issues/621293111/

⁉️Fix count for blocktrans to not use string from intcomma

---

temba/flows/tests.py
temba/flows/views.py

Equivalent goflow change: https://github.com/nyaruka/goflow/pull/340

🍫 Wrap multiple asset responses in a results object

---

temba/archives/models.py
temba/orgs/models.py
temba/orgs/tests.py
temba/settings_common.py
temba/tests/s3.py

Takes care of dealing with extra S3 files existing and being properly cleaned up.

🗑Release org archives

---

.travis.yml
pip-freeze.txt
temba/ussd/models.py

3.6 is still the official / tested Python but handy to get things working on 3.7 since that's what you'll get if you do a `brew update`

🆕 Compatibility with Python 3.7

---

pip-freeze.txt
pip-requires.txt
temba/utils/twilio.py

Part 1 to update twilio, the next one will have more changes to support twilio library version 6

🔀 Update twilio to 5.7.0

---

temba/channels/tests.py
temba/ivr/tests.py
temba/orgs/models.py
temba/orgs/tests.py

Fix https://sentry.io/nyaruka/textit/issues/660600211/

🙃 Fix nexmo

---

temba/api/v2/tests.py
temba/contacts/models.py
temba/contacts/omnibox.py
temba/contacts/tests.py
temba/contacts/views.py

Fixes https://github.com/rapidpro/rapidpro/issues/786

🈁 Show preferred URN for a Contact in Omnibox

---

temba/orgs/tests.py
temba/orgs/views.py
temba/public/views.py
temba/utils/analytics.py
temba/utils/tests.py

https://sentry.io/nyaruka/textit/issues/563557980/

🧜 Fix intercom ResourceNotFound on Org.Signup

---

temba/orgs/tests.py
temba/orgs/views.py

Fixes https://sentry.io/nyaruka/textit/issues/664999073/

📌 Enforce validation on OrgSignup and OrgGrant forms

---

.travis.yml
temba/flows/server/serialize.py
temba/flows/tests.py

🌂 Migrate flows during flowserver trials with collapse_exits=false

---

temba/flows/models.py

In the old world, the input of a resthook ruleset can be multiple requests concatenated, but the logic is based on only one of the requests. In the new world the input is the same request used for the router logic. Feels like new engine behavior is preferable and it would be awkward to replicate old world behavior in the new engine as the router there is just looking at `@run.webhook` which is always a single request.

⌨️ Input for a webhook result test should be a single request

---

temba/flows/server/trial/campaigns.py

Sometimes campaign single message flows generate no events in the old world, if the contact has no sendable URN. Fixes https://sentry.io/nyaruka/rapidpro/issues/668639885

⚗️ Flowserver trial shouldn't blow up if run has no events

---

temba/api/v1/tests.py
temba/api/v1/views.py

Fixes https://github.com/rapidpro/rapidpro/issues/787

⚛️ Ensure API v1 writes are atomic

---

temba/flows/models.py

Don't zeropad contact ids here either

👪 Fix operands for group tests on anon orgs

---

temba/api/v2/serializers.py
temba/api/v2/tests.py
temba/campaigns/models.py
temba/contacts/models.py

* `set_fields` is used by:
*  API.v2.contactwriteserializer
* Contact.create_instance - for contact import
* we are not updating API.v1.contactwriteserializer, bacause it's hardly used

🖇 Add Contact.set_fields

---

temba/locations/views.py
temba/tests/base.py

this is the regex to parse new urls: https://regex101.com/r/VeoTGV/3/
```
4112412
R12321
VNM0
VNM.123
VNM.49_1
VNM.49.1_1
```

🧐 Update Location URLs to work with GADM IDs

---

temba/utils/management/commands/test_db.py

So that mailroom has some campaigns to test against.

Test db campaigns

---

temba/api/v2/serializers.py
temba/api/v2/tests.py

Fixes: https://sentry.io/nyaruka/textit/issues/685200956/

🗞 Raise ValidationError if flow.extra is not a valid JSON

---

temba/contacts/models.py
temba/contacts/tasks.py
temba/contacts/views.py

If it's possible to delete a group we first make it inactive, and then
release it in a background task.

⏿ Defer group.release in a background task

---

temba/campaigns/tasks.py
temba/channels/tasks.py
temba/channels/tests.py
temba/flows/models.py
temba/flows/tasks.py
temba/flows/tests.py
temba/ivr/tasks.py
temba/msgs/models.py
temba/msgs/tasks.py
temba/msgs/tests.py
temba/utils/queues.py

And use constants for queue names

⚡ Switch single contact flow starts to use the handler queue

---

temba/contacts/models.py

Fixes: https://github.com/rapidpro/rapidpro/issues/806

💹 Optimize group releases

---

.travis.yml
temba/flows/models.py
temba/flows/server/client.py
temba/flows/server/tests.py
temba/flows/server/trial/resumes.py
temba/flows/tests.py
temba/flows/views.py

Replaces caller events with a msg-type trigger and resumes

🚰 Latest goflow

---

.travis.yml
temba/contacts/tests.py
temba/flows/models.py
temba/flows/server/serialize.py
temba/flows/tests.py
temba/orgs/models.py
temba/orgs/tests.py

* Fixes quick reply localization using contact language which isn't valid org language
* Fixes category localization using contact language which isn't valid org language
* Update to latest goflow which requires extra language fields on environment

🈵 Language fixes and latest goflow

---

temba/campaigns/views.py
temba/flows/views.py

* Allow contact.created_on in flows
* Initialize to first date field when creating new events

🏑 Allow created_on

---

temba/utils/management/commands/test_db.py

* Ensure users have same username and email as they would in prod. Needed to login as from surveyor.
* Make password configurable

🤖 Test_db tweaks

---

temba/channels/types/viber_public/tests.py
temba/channels/types/viber_public/type.py

Courier has support already for VP attachments

🔛 Turn on the attachment support for VP channels

---

temba/api/v2/serializers.py
temba/api/v2/tests.py
temba/api/v2/views.py

Surveyor needs to fetch all non-archived surveyor flows

📝 Flows API endpoint should support filtering by is_archived and flow_type

---

templates/api/webhookevent_list.haml
templates/orgs/org_token.haml

Fix https://github.com/rapidpro/rapidpro/issues/820

📝  Move webhook docs button from the token view to the webhook view

---

temba/channels/types/whatsapp/type.py

🛑 Remove WA status endpoint

---

temba/api/v2/fields.py
temba/api/v2/serializers.py
temba/api/v2/tests.py

Fixes: https://sentry.io/nyaruka/textit/issues/770220071/

🔫 Raise ValidationError for ContactFields with nul chars

---

temba/campaigns/tests.py
temba/contacts/tests.py
temba/flows/models.py
temba/flows/server/client.py
temba/flows/server/serialize.py
temba/flows/server/tests.py
temba/flows/tests.py
temba/flows/views.py
temba/settings_common.py
temba/tests/base.py
temba/utils/http.py

For now only used for flow migration

🗑️ Remove flow server

---

static/coffee/flows/controllers.coffee
static/less/flow_editor.less
temba/settings_common.py
templates/flows/flow_editor.haml

Fix https://github.com/rapidpro/rapidpro/issues/838

👍Fix recent messages rollover with 0 messages

---

media/test_flows/migrate_to_11_0.json
temba/flows/flow_migrations.py
temba/flows/management/commands/migrate_flows.py
temba/flows/management/commands/tests.py
temba/flows/tests.py

Includes tweaks to `migrate_flows` command to make error reporting more useful

✈️ Flow migration fixes

---

media/test_flows/migrate_to_11_8.json
temba/flows/flow_migrations.py
temba/flows/models.py
temba/flows/tests.py

Addresses https://github.com/rapidpro/rapidpro/issues/844

👯 Fix duplicate rule UUIDs

---

temba/channels/tests.py
temba/ivr/tests.py
temba/orgs/models.py
temba/orgs/tests.py

Fixes https://sentry.io/nyaruka/textit/issues/844041841/events/42627932902/

⏭ Fix nexmo claim

---

temba/flows/migrations/0191_add_deps_for_start_new_flow_action.py

🔥 Fix for flow dependency migration

---

temba/flows/views.py
templates/flows/flow_results.haml

Use buttons on flow results to toggle all runs and responded runs

---

static/coffee/simulator.coffee
static/coffee/simulator_go.coffee
static/coffee/simulator_py.coffee
static/less/simulator.less
templates/flows/flow_editor.haml
templates/flows/simulator.haml

📞 IVR simulation in mailroom

---

static/coffee/simulator.coffee
static/coffee/simulator_go.coffee

Noticed this playing on staging

🔥 Fix quick replies in simulator

---

media/test_flows/migrate_to_11_10.json
static/coffee/flows/controllers.coffee
static/coffee/flows/widgets.coffee
temba/flows/flow_migrations.py
temba/flows/models.py
temba/flows/tests.py
templates/partials/action_editor.haml
templates/partials/split_editor.haml

Fixes https://github.com/rapidpro/rapidpro/issues/845

🌉 Only trigger-flow actions can cross flow modalities 

---

pip-freeze.txt
temba/mailroom/queue.py
temba/msgs/models.py
temba/msgs/tests.py
temba/tests/base.py
temba/utils/cache.py
temba/utils/queues.py
temba/utils/tests.py

```
git revert 25e50aff43d0b25511b42a8391e2f683c0d00feb
```
See https://github.com/celery/celery/issues/4495

🏃 Revert redis upgrade

---

temba/campaigns/tests.py
temba/campaigns/views.py

Fix https://github.com/rapidpro/rapidpro/issues/860

🖲Fix to prevent campaign event to create empty translations

---

temba/orgs/tests.py
temba/orgs/views.py

Addresses https://github.com/rapidpro/rapidpro/issues/850

📅 Default to month first date format for US timezones

---

temba/channels/tests.py
temba/channels/types/jiochat/tests.py
temba/channels/types/wechat/tests.py
temba/channels/views.py
temba/ivr/tests.py
templates/channels/channel_read.haml
templates/channels/channellog_connection.haml
templates/channels/channellog_list.haml
templates/channels/channellog_read.haml

Addresses https://github.com/rapidpro/rapidpro/issues/861

📝 Use URL kwargs for channel logs list to pass the channel uuid

---

temba/campaigns/tests.py
temba/campaigns/views.py
temba/orgs/views.py
templates/orgs/org_export.haml

Addresses https://github.com/rapidpro/rapidpro/issues/863 however we add the export to the campaign read page instead of the list page

📤Add export link on campaign read page

---

temba/contacts/migrations/0094_remove_test_contacts.py

Ran this on staging and it didn't delete to a cascading delete of the entire database so that's good.

🚁 Fix test contact deletion migration to honor db constraints

---

temba/api/v2/tests.py
temba/channels/tests.py
temba/contacts/models.py
temba/contacts/tests.py
temba/flows/tests.py
temba/msgs/models.py
temba/msgs/tests.py
temba/msgs/views.py
temba/orgs/tests.py

They are no longer created anywhere.. in tests or prod.

🧼 No more testing with test contacts

---

temba/api/tasks.py
temba/api/tests.py

pragma no cover strikes again!

🤕  add test for event retrying, fix out of date model

---

pip-freeze.txt

- boto3 - https://github.com/boto/boto3/blob/develop/CHANGELOG.rst
- Django - https://github.com/django/django/blob/master/docs/releases/2.1.6.txt
- twilio - https://github.com/twilio/twilio-python/releases/tag/6.24.0
- pip-tools - https://github.com/jazzband/pip-tools/releases
- psycopg2 - https://github.com/psycopg/psycopg2/releases
- flake8 - http://flake8.pycqa.org/en/latest/release-notes/
- smartmin - https://github.com/nyaruka/smartmin/blob/master/CHANGES.md
- stripe - https://github.com/stripe/stripe-python/blob/master/CHANGELOG.md

🥳 Update Python module dependencies

---

templates/contacts/contact_read.haml

Addresses https://app.intercom.io/a/apps/l6e7tr01/inbox/inbox/155964/conversations/20844347071

⌚️Use pretty datetime on contact page for upcoming events

---

temba/public/tests.py
temba/public/views.py

Fix the sample flow broken since the webhook always return invalid order ID

1️⃣Update status demo view to match the current webhook posted data

---

media/test_flows/parent_child_expiration.json
temba/orgs/models.py
temba/orgs/tests.py
temba/utils/management/commands/mailroom_db.py

turns out if you don't test it it's broken. :(
also sneaking a new test flow for mailroom

make sure we save flow_server_enabled in initialize

---

static/coffee/simulator_go.coffee

* shows both request and response in popup dialog
* include elapsed ms in log for webhook
* deal with attachments like `image:https://...`

simulator tweaks

---

static/coffee/simulator.coffee
static/coffee/simulator_go.coffee

* show entering and exiting sessions even across triggers
* echos quick replies and digit entries, this matches what contact page looks like
* never hides keyboard

improve simulator

---

media/test_flows/migrate_to_11_12_one_node.json
temba/flows/flow_migrations.py
temba/flows/models.py
temba/flows/tests.py

Fix https://sentry.io/organizations/nyaruka/issues/911679250/

⛓ Fix case of one node with invalid channel reference

---

temba/flows/models.py
temba/flows/tests.py

Adresses https://github.com/rapidpro/rapidpro/issues/879

📁 Fix flow export results to include results from replaced rulesets

---

temba/channels/models.py
temba/channels/tests.py
temba/channels/views.py

Proposition to address https://sentry.io/organizations/nyaruka/issues/796599792/

🗝 Ignore request from old android clients using GCM

---

static/examples/sample_flows.json
temba/api/v2/views_base.py
temba/channels/types/twitter_activity/views.py
temba/flows/models.py
temba/flows/tests.py
temba/flows/views.py
temba/mailroom/client.py
temba/orgs/models.py
temba/orgs/tests.py
temba/orgs/views.py
temba/utils/views.py

By making the org grant view non-atomic. Also in this PR we migrate the sample flows from v6 to the latest for good measure.

🚔 Re-enable flow validation via mailroom

---

temba/orgs/views.py

Fixes https://sentry.io/organizations/nyaruka/issues/945386070/?project=20737&referrer=alert_email&statsPeriod=14d

⚛️ CreateSubOrg needs to be non-atomic as well as it creates flows
