nyaruka/rapidpro

temba/flows/models.py, temba/flows/tests.py
How to reproduce the problem:
- choose a ContactField, that is not used in the Flow already, and
change the label of a ContactField (i.e. Age -> Oldness)
- update a flow and add an `Update a Contact` action that will save any
value to the ContactField with an updated label
These actions will change the label of the ContactField to the
capitalized field 'key', in this case (Oldness -> age -> Age).
The problem is fixed by updating how we detect which fields are new and
should be created.
=> 🎋 Prevent updates of ContactField labels when adding a field to a Flow

.travis.yml, pip-freeze.txt, pre-commit.sh, temba/channels/types/jiochat/tests.py, temba/contacts/search/gen/ContactQLLexer.py, temba/triggers/tests.py, temba/utils/gsm7.py
We are already running on Python36 so we should target it as a specific
version.
=> 🕹 Update black, set target-version=py36

do-freeze-python-deps.sh, pip-freeze.txt, temba/channels/types/__init__.py, temba/utils/__init__.py
Also updated few support modules, like coverage, isort, ...
=> 🥋 Update Django version to 2.1.8

temba/contacts/tests.py, temba/utils/views.py, templates/contacts/contact_list.haml
Fixes: https://github.com/rapidpro/rapidpro/issues/876
=> 🎏 Limit pagination on Contact.list to 10000 contacts

temba/api/v1/serializers.py, temba/api/v1/tests.py, temba/api/v1/views.py, temba/api/v2/serializers.py, temba/api/v2/views.py, temba/campaigns/models.py, temba/campaigns/tests.py, temba/contacts/models.py, temba/contacts/tests.py, temba/contacts/views.py, temba/flows/models.py, temba/flows/views.py, temba/orgs/models.py
Fixes: https://github.com/rapidpro/rapidpro/issues/916
=> 🏉 Honor is_active when creating contact fields

package.json, templates/flows/flow_editor_next.haml
* Update to latest flow editor
* Add endpoint for mailroom functions
* Fix styles for in page user selection
=> 🚢  Flow editor 1.4.18

temba/orgs/models.py, temba/orgs/tests.py, temba/orgs/views.py
Fixes: https://github.com/rapidpro/rapidpro/issues/615
=> 👘 Update invitation secret when user is re-invited

temba/channels/types/hormuud/__init__.py, temba/channels/types/hormuud/tests.py, temba/channels/types/hormuud/type.py, temba/settings_common.py
Our quest to support every aggregator and carrier on the planet continues.
=> add hormuud channel type

temba/channels/types/twiml_api/tests.py, temba/channels/types/twiml_api/views.py
Fixes: https://github.com/rapidpro/rapidpro/issues/933
=> 🙊 Don't update TwiML channel when claiming it

temba/orgs/models.py, temba/orgs/tests.py
Fixes: https://github.com/rapidpro/rapidpro/issues/930
=> 🦛 Use most recent topup for credit transfers between orgs

media/test_flows/goflow/favorites_v13.json, temba/api/v2/tests.py, temba/flows/models.py, temba/flows/tests.py
Just the export parts of #2397 so we can get Surveyor working with new flows
=> 📦 Export of new flows

temba/channels/views.py
Updated as seen on https://dashboard.nexmo.com/download_pricing OUTBOUND SMS
=> 🗺Update Nexmo supported countries list

temba/channels/types/clicksend/__init__.py, temba/channels/types/clicksend/type.py, temba/settings_common.py
At customer request.. .https://www.clicksend.com
=> ➕  adds ClickSend channel type

pip-freeze.txt
https://docs.djangoproject.com/en/dev/releases/2.1.9/
=> 🧚🏻‍♂️ Update Django to version 2.1.9

media/test_flows/cataclysm.json, temba/campaigns/models.py, temba/campaigns/tests.py, temba/contacts/models.py, temba/flows/models.py, temba/orgs/models.py, temba/orgs/tests.py, temba/triggers/models.py
And add `.as_export_ref()` to exportable classes
=> 🚍 Make exported fields match goflow representation 

package-lock.json, package.json
Latest flow editor in case somebody is pushing before I'm in tomorrow.
=> Update flow editor to 1.5.8

templates/msgs/msg_outbox.haml
fixes https://github.com/rapidpro/rapidpro/issues/942
=> add pagination to outbox

post-commit.sh, pre-commit.sh
Fixes: https://github.com/rapidpro/rapidpro/issues/938
=> 🦝 Only add initially changed files in post-commit hook

package-lock.json, package.json, temba/flows/views.py, templates/flows/flow_editor_next.haml
Adds flag to force a save on load. Also includes update to new flow editor version which honors that flag on its end.
Fixes: rapidpro/rapidpro#978
=> Force save on migrating flows

package-lock.json, package.json
Fix rendering on overview for flows with long names #666
Add support for create_contact on start session #662
Use flexbox for split by result delimited #663
Include wait for audio on IVR #664
=> Update editor to 1.6.3

package-lock.json, package.json
v1.6.5
Fix operand for field delimiter
v1.6.4
Allow text selection inside stickies
Add external_id to completion
Don't save empty quick reply lists on localization
Use alpha for text selection on stickies
=> Update to flow editor 1.6.5

.gitignore, pre-commit.sh
Fixes: https://github.com/rapidpro/rapidpro/issues/989
=> 🏳️‍🌈 Remove .commit file when flake8 command fails

media/test_flows/ivr_flow.json
This flow is used by mailroom for IVR tests.
=> Add trigger params access to IVR flow

package-lock.json, package.json
* Adds scrolling when there are too many rules
=> Flow Editor 1.6.9

package-lock.json, package.json
* Disable internal scrolling on rules dialog (fixes rule clipping)
=> Update to flow editor v1.6.11

.travis.yml
Only try to initialize postgresql database in Travis build if it doesn't exist
=> 😬 Yet another Travis tweak to fix database initialization

temba/airtime/models.py, temba/channels/models.py, temba/channels/tests.py, temba/channels/types/nexmo/views.py, temba/channels/types/twilio/tests.py, temba/channels/types/twilio/views.py, temba/channels/types/twilio_messaging_service/tests.py, temba/channels/types/twilio_messaging_service/views.py, temba/orgs/models.py, temba/orgs/tests.py, temba/orgs/views.py
Contains #2496 which should be merged first!
=> 🧹 Clean up constants on Org model

temba/channels/tests.py, temba/contacts/models.py, temba/contacts/tests.py, temba/flows/models.py, temba/flows/tests.py, temba/orgs/models.py
Not worth the complexity now that legacy engine isn't used
=> 🚶Ditch caching which was only added for legacy engine performance

temba/contacts/models.py
Ever merge a PR and then realise you had an unpushed commit?
=> 🔧 Limit group fetching to active groups

package-lock.json, package.json
* Show failures in simulator #695
* Remove screen bg on simulator #694
* Add location rules #693
* Fix results erroneously adding to store #692
* Fix operand for non-delimited run result split #691
* Add name to argument list of has_group test #690
=> Update floweditor to 1.6.12

temba/channels/tests.py, templates/channels/channellog_read.haml
Turns out this was broken fixing coverage.. oops :)
https://github.com/nyaruka/rapidpro/commit/d56b907c36c24c6707c738f1cba74fc09e381b99
=> 💥  fix ivr channel logs

temba/orgs/tests.py, templates/orgs/org_export.haml
=> 🤦‍♂️ Fix rendering of campaigns on export page

package-lock.json, package.json, templates/flows/flow_editor_next.haml
Use the displayed language when starting a simulation #721
Allow result type to trump type request #720
Tweak recipients endpoint to only include groups and contacts.
=> Fix for start_session action in the editor

temba/classifiers/models.py, temba/request_logs/models.py, temba/request_logs/tests.py, templates/request_logs/httplog_read.haml
Couple cleanup items:
* sync intents after the transaction is committed
* better (correct!) creation of request / response log
* better display of response log due to HAML template weirdness
=> 🛁  Classifier tweaks

locale/en_US/LC_MESSAGES/django.po, locale/es/LC_MESSAGES/django.po, locale/fr/LC_MESSAGES/django.po, locale/pt_BR/LC_MESSAGES/django.po, templates/flows/flow_filter.haml
Server side blows up if you try already so just preventing that path.
Fixes: https://github.com/rapidpro/rapidpro/issues/1044
=> 🛑  Don't allow deletion of labels with children

package-lock.json, package.json, temba/flows/tests.py, temba/flows/views.py, templates/flows/flow_editor_next.haml
Adds bits for using split by intents in the editor. Includes version 1.7.0 of the editor.
Update airtime node generation to use has_category test nyaruka/floweditor/pull/726
Split by intent nyaruka/floweditor/pull/724
Add feature filtering
=> ❇️ Add classifiers to editor

package-lock.json, package.json
v1.7.1
Default confidence to .9 when selecting an intent nyaruka/floweditor/pull/731
Better simulation for classification nyaruka/floweditor/pull/730
=> Update to flow editor v1.7.1

package-lock.json, package.json
Fix subflow filtering on enter a flow action nyaruka/floweditor/pull/733
=> Update to flow editor v1.7.2

package-lock.json, package.json
* Tweaks for airtime form and their simulation events
=> Update to flow editor version 1.7.3

static/js/schedules-ui.js, templates/triggers/trigger_schedule.haml
Fixes: https://github.com/rapidpro/rapidpro/issues/1069
=> Fix schedule ui datetime init on form validation failure 

temba/flows/models.py, temba/orgs/tests.py
wack-a-mole for missing releases. :)
=> release flow starts when releasing flows

package-lock.json, package.json
* Globals completion
* Render email_sent events in simulator
=> Update to floweditor v1.7.5

.travis.yml
As of 8cdb74f8778a6cbb394fc5a9c2fbd574a358a23d we don't seem to catch removals, only additions
=> 🔬 Fix checking for locale changes on Travis

package-lock.json, package.json
* Tweak css for split by contact field (766)
* Allow messages with only spaces (765)
* Disambiguate simulator email i18n key (764)
=> Update to flow editor v1.7.7

temba/mailroom/client.py, temba/mailroom/tests.py
Pass version to mailroom migrate endpoint
=> ⚙️ Flow migrations part 1

package-lock.json, package.json
=> Update to floweditor 1.7.9

templates/contacts/contact_list.haml
Missed this icon when converting sending over to components.
=> Add sending back to contact list page

temba/classifiers/types/bothub/__init__.py, temba/classifiers/types/bothub/tests.py, temba/classifiers/types/bothub/type.py, temba/classifiers/types/bothub/views.py, temba/settings_common.py
This pr is to fix the Bothub classifier name.
=> Change name BotHub to Bothub

package-lock.json, package.json
* Subflow parameters
* Better webhook header defaults
=> 📋 Subflow parameters

temba/channels/models.py, temba/channels/tests.py
`check_alerts` could certainly use a thorough run through and reconsideration, but this solves the glaring problem of us browning ourselves out checking alerts on channels that haven't sent in a long time.
=> fix query explosion on alerts

templates/api/v2/api_explorer.haml
Fixes https://github.com/rapidpro/rapidpro/issues/1129
=> 👗 Remove syntax highlighting in API explorer as it can't handle big responses

temba/api/support.py, temba/api/v2/tests.py, temba/settings_common.py
Fixes https://github.com/rapidpro/rapidpro/issues/1142
=> 🦅 Do not subject requests to the API with sessions to rate limiting

templates/flows/flow_export_results.haml
Currently we export all runs for each contacts
=> Update message on the flow results export to be clear

templates/contacts/contactgroup_delete.haml
Fixes https://github.com/rapidpro/rapidpro/issues/1151
=> Fix delete contact group modal buttons when blocked by dependencies

static/less/legacy.less, templates/contacts/contact_list.haml, templates/msgs/message_box.haml
Fixes https://github.com/rapidpro/rapidpro/issues/1150
=> Fix text positioning on list pages

package-lock.json, package.json
This includes a small change under the hood to allow for shipping changes to the revisions endpoint (to include metadata/dependencies). This version of the editor can work with both styles of endpoint.
Also includes updated package.json to remove vulnerabilities.
=> Update to flow editor 1.7.15

temba/channels/models.py
Currently throwing a \[harmless\] error from celery: https://sentry.io/organizations/nyaruka/issues/1516680646/?project=227973&referrer=alert_email
=> 📱 Avoid error in creation of Android channels

temba/api/v2/serializers.py, temba/api/v2/tests.py, temba/api/v2/views.py
Addresses https://github.com/rapidpro/rapidpro/issues/1148
=> Add params to flow starts API

package-lock.json, package.json
=> Fix quick replies localization bug

templates/flows/flow_results.haml
Fixes https://github.com/rapidpro/rapidpro/issues/1121
=> Increase the max height on the flow results export modal dialog

package-lock.json, package.json, temba/flows/legacy/tests.py, temba/flows/models.py, temba/flows/views.py
Fixes: https://github.com/rapidpro/rapidpro/issues/1089
=> Softer dependencies in flow editor

temba/contacts/models.py, temba/contacts/tasks.py, temba/contacts/tests.py, temba/flows/models.py, temba/flows/tests.py, temba/msgs/models.py, temba/msgs/tests.py, temba/orgs/tasks.py, temba/orgs/tests.py, temba/settings_common.py
Also addresses https://github.com/rapidpro/rapidpro/issues/907
=> Task resume after deploy

package-lock.json, package.json, templates/flows/flow_editor_next.haml
* Static mapping for help links
* Arrow recalc bug on moving connections
* Timeout alignment
* Issues PopTab
* z-index on connection hover
* Fix MountScroll pulse, z-index
=> Update floweditor to v1.8.5

temba/channels/models.py, temba/channels/tests.py
Fixes https://github.com/rapidpro/rapidpro/issues/1093
=> Keep latest sync event for each channel when trimming

package-lock.json, package.json
* Addresses various z-index issues with connections vs. nodes
=> Update flow editor to 1.8.7

temba/api/v2/fields.py, temba/api/v2/tests.py
Fixes https://sentry.io/organizations/nyaruka/issues/1547441848/?project=20737&referrer=alert_email
=> 🧯 Fix API exception in when contact reference is a JSON number

package-lock.json, package.json
More z-index tweaks for 5.4 release.
=> Update to flow-editor 1.8.8

temba/flows/models.py, temba/flows/tests.py, temba/tests/engine.py
This includes attachments on the messages sheets in flow results exports
=> Export message attachment in flow results exports

package-lock.json, package.json
* fix for like-named category breakout
=> Update to floweditor 1.8.9

locale/en_US/LC_MESSAGES/django.po, locale/es/LC_MESSAGES/django.po, locale/fr/LC_MESSAGES/django.po, locale/pt_BR/LC_MESSAGES/django.po, temba/contacts/tests.py, temba/contacts/views.py, temba/tests/crudl.py, templates/contacts/contactfield_list.haml
Fixes https://github.com/rapidpro/rapidpro/issues/1133
=> ⚠️ Show warnings on contact field page when org is approaching / has hit the limit

static/js/temba.js, templates/msgs/msg_send_modal.haml
=> Fix open modal check on pjax refersh

templates/flows/flow_editor_next.haml
Stop-gap (?) to have the simulator fit on more screens.
=> Bump up the simulator when popped

package-lock.json, package.json, templates/flows/flow_editor_next.haml
* Render contact field clearing events in simulator
* Translation PopTab
* More i18n keys
=> Update to flow-editor 1.9.2

temba/api/v2/serializers.py, temba/api/v2/tests.py
Fixes https://sentry.io/organizations/nyaruka/issues/1632972355/?project=20737&referrer=alert_email
=> 🕯️ Don't blow up if someone calls contact_action endpoint with zero contacts

templates/contacts/contact_customize.haml
=> Do not use font checkboxes for contact import extra fields

templates/channels/channel_read.haml
This fixes the chart on the channel read page
=> Fix parentheses

temba/orgs/models.py, temba/orgs/tests.py, temba/settings_common.py
Can have Stripe do it instead if desired.
=> Make sending of receipts optional

temba/tickets/types/mailgun/tests.py, temba/tickets/types/mailgun/type.py, temba/tickets/types/mailgun/views.py, temba/utils/management/commands/mailroom_db.py
To later use in emails from mailroom
=> 🎟️ Store brand name in mailgun ticketer config 

package-lock.json, package.json, templates/frame.haml
Also adds some other styling options for Select and Button components
=> Fix webcomponent textarea styling for new Chrome

locale/en_US/LC_MESSAGES/django.po, locale/es/LC_MESSAGES/django.po, locale/fr/LC_MESSAGES/django.po, locale/pt_BR/LC_MESSAGES/django.po, locale/ru/LC_MESSAGES/django.po, temba/orgs/views.py, templates/campaigns/campaign_list.haml, templates/campaigns/campaign_read.haml, templates/campaigns/campaignevent_read.haml, templates/flows/flow_editor.haml, templates/flows/flow_editor_next.haml, templates/orgs/org_sub_orgs.haml
Fixes https://github.com/rapidpro/rapidpro/issues/1256
=> Fix failing to manage logins when the we are logged in the same org

templates/frame.haml, templates/includes/nav.haml
Allow nav to be configurable using css properties
=> Add variables for nav colors

temba/msgs/management/commands/msg_console.py
e.g. campaign event messages etc
=> 🕹️ Tweak msg_console so it can include sent messages which are not replies

templates/contacts/contactfield_list.haml
replace https://github.com/nyaruka/rapidpro/pull/2937
=> Add featured label below name and key on fields list

package-lock.json, package.json
=> Modal max-height in vh to not obscure buttons

temba/channels/views.py, templates/channels/channel_read.haml
Tiny change to channel read page, customer feedback
=> Show address when it doesn't match channel name

temba/contacts/views.py, temba/flows/views.py, templates/contacts/contact_list.haml, templates/flows/flow_results.haml
Handful of user feedback issues with contacts / fields
* Add search to contact fields on export results
* Add search to contact fields on edit custom fields
* Fix listeners after group modification on contact list
* Add alpha sort and search for result names on runs tab
=> Small ui issues

locale/en_US/LC_MESSAGES/django.po, locale/es/LC_MESSAGES/django.po, locale/fr/LC_MESSAGES/django.po, locale/pt_BR/LC_MESSAGES/django.po, locale/ru/LC_MESSAGES/django.po, temba/contacts/views.py, templates/contacts/contact_import.haml
=> Adjust styling for contact import scenarios

temba/flows/views.py, templates/flows/flow_export_results.haml, templates/includes/modax.haml
From user feedback:
* Show global form errors on modax template
* Show pre-form on modax template
* Alpha sort field selection on export results
* Remove some select2 cruft for export dialog
=> Export results fixes

templates/channels/types/external/config.haml
Drive-by while I was in there, just tightened everything up and took care of wrapping which wasn't taking place.
=> tweak external styling

temba/api/v2/views.py
Addresses https://github.com/rapidpro/rapidpro/issues/1352
=> 📗 Use v13 flow as example on definitions endpoint docs

temba/contacts/models.py, temba/contacts/tests.py
The preview parsing read was working (and tested with CSVs), but not the read that builds batches
=> 🧯 Fix contact imports from CSV files

package-lock.json, package.json
* Update to floweditor 1.10.1 (split by field fix)
* Update to components 0.6.1 (alignment fix for initiated searchable select)
=> Fix split by field

package-lock.json, package.json
- fetch all for searchable with local search (missing group issue)
- fix issue with cache misses
- add pdf option for attachment urls
- simulator rendering for pdfs
- fix issue with result router selection not showing (asset type with no endpoint)
- fix clear value sorting
=> temba-select local searching fixes, add pdf urls to floweditor

temba/msgs/tasks.py, temba/msgs/tests.py
i.e. avoid https://sentry.io/organizations/nyaruka/issues/1940186558/?project=20737&referrer=alert_email
=> 📩 Don't actually create a broadcast if sending to node but nobody is there

temba/campaigns/models.py, temba/campaigns/tests.py, temba/contacts/models.py, temba/contacts/tests.py, temba/tests/base.py, temba/tests/mailroom.py
Remove code for dynamic group reevaluation and campaign event scheduling
=> 🧼 Great delete part 1 (campaigns)

temba/flows/legacy/migrations.py, temba/flows/legacy/tests.py
https://sentry.io/organizations/nyaruka/issues/1961209861/?project=20737&referrer=alert_email
=> Fix 11.4 flow migration when given broken send action

static/js/temba.js, templates/campaigns/campaign_list.haml, templates/contacts/contact_list.haml, templates/flows/flow_list.haml, templates/globals/global_list.haml
Viewers should be able to view flows, contacts and campaigns.
=> fix viewer selection

locale/en_US/LC_MESSAGES/django.po, locale/es/LC_MESSAGES/django.po, locale/fr/LC_MESSAGES/django.po, locale/pt_BR/LC_MESSAGES/django.po, locale/ru/LC_MESSAGES/django.po, templates/api/v2/api_explorer.haml
Fixes https://github.com/rapidpro/rapidpro/issues/1353
=> Adjust styles for the API explorer page

locale/en_US/LC_MESSAGES/django.po, locale/es/LC_MESSAGES/django.po, locale/fr/LC_MESSAGES/django.po, locale/pt_BR/LC_MESSAGES/django.po, locale/ru/LC_MESSAGES/django.po, templates/contacts/contact_read.haml
Fixes https://github.com/rapidpro/rapidpro/issues/1366
=> Show contact last seen on on contact read page

static/rest_framework/css/prettify.css
Fixes https://github.com/rapidpro/rapidpro/issues/1363
=> Adjust prettify colors

.github/workflows/ci.yml, temba/contacts/tests.py, temba/contacts/views.py, temba/mailroom/client.py, temba/tests/base.py, temba/tests/mailroom.py, templates/contacts/contact_list.haml
=> List contacts sort last seen on

temba/channels/types/twilio/tests.py, temba/channels/types/twilio/views.py, temba/channels/types/twilio_messaging_service/tests.py, temba/channels/types/twilio_messaging_service/views.py, temba/channels/types/twilio_whatsapp/tests.py, temba/channels/types/twilio_whatsapp/views.py, temba/orgs/tests.py, temba/orgs/views.py
Fixes https://github.com/rapidpro/rapidpro/issues/1351
=> Adjust Twilio connect to redirect properly to the original claim page

locale/en_US/LC_MESSAGES/django.po, locale/es/LC_MESSAGES/django.po, locale/fr/LC_MESSAGES/django.po, locale/pt_BR/LC_MESSAGES/django.po, locale/ru/LC_MESSAGES/django.po, temba/channels/types/rocketchat/__init__.py, temba/channels/types/rocketchat/client.py, temba/channels/types/rocketchat/tests.py, temba/channels/types/rocketchat/type.py, temba/channels/types/rocketchat/views.py, temba/contacts/models.py, temba/contacts/tests.py, temba/settings_common.py, templates/channels/types/rocketchat/claim.haml
https://github.com/nyaruka/rapidpro/pull/3040 with 
* the locale conflicts fixed (again)
* unit tests fixed
* channel type limited to beta users for now
=> Rocketchat

static/css/tailwind.css, static/scss/tailwind.scss, templates/flows/flow_list.haml, templates/msgs/message_box.haml
Related to rapidpro/rapidpro/issues/1364
=> Style fixes

package-lock.json, package.json, templates/triggers/trigger_update.haml
* Don't duplicate form errors
* Use updated temba-components where omnibox properly passes error list down
Fixes: rapidpro/rapidpro/issues/1372
=> Fix validation issues on trigger update form

package-lock.json, package.json
* Force recipient search do be done remotely for SendBroadcast / StartSession
=> Editor fixes

temba/contacts/models.py, temba/contacts/tests.py
To be a bit more efficient and so tests don't break every time we add new URN schemes
Addresses https://github.com/rapidpro/rapidpro/issues/1373
=> 📦 Improve calculating of URN columns for exports 

temba/globals/models.py, temba/globals/tests.py
Fixes https://github.com/rapidpro/rapidpro/issues/1321
=> 🌐 Allow underscores in global names

templates/flows/flow_editor.haml
Fixes issue with flashing language dialog text on load
=> Hide language dialog blurb until needed

package-lock.json, package.json
Also re-introduces fix for double loading race.
=> Fix intent selection on split by intent

templates/contacts/contact_history.haml, templates/flows/flow_run_table.haml, templates/globals/global_list.haml
* Share modals on globals list, truncate values 
* Truncate values so page doesn't break with _very_ large values 
* Tiny whitespace fix for archive notice on contacts and flows
=> Performance fix for globals UI (resist)

temba/flows/tasks.py, temba/flows/tests.py
Updates on large numbers of rows on an open query are no bueno!
=> Fix trim lock

static/css/tailwind.css, static/scss/tailwind.scss, templates/contacts/contact_list.haml, templates/globals/global_list.haml
Also sneaks in a couple little style things:
* Add block for Create Global button
* Add will-change property to lifted buttons so Chrome doesn't render goofy animation
=> Inner scroll for contact list

static/js/labels.js
* Wire table listeners on pjax reload
=> Fix table links after using Remove from Group action button

temba/flows/models.py, temba/flows/tests.py, temba/globals/models.py, temba/globals/tests.py
https://app.intercom.com/a/apps/l6e7tr01/inbox/inbox/155936/conversations/20798300029295
=> 🙅🏽‍♂️ Fix deleted flow dependency preventing global deletion

temba/orgs/tests.py, temba/orgs/views.py
Just noticed this testing on staging where I was actually testing accepting invitations 🤦
=> 💌 Don't show accepted invitations in admin UI

temba/flows/models.py, templates/flows/flow_editor.haml
Goes with editor change in https://github.com/nyaruka/floweditor/pull/942
=> 🎨 Simplify passing of flow type to editor

temba/channels/types/android/tests.py, temba/channels/types/dialog360/views.py, temba/channels/types/whatsapp/views.py, temba/contacts/models.py, temba/contacts/tests.py, temba/utils/urns/tests.py, temba/utils/urns/urns.py
Fixing how we currently accept local US numbers
=> ☎️ Update tel parsing to match gocommon

temba/settings_common.py
https://github.com/rapidpro/rapidpro/issues/1345
=> set global email timeout, fixes rapidpro #1345

locale/en_US/LC_MESSAGES/django.po, locale/es/LC_MESSAGES/django.po, locale/fr/LC_MESSAGES/django.po, locale/pt_BR/LC_MESSAGES/django.po, locale/ru/LC_MESSAGES/django.po, templates/includes/pagination.haml, templates/includes/results_count.haml
Fixes https://github.com/rapidpro/rapidpro/issues/1415
=> Fix contact list pagination with searches

temba/orgs/views.py
Don't see a downside to allowing this, does anybody else?
=> 🧑‍💼Allow staff to use the org chooser

templates/flows/flow_editor.haml, templates/frame.haml
Will require changes on editor side too...
=> 🌐 Configure editor and components to use completions files in current language

.github/workflows/ci.yml, pip-freeze.txt
See https://stackoverflow.com/questions/62981104/attributeerror-httpheaderdict-object-has-no-attribute-get-all-while-mapping
=> Upgrade urllib3 to fix ES

temba/contacts/models.py, temba/contacts/tests.py, temba/contacts/views.py, temba/flows/models.py, temba/mailroom/events.py, temba/mailroom/tests.py, temba/utils/templatetags/temba.py, templates/contacts/contact_history.haml
`Contact.get_history()` returns a list of objects and in the view we render these as events. Those are then rendered in a template or returned as JSON.
=> 📜 History as events part 3

temba/orgs/tests.py, temba/orgs/views.py
Re-uses Smartmin's `FailedLogin` functionality
=> 🔐 Limit attempts at 2FA backup token entry

locale/en_US/LC_MESSAGES/django.po, locale/es/LC_MESSAGES/django.po, locale/fr/LC_MESSAGES/django.po, locale/pt_BR/LC_MESSAGES/django.po, locale/ru/LC_MESSAGES/django.po, temba/orgs/tests.py, temba/orgs/views.py
Fix https://github.com/rapidpro/rapidpro/issues/1438
=> Do not allow duplicates invites

templates/contacts/contactfield_list.haml
=> Fix styles on fields list

temba/flows/tests.py, temba/flows/views.py, temba/tests/engine.py
Fixes https://sentry.io/organizations/nyaruka/issues/2280790567/
=> Fix broken flow results charts

temba/channels/types/whatsapp/tests.py, temba/channels/types/whatsapp/type.py
=> Revert - "Update to use latest API version to get WA templates"

poetry.lock
`poetry install` currently complains about the lock file being out of sync which I think I caused yesterday updating DRF whilst having my old pip-based env active. This just runs `poetry update` to fix it which results in a few patch upgrades.
=> Fix lock file being out of sync with pyproject

temba/channels/models.py, temba/channels/tasks.py, temba/channels/tests.py, temba/contacts/views.py, temba/flows/models.py, temba/flows/views.py, temba/msgs/tasks.py, temba/msgs/views.py, temba/orgs/views.py, temba/triggers/views.py, temba/utils/analytics.py, temba/utils/export.py, temba/utils/tests.py
Fixes https://sentry.io/organizations/nyaruka/issues/1532503323
=> ignore anon user in analytics

temba/contacts/views.py
Fixes: https://github.com/nyaruka/temba-components/issues/64
(issue opened on wrong repo, but can't transfer here)
=> Make groups searchable on contact update page

temba/contacts/models.py, temba/orgs/tests.py
=> Release contact imports when releasing groups

temba/flows/tests.py, temba/mailroom/client.py
The problem arises when we load json with our custom decoder (which loads decimals) but serialize with the regular encoder which doesn't understand decimals.
Fixes https://sentry.io/organizations/nyaruka/issues/2358597920/?environment=production&project=20737&referrer=alert_email
=> 🧯 Fix serializing JSON to send to mailroom when it includes decimals

temba/contacts/models.py, temba/orgs/tests.py
Fixes: https://sentry.io/organizations/nyaruka/issues/2363824764/?environment=production&project=20737&referrer=alert_email
=> release import batches when releasing contact imports

temba/orgs/tasks.py, temba/orgs/tests.py, temba/settings_common.py
Releases orgs every night that have been inactive for over 7 days.
=> Release org task

temba/msgs/tests.py, temba/msgs/views.py, templates/contacts/contact_history.haml, templates/msgs/message_box.haml, templates/msgs/msg_outbox.haml
=> 🔧 Fix channel log icons and disallow message resending for suspended orgs

locale/en_US/LC_MESSAGES/django.po, locale/es/LC_MESSAGES/django.po, locale/fr/LC_MESSAGES/django.po, locale/pt_BR/LC_MESSAGES/django.po, locale/ru/LC_MESSAGES/django.po, temba/settings_common.py, temba/triggers/models.py, temba/triggers/tests.py, temba/triggers/views.py, templates/triggers/trigger_list.haml
Contains #3328 which needs to be merged first to make the diff readable
=> 🔫 Triggers by type

templates/msgs/msg_outbox.haml
=> Fix rendering of recipient buttons on outbox

temba/campaigns/tests.py, temba/campaigns/views.py
Like removing your primary language and having translation languages but no primary language
=> Cleanup campaign event CRUDL tests so they don't test behaviour we don't support

locale/en_US/LC_MESSAGES/django.po, locale/es/LC_MESSAGES/django.po, locale/fr/LC_MESSAGES/django.po, locale/pt_BR/LC_MESSAGES/django.po, locale/ru/LC_MESSAGES/django.po, temba/mailroom/events.py, temba/mailroom/tests.py, templates/triggers/trigger_list.haml
* Fixes conversion of ticket events to JSON
* Fixes rendering of closed ticket triggers on trigger list page
=> 🎟️ Ticket fixes

temba/api/v2/serializers.py, temba/api/v2/tests.py
Need mailroom to do these ticket modifications so that events are created and handled correctly.
=> 🚒 Fix closing and reopening of tickets from API

package-lock.json, package.json, templates/tickets/ticket_list.haml
* Reopen now toggles to open filter and focuses reopened ticket
* Handle ticket reopened events
* Fix scroll to bottom on initial load
* Fix scroll to bottom on new message
* Add new message toast when not scrolled near bottom
* Fix margin issues with sticky bin
https://user-images.githubusercontent.com/211652/122457153-343c2180-cf63-11eb-8fd5-4dae61a4685d.mp4
=> Handle reopen events for tickets

static/js/formax.js, templates/smartmin/base.html
Reverts the formData change in https://github.com/nyaruka/rapidpro/pull/3377
=> 🧯 Revert recent formax changes

temba/contacts/models.py, temba/contacts/tests.py, temba/contacts/views.py, temba/tests/base.py
So that you only see things like notes that belong to the ticket you're viewing
=> 🎟️ Optionally filter ticket events by ticket in contact history view

locale/en_US/LC_MESSAGES/django.po, locale/es/LC_MESSAGES/django.po, locale/fr/LC_MESSAGES/django.po, locale/pt_BR/LC_MESSAGES/django.po, locale/ru/LC_MESSAGES/django.po, temba/formax.py, temba/orgs/views.py, temba/settings_common.py, temba/tickets/tests.py, temba/tickets/views.py, templates/tickets/ticketer_read.haml
=> 🧑‍💼 Ticketer management from org home

temba/api/v2/views.py
to mention attachments rather than the deprecated media field
=> Fix API docs for messages endpoint 

temba/orgs/views.py
Broken with https://github.com/nyaruka/rapidpro/blob/main/temba/orgs/models.py#L2012
=> Fix to display email on manage orgs

temba/tickets/models.py, temba/tickets/views.py, templates/tickets/ticket_list.haml
At some point soon we're going to need counts beside those nice ticket folder names so this is just a little reorganization to make that easier, following something similar to `SystemLabel` so folders are a thing on the model side of things. Next step would be adding a squashable `TicketFolderCount`.
=> 🧰 Add `TicketFolder` class

temba/orgs/models.py, temba/orgs/tests.py, temba/orgs/views.py, temba/settings_common.py, temba/tickets/models.py, temba/tickets/tests.py, temba/tickets/views.py
Currently it's just admins + agents but seems like editors should be able to too
=> 👮 Control which users can have tickets assigned to them with a permission

package-lock.json, package.json, static/css/temba-components.css
* Update components to version with more form parameters
* Tweak appearance to be bigger and darker
=> Bigger, darker form bits

package-lock.json, package.json
=> Update flow editor

temba/msgs/tests.py, temba/msgs/views.py
Realized working on #3429 that the Sent view isn't even tested...
=> Cleanup Msg CRUDL tests

temba/flows/views.py, temba/ivr/models.py
Request from user. Requires https://github.com/nyaruka/mailroom/pull/462
=> 🛑 Add option to not retry IVR calls

temba/msgs/views.py, temba/settings_common.py, templates/orgs/dependency_usages_modal.haml
=> ✅ Add usages modal for labels as well

temba/tickets/tests.py, temba/tickets/views.py
@ericnewcomer  note the weird dates by the contacts above - I think that's because these contacts don't have a `last_seen_on` - but that value should be the ticket `last_activity_on`
=> 🧛 Show counts of open tickets

temba/channels/tests.py, temba/classifiers/tests.py, temba/contacts/models.py, temba/contacts/tests.py, temba/globals/tests.py, temba/msgs/tests.py, temba/orgs/models.py, temba/orgs/views.py, temba/tickets/tests.py, templates/includes/dependents.haml, templates/orgs/dependency_delete_modal.haml
Turns campaign event > field into a soft dependency same as flow > field
=> 🌸 Allow deletion of fields used by campaign events

temba/contacts/models.py, temba/contacts/search/mailroom.py, temba/mailroom/client.py, temba/mailroom/tests.py, temba/tests/mailroom.py
Requires https://github.com/nyaruka/mailroom/pull/468
=> ⚛️ Fix importing of dynamic groups when field doesn't exist

temba/flows/views.py
=> ⚠️ Add warning to flow start modal that options have changed

temba/flows/tests.py, temba/flows/views.py
=> Tweak error message on flow start modal now field component is fixed

temba/classifiers/types/luis/client.py, temba/classifiers/types/luis/tests.py, temba/classifiers/types/luis/type.py, temba/classifiers/types/luis/views.py, temba/request_logs/models.py
Microsoft have made it impressively complicated now to setup prediction with LUIS, requiring separate endpoints/keys for the authoring vs the prediction part.
before
after
=> 🗣️ Update and fix LUIS classifiers

static/css/tailwind.css, static/scss/tailwind.scss, templates/contacts/contact_read.haml
=> 🎨 Fix system group labels on contact read page

temba/api/v2/serializers.py, temba/api/v2/tests.py, temba/api/v2/urls.py, temba/api/v2/views.py, temba/api/v2/views_base.py
Step 1 of making users an editor asset type so that the open ticket action can take assignee. For now just listing accounts in the workspace.
=> 👥 Users API endpoint

templates/contacts/contact_update.haml
=> 🖌️ Fix error on contact update modal

temba/channels/views.py
best to be added after DB index in #3479 is built
=> Add button to see channel error logs

temba/channels/views.py, temba/contacts/views.py, temba/orgs/models.py, temba/orgs/tests.py, temba/utils/templatetags/temba.py, temba/utils/tests.py, templates/channels/channellog_connection.haml, templates/channels/channellog_list.haml, templates/channels/channellog_log.haml, templates/channels/channellog_read.haml
* Use same date formatting as rest of app - except with seconds added
* Show `error_reason` if set for errored/failed connections
* Fix missing gear button for calls
=> 🎨 Improve channel log views

temba/channels/models.py, temba/channels/tests.py, temba/channels/views.py, temba/contacts/tests.py, temba/mailroom/events.py, temba/mailroom/tests.py, temba/utils/templatetags/temba.py, templates/channels/channellog_calls.haml, templates/channels/channellog_connection.haml, templates/channels/channellog_list.haml
=> 📒 Improve display of channels logs for calls

temba/contacts/models.py, temba/contacts/tests.py, temba/orgs/models.py, temba/orgs/tests.py
Now that they have associated logs and notifications
=> 🗑️ Fix deletion of imports and exports

package-lock.json, package.json
* Fix overzealous list refresh
* Fix non-breaking ticket summary
* Fix display name when created_by is null
=> Update to latest components

package-lock.json, package.json, templates/flows/flow_editor.haml, templates/tickets/ticket_list.haml
Fixes: https://github.com/rapidpro/rapidpro/issues/1557
=> Add users and topics to flow editor

temba/api/v2/tests.py, temba/api/v2/views.py, temba/api/v2/views_base.py, temba/tests/base.py
=> More use of readonly database connection in API

temba/channels/types/whatsapp/type.py
Replace https://github.com/nyaruka/rapidpro/pull/3551
=> Fix WA check health logs

package-lock.json, package.json, temba/tickets/tests.py, temba/tickets/views.py
=> Add media to ticket history

temba/archives/management/commands/search_archives.py, temba/archives/management/commands/tests.py, temba/archives/models.py, temba/archives/tests.py, temba/flows/models.py, temba/msgs/tests.py, temba/tests/s3.py, temba/utils/s3/__init__.py, temba/utils/s3/select.py, temba/utils/s3/tests.py
Once it we're sure this works, can also use for message and contact exports
=> Use S3 Select for flow result exports

package-lock.json, package.json, static/css/tailwind.css, static/css/temba-components.css, static/scss/tailwind.scss, temba/contacts/views.py, temba/tickets/views.py, templates/contacts/contact_list.haml, templates/contacts/contact_read.haml, templates/contacts/contact_update.haml, templates/contacts/contact_update_fields.haml, templates/contacts/contact_update_fields_input.haml, templates/frame.haml, templates/spa_frame.haml, templates/spa_page_menu.haml, templates/tickets/ticket_list.haml
* Updates latest temba-components
=> Add contact read page based on contact chat component

templates/msgs/broadcast_schedule_list.haml, templates/msgs/msg_outbox.haml, templates/msgs/msg_outbox_spa.haml
paginator block should not be indented in the message list block
=> Fix outbox pagination

temba/contacts/tests.py, temba/contacts/views.py, templates/contacts/contact_archived.haml, templates/contacts/contact_blocked.haml, templates/contacts/contact_list.haml, templates/contacts/contact_stopped.haml, templates/contacts/contact_stopped_spa.haml
* Add description for stopped and blocked lists
=> Fix contact stop list

templates/frame.haml
=> Add privacy policy link

temba/notifications/models.py, temba/notifications/tasks.py, templates/notifications/email/base.html, templates/notifications/email/base.txt, templates/notifications/email/export_finished.contact.html, templates/notifications/email/export_finished.contact.txt, templates/notifications/email/export_finished.message.html, templates/notifications/email/export_finished.message.txt, templates/notifications/email/export_finished.results.html, templates/notifications/email/export_finished.results.txt
=> 📧 Use branded templates for export emails

temba/channels/models.py, temba/notifications/models.py, temba/utils/email.py, templates/email_base.html, templates/notifications/email/base.html, templates/notifications/email/base.txt
Fixes https://sentry.io/organizations/nyaruka/issues/2809591502/?environment=production&project=20737&referrer=alert_email
=> Fix email template for password forgets

temba/request_logs/models.py, templates/request_logs/httplog_read.haml, templates/request_logs/httplog_webhooks.haml
=> Render webhook calls which are too slow as errors

templates/flows/flowstart_list.haml
=> Fix wrap for recipients

static/css/tailwind.css, static/scss/tailwind.scss, templates/channels/channel_read.haml
* Allow `.card` to shrink as needed
* Add explicit `.flex-shrink-0` on channel chart card
=> Fix welcome page widths

templates/flows/flow_export_results.haml, templates/flows/flow_results.haml
Tho keep change to remove "include messages" option
=> ⏪ Revert change to hide non-responded runs in UI

temba/flows/models.py, temba/flows/tests.py, temba/flows/views.py, temba/mailroom/client.py, temba/mailroom/tests.py, templates/flows/flow_export_translation.haml
=> Remove option to include router arguments in downloaded PO files

temba/orgs/management/commands/update_analytics_consent.py, temba/settings_common.py, temba/urls.py, temba/utils/analytics/__init__.py, temba/utils/analytics/base.py, temba/utils/analytics/crisp/backend.py, temba/utils/analytics/crisp/tests.py, temba/utils/analytics/librato/backend.py, temba/utils/analytics/librato/tests.py
So just need to add this to settings files where we want the current analytics backends:
```python
ANALYTICS_TYPES = [
"temba.utils.analytics.crisp.CrispBackend",
"temba.utils.analytics.librato.LibratoBackend",
]
```
=> ⚡ Make loading of analytics backends dynamic

temba/contacts/models.py, temba/orgs/models.py
https://sentry.io/organizations/nyaruka/issues/2918778225/?environment=production&project=20737&referrer=alert_email
=> Fix group deletion as part of org deletion

templates/orgs/user_two_factor_enable.haml
Fix  to make sure the QR code it displayed
=> Include qrious.js script

static/css/temba-components.css, templates/orgs/login/login.haml, templates/orgs/login/two_factor_verify.haml
Now 1Password and automatic OTP works.
=> Fix login via password managers

package-lock.json, package.json
* Allow removing of cases in Split by Expression and Split by Field
* Fix select widgets for slow clickers
=> Some UI Fixes

temba/api/v2/tests.py, temba/channels/tests.py, temba/channels/types/jiochat/tests.py, temba/channels/types/wechat/tests.py
Fixes https://github.com/rapidpro/rapidpro/issues/1609
=> Fix misuse of assertTrue for comparisons

temba/contacts/models.py, temba/contacts/tests.py, temba/orgs/models.py
Think this caused https://github.com/rapidpro/rapidpro/issues/1615
=> Fix race condition in contact deletion

temba/msgs/models.py, temba/msgs/tests.py, temba/msgs/views.py
Adds https://github.com/rapidpro/rapidpro/issues/1048
We've actually allowed this over the API since forever and CasePro does it
=> Allow archiving of flow messages

temba/contacts/models.py, temba/flows/models.py
Possible source of deadlocks https://sentry.io/organizations/nyaruka/issues/3048691213/?referrer=alert_email&environment=production
=> Don't try interrupting session that is about to be deleted

temba/flows/views.py
Because mailroom doesn't know about them.. which might warrant changing but for now let's not error
=> Disallow PO export/import for archived flows

temba/channels/tests.py, temba/channels/views.py
https://sentry.io/organizations/nyaruka/issues/3103298135/?environment=production&project=20737&referrer=alert_email
=> Fix searching on calls list page

temba/orgs/views.py
...why didn't I add this sooner?
=> Add service button to org edit page

temba/contacts/migrations/0152_squashed.py, temba/contacts/models.py, temba/flows/migrations/0278_squashed.py, temba/flows/models.py, temba/utils/models.py, temba/utils/tests.py
The two models we currently use this with are things that RP doesn't even write any more
=> Remove no longer needed `RequiredFieldsMixin`

temba/api/v2/tests.py, temba/flows/models.py, temba/flows/tests.py, temba/flows/views.py
https://sentry.io/organizations/nyaruka/issues/3246487070/?alert_rule_id=5195&alert_timestamp=1651612054024&alert_type=email&environment=production&project=20737&referrer=alert_email
=> Fix copying flows to generate a unique name

temba/api/v2/serializers.py, temba/api/v2/tests.py, temba/api/v2/views.py, temba/api/v2/views_base.py
* Simplify checking org limits on creates
* Generalize prevention of updating system objects
* Generalize prevention of deleting system objects
* Allow deleting of groups used in flows (that's a soft dependency now)
=> Better API validation

temba/contacts/search/omnibox.py, temba/contacts/tests.py, temba/msgs/tests.py, temba/msgs/views.py
Asa far I can see this isn't used
=> Remove omnibox support for fetching by label and message

temba/contacts/tests.py, temba/settings_common.py, temba/tests/base.py, temba/tickets/models.py, temba/tickets/tests.py, temba/tickets/views.py, temba/utils/dates.py, temba/utils/export.py, temba/utils/tests.py
A temporary way to expose this data until we build the dashboard of our dreams
=> Add endpoint to export Excel sheet of ticket daily activity counts

temba/api/models.py, temba/api/v2/tests.py, temba/api/v2/views.py, temba/contacts/tests.py, temba/flows/tests.py, temba/locations/tests.py, temba/msgs/tests.py, temba/orgs/context_processors.py, temba/orgs/models.py, temba/orgs/tests.py, temba/tests/base.py
Caches auth group permissions on `OrgRole`
=> Better permissions checking part 1

temba/channels/models.py, temba/channels/tests.py, temba/channels/views.py, temba/flows/models.py, temba/flows/tests.py, temba/orgs/models.py, temba/orgs/tests.py, temba/orgs/views.py, temba/tests/base.py
Basically want all user/org role changes to go thru `Org.add_user` and `Org.remove_user` to make caching of that easier
=> Use `Org.add_user` to setup tests, don't rely on `User.get_org` in model code

temba/campaigns/models.py, temba/campaigns/tests.py, temba/contacts/models.py, temba/contacts/tests.py, temba/contacts/views.py, templates/contacts/contact_read.haml
Since this involves fetching different object types and merging and sorting them.. and it [hopefully] doesn't need to be paged.. didn't feel like it belonged in the API
=> Endpoint for scheduled contact events

package-lock.json, package.json, static/css/temba-components.css, temba/api/v2/serializers.py, temba/api/v2/tests.py, temba/contacts/tests.py, temba/contacts/views.py, temba/orgs/views.py, templates/contacts/contact_read_spa.haml, templates/spa.haml, templates/spa_frame.haml, templates/spa_page_menu.haml, templates/tickets/ticket_list.haml
* Show field count on tab
* Includes fix for standard ticket list
* Flow badge 
* Language badge
=> Spreadsheet layout for contact fields

temba/assets/tests.py, temba/channels/tasks.py, temba/msgs/management/commands/msg_console.py, temba/orgs/models.py, temba/orgs/tests.py, temba/orgs/views.py
So we don't have duplicates. Also replaces a few more cases of reading from role m2ms.
=> Fix fetching org users with given roles

temba/api/models.py, temba/api/tests.py, temba/channels/tests.py, temba/orgs/models.py, temba/orgs/tests.py, temba/orgs/views.py
And rework tests to not use role m2ms
=> Fix surveyor joins so new users are added to orgmembership as well

package-lock.json, package.json, templates/contacts/contact_read_spa.haml
=> Add contact ticket list

package-lock.json, package.json, temba/contacts/views.py, temba/flows/tests.py, temba/flows/views.py, templates/flows/flow_editor_spa.haml, templates/spa_frame.haml
Some minor tweaks for release:
* Fix spa history bug that erroneously pushed on history stack on pop
* Update components for fix on menu collapse margin bug
* Add new flow button for spa
=> Tweaks for release

static/js/labels.js, temba/campaigns/views.py, temba/msgs/views.py, temba/triggers/views.py, templates/campaigns/campaign_list_spa.haml, templates/contacts/contact_list.haml, templates/contacts/contact_list_include.haml, templates/contacts/contactgroup_list.haml, templates/gear_links_include.haml, templates/includes/short_pagination.haml, templates/msgs/message_box.haml, templates/spa_frame.haml
* Omit legacy list table listeners
* Add counts to campaign lists
* Fix trigger active/archive counts
=> [NR] Refresh menu on modax redirects

templates/contacts/contact_list.haml, templates/contacts/contact_read.haml, templates/contacts/contact_update.haml, templates/contacts/contact_update_fields_input.haml
This hopefully is the last of them.
=> More fallback modax references

temba/flows/tests.py, temba/flows/views.py
Same as what we did for msg labels a while back
=> Don't allow creating of flow labels with parents or editing labels to have a parent

temba/classifiers/views.py
=> fixed classifier page title

temba/channels/views.py
=> fixed channel page title

temba/api/v2/fields.py, temba/api/v2/serializers.py, temba/api/v2/tests.py, temba/contacts/models.py, temba/contacts/templatetags/contacts.py, templates/contacts/contact_read.haml
=> Add anon-display field to API contact results if org is anon 

package-lock.json, package.json, templates/flows/flow_editor_spa.haml, templates/flows/flow_results_spa.haml
Added charts to new analytics tab. Thankfully was able to repurpose what we had before after an audit and replace of any jquery usage.
Also added some control to make sure that runs and charts only poll while the tab is active.
=> Add charts to analytics tab

package-lock.json, package.json, templates/flows/flow_activity_chart.haml, templates/flows/flow_results_spa.haml, templates/spa_frame.haml
=> Add overview charts

package-lock.json, package.json, static/js/urls.js, temba/channels/tests.py, temba/channels/views.py, temba/contacts/tests.py, temba/mailroom/events.py, temba/mailroom/tests.py, temba/msgs/tests.py, temba/orgs/tests.py, temba/orgs/views.py, templates/archives/archive_list_spa.haml, templates/campaigns/campaign_list_spa.haml, templates/channels/channellog_calls.haml, templates/channels/channellog_list.haml, templates/channels/channellog_list_spa.haml, templates/contacts/contact_read_spa.haml, templates/flows/flow_create.haml, templates/flows/flow_editor_spa.haml, templates/frame.haml, templates/msgs/tags/channel_log_link.haml, templates/spa_frame.haml, templates/tickets/ticket_list.haml
* Fix history state on tickets and contacts
* Update footer
* Fix channel log links to include channel
* Add download icons for archives
* Fix create flow modal opener
* Flow editor embed styling
=> A few ui tweaks

package-lock.json, package.json, static/js/urls.js, temba/channels/tests.py, temba/channels/views.py, temba/contacts/templatetags/contacts.py, temba/contacts/tests.py, temba/request_logs/tests.py, templates/channels/channel_read.haml, templates/channels/channel_read_spa.haml, templates/channels/channellog.haml, templates/channels/channellog_group_base.haml, templates/channels/channellog_list_spa.haml, templates/channels/channellog_msg.haml, templates/includes/http_log.haml, templates/request_logs/httplog_list.haml
=> Fix channel log urls, tweak appearance

temba/channels/models.py, temba/channels/types/africastalking/type.py, temba/channels/types/blackmyna/type.py, temba/channels/types/dartmedia/type.py, temba/channels/types/facebook/type.py, temba/channels/types/globe/type.py, temba/channels/types/hub9/type.py, temba/channels/types/redrabbit/type.py, temba/channels/types/shaqodoon/type.py, temba/channels/types/telesom/type.py, temba/channels/types/thinq/type.py, temba/channels/types/twilio/type.py, temba/channels/types/twilio_messaging_service/type.py, temba/channels/types/twitter_legacy/type.py, temba/channels/types/verboice/type.py, temba/channels/types/vonage/type.py, temba/channels/types/yo/type.py, temba/channels/types/zenvia/type.py, temba/channels/views.py
Part of the larger war on `user.get_org()`
=> Change `ChannelType.is_available_to` and `is_recommended_to` to include org

temba/airtime/views.py, temba/channels/tests.py, temba/channels/views.py, temba/contacts/tests.py, temba/contacts/views.py, temba/flows/views.py, temba/middleware.py, temba/orgs/models.py, temba/orgs/tests.py, temba/orgs/views.py, temba/tests/crudl.py, temba/utils/tests.py
in favor of uniform treatment of staff users
=> Fix bug in user releasing and remove special superuser handling

static/js/urls.js, templates/tickets/ticket_list.haml
Was using the spa url when visiting tickets which broke refresh and deep linking within tickets.
=> Ticket history path

temba/flows/tests.py, temba/flows/views.py, temba/msgs/tests.py, temba/msgs/views.py, temba/tests/base.py, temba/tickets/tests.py, temba/tickets/views.py, temba/utils/export/__init__.py, temba/utils/export/models.py, temba/utils/export/views.py
Introduces a common base view for msg, ticket and result exports. Tidies up modal responses.
=> Simpler export views

temba/archives/models.py, temba/tests/s3.py
On reflection this probably isn't affecting us because it would require an org to have more than 1000 non-archive archive files...
=> Fix releasing other archive files to use proper pagination

temba/channels/models.py, temba/channels/tasks.py, temba/channels/tests.py, temba/mailroom/queue.py, temba/mailroom/tests.py
requires https://github.com/nyaruka/mailroom/pull/670 first
=> Interrupt channel by mailroom task

temba/campaigns/views.py, temba/channels/tests.py, temba/channels/views.py, temba/contacts/views.py, temba/flows/views.py, temba/orgs/tests.py, temba/orgs/views.py
=> Always put service menu options at end of menu in new group

templates/api/v2/api_explorer.haml, templates/api/v2/api_root.html, templates/orgs/org_token.haml
* Rewrite API Explorer to be vanilla javascript
Styling updates:
=> Update api docs to be nav agnostic

temba/schedules/models.py, temba/schedules/tests.py
=> Remove no longer used `Schedule.create_blank_schedule`

temba/contacts/models.py, temba/flows/models.py, temba/tickets/models.py, temba/utils/export/models.py, temba/utils/export/tests.py, temba/utils/tests.py
Rename `TableExporter` to `MultiSheetExporter` and have it do the preparing of values rather than the export tasks
=> 🚛 Simpler exports

temba/channels/types/whatsapp_cloud/tests.py, temba/channels/types/whatsapp_cloud/views.py
Fixes https://sentry.io/organizations/nyaruka/issues/3708428950/
=> Properly truncate the channel name

temba/orgs/tests.py, temba/orgs/views.py
=> Re-add org plan and plan end to update form

temba/middleware.py, temba/orgs/models.py, temba/orgs/tests.py, temba/orgs/views.py, temba/utils/brands.py
=> Use dropdown for brand field on org update form

temba/contacts/models.py, temba/contacts/tests.py
Fix for https://sentry.io/organizations/textit/issues/3730143385/
=> Catch CSV corrupted errors

temba/orgs/models.py, temba/orgs/views.py
And move plan selection to classmethod
=> 👗 Fix choice of brand for new orgs

temba/api/v2/serializers.py, temba/msgs/models.py, temba/msgs/views.py
https://github.com/rapidpro/rapidpro/issues/1377
=> Cleanup msg status constants

temba/notifications/models.py, temba/notifications/tests.py, temba/notifications/types/builtin.py, temba/orgs/tests.py, temba/utils/export/models.py
and have separate methods for email subject and template
=> Rework notifications to not be created thru Notification class

temba/orgs/views.py, templates/orgs/org_plan.haml
=> Show org plan end as relative time

package-lock.json, package.json, static/js/urls.js, temba/orgs/tests.py, temba/orgs/views.py, templates/campaigns/campaign_read_spa.haml, templates/orgs/user_read.haml, templates/orgs/user_update.haml
* Add user read page
* Update org filtering logic around suspended orgs
=> Update to manage views

.gitignore, code_check.py, poetry.lock, pre-commit.sh, pyproject.toml, setup.cfg, temba/channels/types/discord/tests.py, temba/flows/views.py
https://github.com/charliermarsh/ruff
=> ⚡️ Switch from flake8 to ruff

templates/flows/flow_editor.haml, templates/flows/flow_results.haml, templates/gear_links_include.haml, templates/spa_page_menu.haml
=> Fix transparency issue with content menu on editor page

.github/workflows/ci.yml, temba/flows/models.py, temba/flows/tests.py
Requires https://github.com/nyaruka/mailroom/pull/8
=> Bump engine version to 13.2

temba/orgs/tests.py, temba/orgs/views.py, templates/frame.haml
* Also put urls.js into compress for cache busting
=> Turns out we still want servicing on org read

templates/flows/flow_editor.haml, templates/flows/flow_editor_spa.haml, templates/frame.haml
This is so verification tests can use the same flow building snippets in old/new interface
=> Make old editor look closer to new one

temba/api/v2/fields.py, temba/api/v2/serializers.py, temba/api/v2/tests.py
Embraces the DRF way of using child fields to support stricter validation of things like translated attachments on broadcasts
=> 👮 Better and stricter API field validation

temba/orgs/tests.py, temba/orgs/views.py, temba/utils/views.py, templates/dashboard/home_spa.haml, templates/flows/flow_editor_spa.haml, templates/frame.haml, templates/spa_frame.haml
* Dashboard loads now whether initial page or clicking into it
* Redirect to org/start when previewing from root
* Fix old-nav logo to point to org/start instead of inbox
* Don't include dashboard in menu unless org has child org feature
=> Fixes for ungating ui

package.json, static/js/labels.js, templates/contacts/contact_list.haml, templates/spa_frame.haml, yarn.lock
* Fix searching contacts after direct navigation
* Fix race condition for menu refresh not always showing updated items
=> Small ui fixes

temba/channels/tests.py, temba/channels/types/facebookapp/views.py, temba/channels/types/instagram/views.py, temba/channels/types/whatsapp/tests.py, temba/channels/types/whatsapp_cloud/tests.py, temba/channels/types/whatsapp_cloud/views.py, temba/channels/views.py, temba/orgs/views.py, temba/utils/whatsapp/views.py, templates/channels/channel_bulk_sender_options.haml
Addresses  https://github.com/nyaruka/rapidpro/issues/4281
=> Use SpaMixin to more channels extra views

package.json, temba/flows/views.py, temba/orgs/views.py, temba/public/views.py, temba/utils/templatetags/temba.py, temba/utils/views.py, templates/channels/types/telegram/claim.haml, templates/channels/types/twilio_messaging_service/claim.haml, templates/contacts/contactimport_read.haml, templates/flows/flow_results_spa.haml, templates/orgs/user_two_factor_enable.haml, templates/orgs/user_two_factor_enable_spa.haml, templates/public/public_welcome.haml, templates/spa_frame.haml, yarn.lock
* No longer intercept clicks in spa-content
* Use target="_blank" for third party links
* Add press feedback in menu
* Launch trigger menu items with hrefs in a different window
* Stop activity on flow results from taking over page
* Update welcome page buttons to work inside spa
* Use absolute urls in history pushes
=> Update click handling

temba/assets/views.py, templates/assets/asset_read.haml, templates/assets/asset_read_spa.haml
=> Adjust export download page for new UI

package.json, temba/orgs/tests.py, temba/orgs/views.py, templates/spa_frame.haml, templates/tickets/ticket_list_spa.haml, yarn.lock
=> Fix layering for menu

package.json, templates/campaigns/campaign_list_spa.haml, templates/contacts/contact_list.haml, templates/contacts/contact_list_spa.haml, templates/flows/flow_list_spa.haml, templates/frame.haml, templates/msgs/message_box.haml, templates/msgs/message_box_spa.haml, templates/spa_frame.haml, templates/spa_page_menu.haml, yarn.lock
* Also removes some unnecessary hardcoded urls, yay
=> Broad support for meta click for new tabs

temba/orgs/views.py
=> Add menu path for org export and import

templates/spa_frame.haml
=> Warn users who go back to the old interface

package.json, static/css/temba-components.css, yarn.lock
=> Limit groups to a single line

static/css/tailwind.css, static/scss/tailwind.scss, temba/contacts/views.py, templates/tickets/ticket_list_spa.haml
Makes contact name on tickets a link to contact read if permitted
Depends on: https://github.com/nyaruka/rapidpro/pull/4461
=> Navigate to contact

package.json, templates/contacts/contact_read_spa.haml, yarn.lock
Hides tabs that are empty
Scrolls for busy contacts
=> Contact deets

temba/orgs/models.py, temba/orgs/tests.py
https://textit.sentry.io/issues/4068523124/?referrer=alert_email&alert_type=email&alert_timestamp=1680840041097&alert_rule_id=5195&environment=production&ref_fallback=ga
=> 🗑️ Fix deleting of orgs with incidents

package.json, templates/tickets/ticket_list.haml, yarn.lock
=> Make ticket banner expandable

templates/contacts/contact_list.haml, templates/spa_page_menu.haml
fixes https://github.com/nyaruka/rapidpro/issues/4480
=> Fix Delete All menu option on Archived contacts

package.json, static/js/labels.js, temba/msgs/tests.py, temba/msgs/views.py, temba/orgs/tests.py, temba/orgs/views.py, temba/settings_common.py, templates/flows/flow_list_spa.haml, templates/includes/recipients_contact.haml, templates/includes/recipients_group.haml, templates/msgs/message_box_spa.haml, yarn.lock
* Add anchors for menu items with hrefs
* Add hrefs to root menu items (except settings)
* Switch `/msg/inbox/` to `/msg/` with redirect view for bookmarks
* Add flow to message views where available
* Use `temba-label` instead of `.lbl` for list views for consistency
* Switch Msg > Flows to Msg > Handled
* Fixed box-shadow not showing on select widgets
* Added box-shadow back to field editors (they were removed for the excel-like version)
=> Main menu links

temba/tickets/views.py
=> Show counts of tickets by topic on tickets menu

temba/contacts/models.py
Still not sure how this will be searched on tho... `ticket = 1`.. `ticket = true`... `ticket = yes`?
=> Make `ticket` a reserved field name

temba/archives/tests.py, temba/archives/views.py, temba/campaigns/tests.py, temba/campaigns/views.py, temba/channels/models.py, temba/channels/tests.py, temba/channels/types/viber_public/tests.py, temba/channels/views.py, temba/classifiers/tests.py, temba/contacts/tests.py, temba/contacts/views.py, temba/flows/tests.py, temba/flows/views.py, temba/globals/tests.py, temba/globals/views.py, temba/msgs/tests.py, temba/msgs/views.py, temba/orgs/tests.py, temba/orgs/views.py, temba/request_logs/tests.py, temba/request_logs/views.py, temba/tests/crudl.py
Which often means no more content menu
=> 🧹 Remove non-spa items from content menus

package.json, yarn.lock
=> Update components and editor to support compose for somebody else

package.json, static/css/frame.css, static/js/frame.js, temba/tickets/models.py, temba/tickets/tests.py, temba/tickets/urls.py, temba/tickets/views.py, templates/contacts/contact_list.haml, templates/frame.haml, templates/spa_page_menu.haml, templates/tickets/ticket_list.haml, yarn.lock
* Change clipping rules so things on the right can overlap the main menu
* Ability to resize the ticket list pane, only persists until page reload for now
* New topic title header and content menu
* Add modal for editing topic names
=> Add ticket topic menu and resizer

temba/api/v2/serializers.py, temba/mailroom/client.py, temba/mailroom/tests.py, temba/tests/mailroom.py, temba/tickets/models.py, temba/tickets/tests.py, temba/tickets/views.py
Current UI uses ticket actions API endpoint
=> Remove old ticket assign view and support for notes with assignment

.github/workflows/ci.yml
Think this relates to https://github.com/python-poetry/poetry/pull/7606
=> Tweak how we run python scripts in CI

temba/contacts/search/mailroom.py, temba/flows/models.py, temba/flows/tests.py, temba/flows/views.py, temba/mailroom/client.py, temba/mailroom/tests.py, temba/msgs/models.py, temba/msgs/tests.py, temba/msgs/views.py, temba/tests/mailroom.py
And reworks flow start preview endpoint to remove stuff we don't use
=> 📺 Broadcast preview endpoint

static/js/labels.js, static/less/style.less, templates/campaigns/campaign_list.haml, templates/includes/short_pagination.haml, templates/triggers/trigger_list.haml
Sorry for the auto-formatting, will comment on the real bits.
=> Add select all on list pages

package.json, templates/includes/short_pagination.haml, templates/msgs/message_box.haml, yarn.lock
* Only show select all if there are items and actions
* Tweak alignment of box ever so slightly
* Fix message delete action
=> Add resend.

temba/orgs/models.py, temba/orgs/tests.py, temba/orgs/views.py
Also fixes not showing surveyor role
=> 🔭 Make viewer role a feature that can be toggled

temba/channels/views.py, templates/airtime/airtimetransfer_read.haml, templates/channels/channel_configuration.haml, templates/channels/channellog_call.haml, templates/channels/channellog_msg.haml, templates/channels/channellog_owned_base.haml, templates/channels/channellog_read.haml, templates/request_logs/httplog_read.haml
and fix channel log read menu path
=> 🪛 Fix calls to `prettyPrint()` that aren't sploaded

static/js/utils.js, templates/api/v2/api_explorer.haml, templates/frame.haml, templates/tickets/ticket_list.haml, templates/triggers/trigger_update.haml
Some cherry picked commits from https://github.com/nyaruka/rapidpro/pull/4566
=> Remove some uses of django tags inside javascript

.gitignore, temba/flows/views.py, templates/flows/flow_import_translation.haml, templates/orgs/org_export.haml
=> Fix import translation to use new UI

package.json, temba/campaigns/tests.py, temba/campaigns/views.py, temba/utils/fields.py, templates/campaigns/campaignevent_update.haml, templates/flows/flow_broadcast.haml, templates/tickets/ticket_list.haml, yarn.lock
This is to address shortcomings with the select widget now that components treat them more like standard form controls.
=> Updates for select widget to behave with more standard form controls

temba/archives/models.py, temba/orgs/tests.py, temba/settings_common.py
Cuz we're about to add yet another for logs
=> 🧹 Cleanup settings for S3 buckets

poetry.lock, pyproject.toml
4.2 supports multiple storages.. which would be a nice way to model access to attachments, archives, logs etc
=> Update to Django 4.2

temba/contacts/views.py
Inconsistent ordering of these groups was found by a RF test and this will make them deterministic.
=> Sorted group list when editing contacts

temba/channels/tests.py, temba/channels/views.py, temba/settings_common.py, templates/channels/channel_read.haml
Extracted from the hamless branch
=> Switch channel charts to load with json instead of embedded data

temba/utils/management/commands/mailroom_db.py
so it's always correct version
=> Use pg_dump/restore from docker container in `mailroom_db` command

poetry.lock, pyproject.toml, temba/orgs/tests.py, temba/orgs/views.py, templates/orgs/org_export.haml
=> Fix org export page

templates/contacts/contact_list.html
Fix contact list sorting order indicator icon
=> Add show CSS class to icon for contact list sorting

temba/triggers/models.py, temba/triggers/tests.py, temba/triggers/types.py, temba/triggers/views.py, templates/triggers/trigger_create_opt_in.html, templates/triggers/trigger_create_opt_out.html
icons to-be-tweaked before opening up to users
=> Add opt-in and opt-out trigger types (staff only for now)

temba/orgs/models.py, temba/orgs/views.py
And move code into separate method so we can more easily call it when testing emails
=> Use proper secret generation for recovery tokens 

temba/triggers/models.py, temba/triggers/tests.py, temba/triggers/types.py, temba/triggers/views.py
Add base classes for trigger types that are based on channel activity
=> Extend channel to more trigger types, part 1

temba/api/internal/tests.py, temba/api/tests.py, temba/api/v2/tests.py
Thus far implemented for globals and labels
=> Improve testing of API endpoints

temba/contacts/models.py, temba/triggers/models.py, temba/triggers/tests.py, temba/triggers/types.py, temba/triggers/views.py, templates/triggers/trigger_create_inbound_call.html
=> Add optional channel field to trigger types that are based on channel activity

package.json, temba/triggers/views.py, templates/includes/recipients.html, templates/includes/recipients_group.html, templates/triggers/trigger_list.html, yarn.lock
=> Show exclusion groups on trigger list pages

templates/flows/flow_list.html
=> Make sure we show the issue icon on the flow list page

temba/flows/tests.py, temba/flows/views.py, temba/triggers/tests.py, temba/triggers/types.py, temba/triggers/views.py, templates/triggers/trigger_create_keyword.html, templates/triggers/trigger_list.html, templates/triggers/types/keyword.html
=> Support multiple keywords per trigger in UI

temba/triggers/types.py, templates/flows/flow_list.html, templates/includes/recipients_contact.html, templates/includes/recipients_group.html, templates/triggers/trigger_list.html, templates/triggers/types/catch_all.html, templates/triggers/types/closed_ticket.html, templates/triggers/types/inbound_call.html, templates/triggers/types/missed_call.html, templates/triggers/types/new_conversation.html, templates/triggers/types/opt_in.html, templates/triggers/types/opt_out.html, templates/triggers/types/referral.html, templates/triggers/types/schedule.html
=> Improve display of triggers on list pages

temba/utils/templatetags/temba.py, temba/utils/tests.py, templates/triggers/types/keyword/desc.html
And use for rendering trigger keywords
=> Update oxford template filter to allow different conjunctions

temba/orgs/models.py, temba/orgs/tests.py, temba/orgs/views.py
* Get rid of `StartMixin` and always redirect thru the actual start view for simplicity
* Move start view config into `OrgRole`
* Always go to start view instead of inbox
=> Fix join redirection for agent users

package.json, temba/triggers/types.py, temba/triggers/views.py, templates/triggers/trigger_list.html, yarn.lock
Does https://github.com/nyaruka/textit/issues/171
=> Update trigger type icons

temba/orgs/tests.py, temba/orgs/views.py
Fixes https://textit.sentry.io/issues/4593558790/?project=21956
=> Fix org start view when org isn't set

temba/msgs/tests.py, temba/msgs/views.py, templates/msgs/broadcast.html
A few changes:
* Update scheduled broadcast to send now does the right thing
* Don't show broadcasts without a next_fire on scheduled list
* Use modified on instead of created on for broadcast sent
=> Update scheduled broadcast to send now

temba/flows/tests.py, temba/flows/views.py
Fixes https://textit.sentry.io/issues/4544293918/ and https://textit.sentry.io/issues/4659325508/
=> Fix IVR simulation

temba/utils/whatsapp/tasks.py, temba/utils/whatsapp/tests.py
Fixes https://textit.sentry.io/issues/4675333032/
=> Fix syncing OTP utility templates

temba/channels/views.py
When we extracted the channel count view into it's own view, some stuff ended up in chart that isn't used
=> Remove duplication between channel read and chart views

temba/channels/models.py, temba/channels/tests.py
Fixes https://textit.sentry.io/issues/4561400661/
=> Fix channel log display when missing URN

temba/contacts/views.py, temba/flows/tests.py, temba/flows/views.py, temba/msgs/views.py, temba/tickets/views.py, temba/utils/export/views.py
=> Simplify messaging when export is started

temba/contacts/models.py, temba/orgs/models.py, temba/orgs/tests.py, temba/orgs/views.py, temba/tickets/models.py, templates/contacts/export_download.html, templates/orgs/export_download.html
=> Improve export download page

temba/contacts/tests.py, temba/orgs/models.py, temba/tickets/tests.py
Fixes https://textit.sentry.io/issues/4928103120
=> Remove using readonly DB connection for fetching groups and fields

temba/notifications/tasks.py, temba/notifications/tests.py, temba/orgs/models.py, temba/orgs/tasks.py, temba/orgs/tests.py, temba/orgs/views.py, temba/settings_common.py
Exports live 90 days and notifications 30 days.. and make sure we delete export files from storage.
=> Trim old exports and notifications

temba/channels/types/dialog360/tests.py, temba/channels/types/dialog360/type.py, temba/channels/types/dialog360_legacy/tests.py, temba/channels/types/dialog360_legacy/type.py, temba/channels/types/whatsapp/tests.py, temba/channels/types/whatsapp/type.py, temba/channels/types/whatsapp_legacy/tests.py, temba/channels/types/whatsapp_legacy/type.py, temba/utils/whatsapp/__init__.py, temba/utils/whatsapp/tasks.py, temba/utils/whatsapp/tests.py
* Only create incidents after 5 failures
=> Cleanup code for fetching WhatsApp templates

temba/contacts/models.py, temba/contacts/tests.py, temba/contacts/views.py, templates/contacts/contact_export.html
=> Restrict exports of contact groups that are too big

temba/contacts/models.py, temba/contacts/tests.py, temba/contacts/views.py, temba/mailroom/client.py, temba/mailroom/tests.py, temba/tests/mailroom.py, templates/contacts/contact_export.html
And cleanup the tests for contact exports...
=> Improve contact export modal and use mailroom endpoint to know how many contacts will be exported

templates/utils/whatsapp/templates.html
=> Show more components for WA templates list

temba/api/internal/serializers.py, temba/api/internal/tests.py, temba/channels/types/dialog360/tests.py, temba/channels/types/dialog360_legacy/tests.py, temba/channels/types/whatsapp_legacy/tests.py, temba/flows/tests.py, temba/orgs/tests.py, temba/templates/models.py, temba/templates/tests.py, temba/utils/management/commands/data/mailroom_db.json, temba/utils/management/commands/test_db.py, temba/utils/whatsapp/templates.py, temba/utils/whatsapp/tests.py, templates/utils/whatsapp/templates.html
Requires https://github.com/nyaruka/mailroom/pull/212 deployed
=> Save `TemplateTranslation.components` as list, use `comps_as_dict` for API endpoint

static/css/tailwind.css, static/js/formax.js, static/scss/tailwind.scss, temba/orgs/views.py, yarn.lock
=> Switch formax to expand vertically

templates/channels/channel_claim.html
=> Simplify channel claim page styling and remove unused styles

temba/templates/views.py
http://app.rapidpro.io/templatetranslation/channel/6067f421-14c5-4fad-b289-94f46c603592/
becomes...
http://app.rapidpro.io/template/channel/6067f421-14c5-4fad-b289-94f46c603592/
=> Simplify URL for template list page

temba/orgs/models.py
https://textit.sentry.io/issues/5244735295/?project=21956
=> Remove start url for surveyors and instead do login redirect

temba/orgs/tasks.py, temba/orgs/tests.py, temba/settings_common.py
Not considered good practice to leave invitations around indefinitely.
=> Expire invitations

temba/orgs/tasks.py, temba/orgs/views.py, temba/settings_common.py, templates/orgs/invitation_create.html
=> Add blurb to invite modal to explain that invite links expire

temba/api/v2/views.py
Trying to make them more consistent...
=> Cleanup API endpoint docs

package.json, temba/campaigns/tests.py, temba/orgs/models.py, temba/orgs/tests.py, temba/orgs/views.py, templates/orgs/definitions_download.html, yarn.lock
the notifications will require https://github.com/nyaruka/temba-components/pull/423
=> Change flow definitions export to be async, using ExportType

temba/channels/android/views.py, temba/channels/tests.py, temba/mailroom/client.py, temba/mailroom/tests.py, temba/tests/mailroom.py
Requires https://github.com/nyaruka/mailroom/pull/241
=> Send phone instead of urn to mailroom android endpoints

temba/channels/android/tests.py, temba/channels/android/views.py, temba/channels/tests.py, temba/tests/mailroom.py
To match https://github.com/nyaruka/gocommon/pull/124
=> Update to allow matching sender ID as valid phones

temba/contacts/tests.py, templates/contacts/contact_list.html
=> Re-add search errors to contact list views

static/js/labels.js, temba/campaigns/tests.py, temba/triggers/tests.py, temba/utils/views.py, templates/includes/short_pagination.html
* Update bulk action icons
* Report bulk action errors to users with django messages
=> Fix action to remove from group

temba/contacts/tests.py, temba/contacts/views.py, temba/mailroom/client.py, temba/mailroom/tests.py, temba/orgs/tests.py, temba/tests/mailroom.py
=> Rework contact create view to let mailroom do the URN validation

temba/channels/android/tests.py, temba/channels/android/views.py, temba/channels/tests.py, temba/tests/mailroom.py
Requires https://github.com/nyaruka/mailroom/pull/253
=> Lean on mailroom for validation of phone numbers from android events

static/js/labels.js, temba/utils/views.py
Rely on https://github.com/nyaruka/rapidpro/pull/5257/files#diff-77fd99b3305c90fe5ce2b3a41f6bc30cfc1f3a79861388ce96c9c70cee92a0b6L230-L231 to work
So we need the `add` field in the form
=> Fix flow and msgs unlabel action

templates/api/v2/explorer.html
I think broken since the jQuery removal
=> Fix API explorer POSTs

static/js/frame.js, templates/frame.html, templates/spa.html
This reverts commit d3fd7ef8a3b46362b4748bb11dc1715c051b30c2.
=> Revert "Remove csrf token hidden element not under a form"

temba/contacts/forms.py, temba/contacts/tests.py, temba/mailroom/client.py, temba/mailroom/tests.py, temba/tests/mailroom.py, templates/contacts/contact_update.html
=> Lean on mailroom for URN validation during contact update

templates/templates/templatetranslation_channel.html
=> Add pagination on channel templates page

temba/mailroom/client.py, temba/mailroom/tests.py, temba/msgs/models.py, temba/msgs/tasks.py, temba/msgs/tests.py, temba/msgs/views.py, temba/tests/mailroom.py
=> Use mailroom endpoint to send broadcasts to flow nodes

temba/utils/management/commands/mailroom_db.py
I keep running into problems where vscode is running something on port 8090... so now this command does its business over port 8092.
=> Tweak `mailroom_db` to run on different port

temba/campaigns/tests.py, temba/campaigns/views.py
=> Tweak menu on campaign read page

temba/globals/models.py, temba/globals/tests.py, temba/orgs/models.py, templates/globals/global_list.html
And move `annotate_usage` into `DependencyMixin` so it can be used by other flow dependency types.
=> Fix globals list template

temba/msgs/tests.py, temba/msgs/views.py, templates/msgs/broadcast_create_schedule.html
=> Once a scheduled broadcast always a scheduled broadcast

temba/dashboard/tests.py, temba/dashboard/views.py
Make sure we include only workspace that have stats
=> Fix dashboard workspace data

temba/api/models.py, temba/api/v2/tests.py
Avoids https://textit.sentry.io/issues/5594610256/
=> Fix handling of POSTs to API docs

temba/templates/tests.py, templates/templates/includes/translation.html
=> Show template translation problems as errors on template read page

temba/campaigns/models.py, temba/campaigns/tests.py, temba/contacts/models.py, temba/flows/models.py, temba/msgs/models.py, temba/orgs/models.py, temba/orgs/tests.py, temba/templates/models.py, temba/tickets/tests.py, temba/triggers/models.py, temba/triggers/tests.py, temba/utils/models/base.py
These are just for us when cowboy coding or looking at sentry
=> Add `__repr__` to more models and tweak existing ones for consistency

temba/orgs/tests.py, temba/orgs/views.py
Otherwise you get duplicates https://textit.sentry.io/issues/5638034501/?project=20737
=> Ensure that emails are consistently treated as case insensitive

temba/apks/models.py, temba/channels/android/views.py, temba/channels/tests.py, temba/notifications/incidents/__init__.py, temba/notifications/incidents/builtin.py, templates/channels/types/android/claim.html
(note this is local and I don't have an apk in my test db)
=> Fix Android claim page and ending outdated app incidents

templates/orgs/org_manage_accounts.html
=> Add cutoff date for using viewer role

package.json, temba/api/v2/views.py, temba/contacts/models.py, temba/contacts/tests.py, temba/contacts/views.py, temba/mailroom/modifiers.py, temba/tests/mailroom.py, yarn.lock
Requires https://github.com/nyaruka/mailroom/pull/308
=> Update open ticket modal to use note instead of body

package.json, temba/channels/models.py, temba/flows/tests.py, temba/flows/views.py, temba/msgs/tests.py, temba/msgs/views.py, temba/orgs/models.py, temba/settings_common.py, templates/flows/flow_start.html, yarn.lock
* Add DEFAULT_EXCLUSIONS, SEND_HOURS_WARNING, and SEND_HOURS_BLOCK for flow starts and broadcasts
* Only allow one flow start at a time
* Remove inactive_threshold in favor of send hours warning/blocking
=> Add some controls around flow starts

temba/mailroom/queue.py, temba/mailroom/tests.py
Requires https://github.com/nyaruka/mailroom/pull/324
=> Use 'tasks:batch' queue name instead of 'batch'

media/test_imports/invalid.txt.xlsx, temba/contacts/models.py, temba/contacts/tests.py
Fix https://textit.sentry.io/issues/5861787406
=> Show bad file error as validation errors to the user

temba/api/internal/serializers.py, temba/api/internal/tests.py, temba/api/internal/urls.py, temba/api/internal/views.py
=> Ticket response shortcuts part 2

temba/airtime/views.py, temba/api/v2/views.py, temba/archives/views.py, temba/campaigns/views.py, temba/channels/types/plivo/views.py, temba/channels/types/twilio/views.py, temba/channels/types/vonage/views.py, temba/channels/types/whatsapp/views.py, temba/channels/views.py, temba/classifiers/views.py, temba/contacts/views.py, temba/dashboard/views.py, temba/flows/views.py, temba/globals/views.py, temba/locations/views.py, temba/msgs/views.py, temba/notifications/views.py, temba/orgs/mixins.py, temba/orgs/views.py, temba/request_logs/views.py, temba/templates/views.py, temba/tickets/views.py, temba/triggers/views.py, temba/utils/whatsapp/views.py
=> Move org dependent view mixins into mixins module

templates/campaigns/campaign_list.html, templates/contacts/contact_list.html, templates/flows/flow_list.html, templates/globals/global_list.html, templates/msgs/message_box.html, templates/staff/org_list.html, templates/staff/user_list.html, templates/triggers/trigger_list.html
* Remove unnecessary flex divs around search boxes
* Make margin between search box and table consistently 4
* Make empty table styling consistent
=> Make list views more consistent

templates/channels/channel_claim_number.html
Fixes displaying well validation errors from the clean methods such as checking unique addresses
=> Fix claim number to display non field errors

static/css/tailwind.css, static/scss/tailwind.scss, templates/channels/types/freshchat/claim.html, templates/channels/types/line/claim.html, templates/channels/types/messagebird/claim.html, templates/channels/types/rocketchat/claim.html, templates/channels/types/slack/claim.html, templates/channels/types/slack/config.html, templates/channels/types/telegram/claim.html
BEFORE
Facebook
FreshChat
AFTER
Facebook
FreshChat
=> More clarifications on FC channel claim

temba/tickets/tests.py, temba/tickets/views.py
* Add query checks to ticket view tests
* Tweak how we render tickets to JSON to avoid lazy fetched fields
=> Fix N+1 queries on ticket fetches

templates/no_nav.html, templates/orgs/org_join_accept.html
=> Fix styling on join-accept page

temba/orgs/views/views.py, temba/staff/views.py, templates/orgs/user_list.html
=> Show on user list pages whether user has 2FA enabled

temba/utils/models/squashable.py
and it doesn't quite match how we're doing generic counts now
=> Merge old `ScopedCountModel` into `DailyCountModel` since that's only place it's used

temba/flows/views.py
To make it easier to switch the data source to the new counts
=> Cleanup `FlowCRUDL.ActivityData`

temba/flows/tests.py, temba/flows/views.py
They'll be validating if someone tries to preview/revert-to them and we can't hit mailroom that many times in a single request.
=> Stop validating flow revisions when fetching revision list

temba/flows/tests.py, temba/flows/views.py, templates/flows/flow_engagement.html, templates/flows/flow_results.html
that returns both data and template
=> Merge activity_data and activity_chart into a single engagement view

package.json, templates/flows/flow_results.html, yarn.lock
v0.113.0
* Update tabs to be more judicious about firing context change 
* Allow longer tab names
=> Only load flow results once per page load

temba/api/v2/tests.py, temba/api/v2/views.py, temba/contacts/models.py, temba/flows/models.py, temba/flows/views.py
This has always been an issue: https://textit.sentry.io/issues/6095627945 (new count model) https://textit.sentry.io/issues/5649439402 (old count model)
=> Prefetch run status counts used by flows list view and flows API endpoint

temba/flows/models.py, temba/flows/tests.py
This reverts commit f39fa98c8d38ffb67c08d6fdc9a6c39d54781eea.
=> Revert "Remove input/text columns from results exports"

templates/flows/flow_results.html
Not even removing the views just yet.. let's see how it goes?
=> Remove ability to delete runs from the UI

temba/flows/models.py, temba/flows/tests/test_flow.py, temba/flows/tests/test_flowcrudl.py, temba/flows/tests/test_run.py
Note that these counts aren't deleted when runs are deleted... need to decide whether we implement that, allow run deletion that doesn't affect these counts, or even remove run deletion altogether.
=> Read from new category count model

package.json, static/css/frame.css, templates/includes/short_pagination.html, yarn.lock
This fixes three issues
- Adds inner scroll for those with many labels
- Fixes dropdown arrow alignment when toggle slot is narrow (case with labels)
- Tweaks padding settings for root levels menu icons so notifications is in line with other icons
=> Label dropdown fixes

temba/users/models.py
No actual changes to fields yet
=> Inherit AbstractBaseUser instead of AbstractUser but copy over existing fields

temba/api/v2/serializers.py, temba/api/v2/views.py, temba/archives/management/commands/audit_archives.py, temba/flows/models.py, temba/flows/tests/test_export.py, temba/flows/views.py, templates/flows/flow_list.html
* Show ongoing + total + completion (we currently just show total + completion)
* Show total + completion on archived list (we currently show nothing)
=> Add number of ongoing runs to the flow list view

temba/contacts/migrations/0205_create_session_expires_fires.py, temba/contacts/tests/test_migrations.py
One day we'll fix the code that can leave contacts in this state...
=> Fix contacts whose `current_session_uuid` doesn't match a waiting session

temba/public/tests.py, temba/public/urls.py, temba/public/views.py, templates/public/public_forgetme.html
=> Add forgetme view to check the delete confirmation

temba/api/v2/tests/test_flows.py, temba/api/v2/views.py, temba/flows/tests/test_flowcrudl.py, temba/flows/views.py
If we ever reintroduced system flows it would be like system groups and fields which still appear in the UI
=> Remove no longer need filtering out of system flows

temba/api/v2/fields.py, temba/api/v2/serializers.py, temba/api/v2/tests/test_broadcasts.py, temba/api/v2/tests/test_messages.py, temba/api/v2/tests/test_serializers.py, temba/mailroom/client/client.py, temba/mailroom/client/tests.py, temba/msgs/models.py, temba/msgs/tests/test_quick_reply.py, temba/tests/mailroom.py
Also adds `QuickReply` dataclass.. which serves as a way to ensure only text+extra end up in messages.
=> Add API support for extra on quick replies

temba/api/v2/serializers.py, temba/api/v2/tests/test_channels.py
Addresses https://github.com/nyaruka/rapidpro/discussions/5959
=> Add channel type to channels API endpoint

temba/contacts/models.py, temba/contacts/tests/test_contact.py, templates/contacts/contact_read.html
=> Fix fetching scheduled broadcasts for contacts so we don't return dupes

temba/ai/tests/test_llmcrudl.py, temba/ai/views.py, templates/ai/llm_list.html, templates/orgs/dependency_delete_modal.html
=> Fix LLM list page to display icons and add update modal to allow name changes

package.json, poetry.lock, pyproject.toml, temba/ai/tests/test_llmcrudl.py, temba/ai/types/anthropic/tests.py, temba/ai/types/anthropic/type.py, temba/ai/types/anthropic/views.py, temba/ai/types/openai/tests.py, temba/ai/types/openai/type.py, temba/ai/views.py, temba/settings_common.py, yarn.lock
@ericnewcomer missing anthropic icon
=> Add anthropic as LLM option in UI

temba/channels/types/bandwidth/tests.py, temba/channels/types/bandwidth/type.py, temba/channels/types/bandwidth/views.py
=> Add support for claiming BW voice channels

temba/api/v2/views.py
Otherwise you get https://textit.sentry.io/issues/6504471634
=> Always validate UUID query params on API endpoints before trying to filter by them

temba/ai/models.py, temba/ai/tests/test_llm.py, temba/ai/types/anthropic/tests.py, temba/ai/types/openai/tests.py
Requires https://github.com/nyaruka/mailroom/pull/542
=> Stop writing LLM model name into config as well

temba/orgs/views/forms.py, temba/orgs/views/tests/test_orgcrudl.py, temba/orgs/views/views.py, temba/settings_common.py, temba/tests/base.py, temba/urls.py, temba/users/adapter.py, temba/users/forms.py, temba/users/models.py, temba/users/urls.py, temba/users/views.py, templates/account/login.html, templates/account/password_change.html, templates/account/signup.html, templates/allauth/elements/fields.html, templates/allauth/elements/provider.html, templates/allauth/elements/provider_list.html, templates/allauth/layouts/base.html, templates/orgs/org_signup.html, templates/socialaccount/connections.html, templates/socialaccount/email/account_connected_message.html, templates/socialaccount/email/account_connected_subject.txt, templates/socialaccount/email/account_disconnected_message.html, templates/socialaccount/email/account_disconnected_subject.txt, templates/socialaccount/snippets/login.html
- Add support for social account logins.
- Move invitations to run through login and signup flows
=> Add social account signup

templates/flows/flow_list.html
=> Fix listing of archived flows

temba/msgs/views.py
Make broadcast page order by recent first
=> Explicitly set the order the broadcast list page

temba/api/v2/serializers.py, temba/flows/models.py, temba/flows/tests/test_export.py, temba/flows/tests/test_flow.py, temba/flows/tests/test_flowcrudl.py, temba/flows/views.py
Requires https://github.com/nyaruka/mailroom/pull/556
=> Use `Flow.info` instead of `Flow.metadata`

temba/ai/views.py, temba/mailroom/client/client.py, temba/mailroom/client/exceptions.py, temba/mailroom/client/tests.py
Requires https://github.com/nyaruka/mailroom/pull/561
=> Update LLM service exception

temba/orgs/models.py, temba/orgs/tests/test_org.py
Fix https://textit.sentry.io/issues/6497174080/
=> Igrore invalid date when formating datetime

temba/settings_common.py, temba/templates/views.py, templates/templates/template_list.html
and remove mention of automatic syncing
=> Make refresh a button on the template list page

temba/notifications/models.py, temba/staff/tests.py, temba/staff/views.py, temba/users/models.py, temba/users/tests/test_user.py
Adds menu options to staff user read page
=> Easier manual user verification

temba/orgs/tests/test_counts.py, temba/utils/models/counts.py
https://textit.sentry.io/issues/6633571025/
=> Fix ticket menu for users with access to zero topics

temba/users/forms.py
Fix https://textit.sentry.io/issues/6653526566/
=> Only delete invite secret in session if present

temba/api/v2/tests/test_campaign_events.py, temba/api/v2/tests/test_campaigns.py, temba/campaigns/models.py, temba/campaigns/tests/test_campaign.py, temba/campaigns/tests/test_campaigncrudl.py, temba/mailroom/client/client.py, temba/mailroom/client/tests.py, temba/orgs/tests/test_definitionexport.py, temba/tests/mailroom.py
Requires https://github.com/nyaruka/mailroom/pull/649
=> Tweak mailroom endpoint used to schedule campaign events/points

package.json, templates/flows/flow_list.html, templates/flows/flow_results.html, yarn.lock
* Nicer chart layout with clamped height that also handles responsive resize better
* No more chart animations
* Fix full page reload when clicking on results percentage
=> Nicer chart layout on results

temba/flows/tests/test_flowcrudl.py, temba/flows/views.py
* Send call for IVR flows separately as well as on trigger
* Include call UUID
=> Sim tweaks

temba/mailroom/client/client.py, temba/mailroom/client/tests.py, temba/orgs/models.py, temba/tests/mailroom.py
Requires https://github.com/nyaruka/mailroom/pull/671
=> Pass is_import=true for flow inspect for imports

temba/contacts/models.py, temba/contacts/tests/test_groupcrudl.py, temba/mailroom/client/client.py, temba/mailroom/client/tests.py, temba/mailroom/queue.py, temba/tests/mailroom.py
Requires https://github.com/nyaruka/mailroom/pull/685
=> Populate dynamic groups via endpoint instead of queueing task

temba/api/v2/serializers.py, temba/api/v2/tests/test_contact_actions.py, temba/api/v2/tests/test_flows.py, temba/contacts/models.py, temba/contacts/tests/test_contact.py, temba/flows/legacy/tests.py, temba/flows/models.py, temba/flows/tests/test_flow.py, temba/flows/tests/test_flowcrudl.py, temba/flows/tests/test_startcrudl.py, temba/mailroom/client/client.py, temba/mailroom/client/tests.py, temba/mailroom/queue.py, temba/mailroom/tests/test_queue.py, temba/msgs/tests/test_msg.py, temba/orgs/tests/test_definitionexport.py, temba/tests/mailroom.py
Requires https://github.com/nyaruka/mailroom/pull/692 and https://github.com/nyaruka/mailroom/pull/691
=> Call mailroom endpoints to interrupt by flow or contacts

temba/contacts/tests/test_fieldcrudl.py, temba/contacts/views.py
Fixes https://github.com/nyaruka/rapidpro/issues/6196
=> Do not allow changing field type for fields used in groups

templates/contacts/contactimport_preview.html
=> Alignment tweaks on contact import preview

static/js/frame.js
=> Don't populate history until page is fetched

temba/contacts/models.py, temba/contacts/tests/test_contactcrudl.py, temba/mailroom/events.py, temba/mailroom/tests/test_event.py
Requires https://github.com/nyaruka/rapidpro/pull/6237
=> Read call events from DynamoDB

templates/flows/flowstart_list.html
https://textit.sentry.io/issues/6877297178/
=> Fix flow start list page when start is pending

temba/tickets/models.py, temba/tickets/tests/test_ticketcrudl.py
=> Improve testing of ticket folder views ahead of some changes

temba/api/v2/serializers.py, temba/api/v2/tests/test_broadcasts.py, temba/api/v2/tests/test_messages.py, temba/api/v2/views.py, temba/tests/mailroom.py
Requires https://github.com/nyaruka/mailroom/pull/845
=> Add UUID to Broadcast and Message API representations and depublicize ID
