nyaruka/rapidpro

temba/flows/migrations/0005_auto_20141216_0629.py
temba/flows/migrations/0007_auto_20150115_1926.py
temba/flows/models.py
temba/flows/tasks.py
temba/flows/tests.py

We weren't using the same expiration path when expiring flow runs from the cron. This change uses a shared method for the cron and for an individual run.expire(). The expiration for activity here is a bit more complex than before in order to be considerate of large batches of expirations occurring at once.

Use the same path when expiring single flow runs and batch expirations

---

temba/api/serializers.py
temba/api/tests.py
temba/api/views.py

Removes messages from serialized broadcasts as this will get too large on big broadcasts. As an alternative, added filtering by broadcast id to messages endpoint

Broadcasts api fix

---

static/coffee/flows/controllers.coffee

Newly created actions weren't getting uuids which resulted in mismatched audio recordings if uploads where made before the flow was reloaded.
This is a fix for rapidpro/rapidpro#123

Fix IVR prompt uploads

---

media/test_imports/capture-recording.json
temba/ivr/models.py
temba/ivr/tests.py
temba/ivr/views.py
temba/tests.py

Handle case when speaker hangs the phone up immediately after making their recording. This is probably a pretty common scenario for recordings (such as in the case of leaving a voicemail).

Save recordings when speaker hangs up immediately afterwards

---

media/test_imports/call-me-maybe.json
media/test_imports/gather-digits.json
temba/flows/models.py
temba/ivr/tests.py

When gathering multi-digit keypad entry we are sending a bogus attribute to twilio. The end result is the same since we only allow sending the default today, but customers get warnings in their Twilio logs.

Send proper finish key attribute on gather

---

temba/api/views.py
temba/flows/models.py
temba/flows/tests.py
temba/ivr/migrations/0003_auto_20150129_1725.py
temba/ivr/migrations/0004_auto_20150129_1727.py
temba/ivr/migrations/0005_auto_20150129_1759.py
temba/ivr/migrations/0006_auto_20150130_1709.py
temba/ivr/migrations/0006_auto_20150203_0558.py
temba/ivr/migrations/0007_auto_20150203_0743.py
temba/ivr/models.py
temba/ivr/tests.py
temba/msgs/migrations/0003_auto_20150129_0515.py
temba/msgs/models.py
temba/orgs/models.py
temba/orgs/tests.py
templates/contacts/contact_read.haml
templates/flows/flow_results_contact.haml

Create messages for all interactions during an IVR call
A few notes:
* Migration only creates incoming messages (we don't have enough information to create outgoing messages). It's better to have this migration than not, otherwise, the runs will appear empty for legacy IVR runs. While the end result isn't fantastic, It's the best we can do. 
* With IVRAction gone, all incoming messages that were created above will take over the topup of the IVRAction it is replacing. This means that orgs will essentially be debited for historical IVR, but only for the incoming messages. The actions representing the outgoing messages are removed (and the topup ids attached to them). If a topup is recalculated, they will get these credits back, but if the topup has already been exhausted they may not. This …

IVR as messages

---

static/coffee/flows/services.coffee
static/coffee/simulator.coffee
temba/flows/models.py
temba/flows/tests.py
templates/flows/flow_editor.haml

* Reduce quiet period from 5s to 0.5s
* Remove revisions occurring in the last minute when creating revisions
* Don't post messages in the simulator until outstanding saves are complete
* Warn user if they try to leave before the flow is done saving

Quicker flow saves

---

temba/api/tests.py
temba/api/views.py
temba/channels/models.py
temba/msgs/models.py
temba/msgs/tests.py
temba/orgs/tests.py

Fixes the case that we weren't clearing our failsafe double send redis key when vumi came back with an error sending. (ie, when the downstream smsc fails)

Fixes asynchronous Vumi failures not retrying

---

static/coffee/flows/controllers.coffee

* Recalculate connection offsets when updating webhook length on rulesets
* Make sure dialog is dismissed before updating ruleset

Connection offsets

---

temba/flows/migrations/0013_auto_20150306_1817.py
temba/flows/models.py
temba/flows/tests.py

There was an optimization for expiring large batches of runs that wasn't being exercised in the test and (surprise!) had a bug. This makes the test more robust and fixes the big. Also includes a migration to update the active sets by removing any expired runs.

Make sure runs are removed from active sets when they are expired

---

temba/contacts/models.py

Two bits to this:
1) Move the common case of looking up a contact from a single URN to before the Lock and optimize for that case
2) Move the calculation of group updates and event updates (triggered by name / urn updates) to outside the lock, this should remove the lock bottleneck when there are a large number of dynamic groups or campaigns

optimize common case of getting single contact from single urn

---

temba/api/serializers.py
temba/api/tests.py
temba/api/views.py
temba/flows/models.py

Flow definition is provided via optional definition field. Being optional you can update a flow's properties without providing the full JSON definition. For example to update an existing flow...
```json
{
"uuid": "56811758-C8EE-494C-B3CC-FD92A85E49CA",
"name": "Test Flow",
"flow_type": "F",
"definition": { "action_sets": ... }
}
```
Writing is not included in user facing documentation for now.

Allow writing to flows API endpoint

---

temba/api/tests.py
temba/api/views.py

API docs already claim you can search by `id`

Small fix for fetching messages by id in the API

---

static/coffee/analytics.coffee
temba/contacts/models.py
temba/flows/models.py
temba/flows/views.py
templates/flows/ruleset_analytics.haml

The main index page for analytics was doing a ton of super expensive queries, just to show the lists of rulesets in various orders.
This removes those and just shows the most recent and active flows, along with a simple list of all the categories.
Also a few other optimizations on queries and not using caches.

Simplify queries on main analytics page to speed it up

---

temba/contacts/models.py
temba/flows/views.py
temba/utils/__init__.py
temba/utils/tests.py
temba/values/tests.py

Uses our much faster (and cached) Value summary method to calculating Choropleth results in analytics. Now it is basically just reformatting those results in the view instead of doing slow calculations.
Also fixes us going to the db for each group to calculate whether there are contacts in it by using the cache instead.

Use our optimized value summary call for choropleth

---

media/test_imports/flow-starts.json
temba/flows/models.py
temba/flows/tests.py

On flow starts, we were using a single list of the previously started flows to prevent loops from happening, instead of one list per contact.

Fixes flow starts that span more than one contact and more than one flow

---

temba/api/tests.py
temba/api/views.py

Removes duplicates when querying with multiple labels

Added .distinct() to messages api endpoint 

---

temba/api/views.py

Problem here was that we initialize cached values as dynamic attributes for contacts in the paged queryset, but when the serializer is serializing the object_list field of the page object, it calls all() to extract the contact items... and of course that generates a new queryset with different contact objects. Converting page.object_list to a list avoids this.

Ensure caching is used for contact fetching over the API

---

.travis.yml

This enables the karma test runner and fixes crypto error we were seeing on builds.
Builds fail appropriately for the karma runner and coverage metrics are taken. Coverage results are not reported to coveralls. It looks like coveralls needs the coverage to be merged and I'm not sure that's something we want to do.

Enable javascript tests

---

media/test_flows/color_gender_age.json
temba/api/tests.py
temba/api/views.py
temba/contacts/migrations/0001_initial.py
temba/contacts/migrations/0017_remove_contact_fields.py
temba/contacts/models.py
temba/contacts/tests.py
temba/flows/tests.py
temba/settings_common.py
temba/tests.py
temba/utils/__init__.py
temba/values/models.py
temba/values/tests.py

Adds the ability to segment results by a contact field by passing in the values you want to segment by. (this addresses my primary concern on performance as it is now no worse than ruleset segmenting)
Also get rid of HSTORE and ```fields``` field on Contact as these were unused.

Add ability to segment results by contact field

---

pip-freeze.txt
temba/api/tests.py
temba/channels/views.py
temba/formax.py

This makes a few concessions for accounts that have a huge # of messages so that we can display them in a reasonable amount of time. Namely, we don't display IVR counts for accounts with over 1M messages and we use a rough estimate of total messages instead of doing a real count.
Both of these should be removed when we start using triggers as they can both be tracked that way then.

Faster channel read

---

pip-requires.txt
temba/api/views.py

This is due to them not being able to change their config to not send back responses with our responses. Doh.

Return emptry strings when Blackmyna delivers messages or status updates

---

temba/flows/models.py
temba/flows/tests.py
temba/orgs/tests.py

Just like it says. We weren't carrying forward expiration settings on export/import or on flow copy.

Maintain expiration on import and copy

---

temba/orgs/tests.py
temba/temba_email.py
templates/orgs/email/invitation_email.html
templates/orgs/email/invitation_email.txt

* Fixed text version of org invitation email
* Switch invitation emails to use branding.link so that they use correct URL on staging server
* Made it easier to test emails by extracting a send_multipart_email function

Email fixes

---

temba/campaigns/models.py
temba/campaigns/tasks.py
temba/campaigns/views.py

Primary change is instead of looking up all contacts and then value for each of those contacts as separate queries we lookup all values for the list of contacts in a single query. Also creates the event fires as a bulk insert instead of individual creates.
Definitely noticed some goofiness where we turn dates into strings and then back into dates which is accounting for timezones. Didn't want to mess with that just yet, so its maintained here.

Optimization for eventfire creation

---

temba/api/views.py
temba/channels/models.py
temba/channels/tasks.py
temba/msgs/models.py
temba/msgs/tasks.py
temba/msgs/tests.py
temba/orgs/tests.py

We now use segment.io event counts/events to track msg failures, errors and sends so we can track message states in a more performant way.

Remove total metric counts that are too slow, add latency metrics

---

temba/api/serializers.py
temba/api/tests.py

For when users do https://app.getsentry.com/nyaruka/rapidpro/group/67345152/

Passing empty string for parent to label API endpoint should act same as not passing it

---

karma/flows/test_services.coffee
static/coffee/flows/services.coffee

This lets you extend actionsets which don't send messages.

Don't require actionsets to send messages to be extended

---

static/coffee/flows/services.coffee
static/less/flow_editor.less
temba/flows/tests.py
temba/flows/views.py
templates/partials/modal.haml

While flows can no longer be saved with known invalid cycles (thanks to server side evaluation), that information was not presented to the user.
* View catches FlowException when saving flows and sends back json error
* Show error dialog when json error is received
* Embed error in the UserVoice widget so it is transparently provided to support team
We should be catching any errors before sending them to the server, but this is a far better experience if there are cases we miss (or are broken for one reason or another).

Show an error dialog when flow saves fail

---

temba/orgs/models.py
temba/orgs/tests.py

Addresses the problem that orgs who are considered pros (>100,000 credits) are losing their status when their big topups expire.
We now base this on total # of credits "purchased"

Dont expire pro accounts when their big topups expire

---

media/test_flows/non_blocking_rule_first.json
temba/flows/models.py
temba/flows/tests.py

This is the maintain behavior where flows starting with non-blocking rulesets with webhooks would still have their webhooks triggered.

Force webhook execution at the beginning of flows

---

temba/api/serializers.py
temba/api/tests.py
temba/msgs/models.py
temba/msgs/tests.py
temba/msgs/views.py

* Bulk actions endpoint will ignore ids of outgoing messages
* Removed archive as an action from Failed messages view
* Reworked unit tests that were labelling outgoing messages

Restrictions on archiving and labelling messages

---

temba/contacts/models.py
temba/contacts/tests.py
temba/flows/models.py

This fixes a problem where it was possible for a test contact to lose its URN and then no longer work properly. That was caused by the bug in get_test_contact(), but we now also make sure test contacts always have a unique URN before we hand them back.

Fix case where test contact's URN was reassigned

---

temba/contacts/views.py

Order contacts by reverse pk (aka, reverse chronological)

---

templates/flows/ruleset_analytics.haml

1.2 changed the behavior of how ng-show works which broke redraws and events on our maps. Switching to ng-if restores the behavior.

Fix angular maps not display due to 1.2 change

---

temba/flows/models.py
temba/flows/templatetags/__init__.py
temba/flows/templatetags/rules.py
temba/flows/tests.py
temba/flows/views.py
temba/locations/models.py
temba/locations/tests.py
temba/locations/views.py
temba/msgs/migrations/0014_labels_to_folders.py
temba/msgs/migrations/0017_install_label_triggers.py
temba/msgs/models.py
temba/msgs/tests.py
temba/msgs/views.py
temba/orgs/context_processors.py
temba/orgs/models.py
temba/orgs/tests.py
temba/orgs/views.py
temba/settings_common.py
temba/tests.py
templates/campaigns/campaign_list.haml
templates/campaigns/campaign_read.haml
templates/campaigns/campaignevent_read.haml
templates/flows/flow_filter.haml
templates/flows/flow_list.haml
templates/flows/flow_versions.haml
templates/includes/nav.haml
templates/triggers/trigger_list.haml

Instead of doing the rather expensive query of figuring out if there are new inbox or flow messages since the user last visited the org, we now use a redis to increment a count as those things occur.
Redis is good for this because none of these matter so much, these are just hints to the user.

Use redis to keep track of unread msgs and incoming flow msgs

---

temba/contacts/migrations/0020_exportcontactstask_is_finished.py
temba/contacts/models.py
temba/contacts/tasks.py
temba/contacts/tests.py
temba/contacts/views.py
temba/flows/migrations/0022_exportflowresultstask_is_finished.py
temba/flows/models.py
temba/flows/tasks.py
temba/flows/tests.py
temba/flows/views.py
temba/msgs/migrations/0021_exportmessagestask_is_finished.py
temba/msgs/models.py
temba/msgs/tasks.py
temba/msgs/tests.py
temba/msgs/views.py

Adds ```is_finished``` on all export tasks and tracks when they are complete. Also disallows the creation of new exports until the previous exports are actually complete.

Only allow one export per type per org at a time so people don't melt us

---

temba/channels/models.py
temba/channels/tests.py
temba/channels/views.py

Fixes the case that World Relief (DE) has been running into, that their device was reporting DE as a country but they were registering with a number in a different place. We now let the phone number of the channel take precedence when determining whether they are adding a channel in the same country as their other orgs.

Let channel phone number take precendence for channel country

---

temba/orgs/tests.py
temba/orgs/views.py

We weren't allowing admins from removing themselves from orgs if there was more than one admin on it. This fixes that.

Allow admins to remove themselves from orgs

---

temba/api/tests.py
temba/channels/models.py
temba/channels/views.py

Lets users use one of the Africa's Talking shared shortcodes.. this basically is just a flag set when connecting that then changes our send format a bit.

Allow use of shared shortcodes on AfricasTalking

---

temba/api/serializers.py
temba/api/tests.py

.. when it's required (i.e. action = label or unlabel) or provided when it's not used.
Rather than blowing up with a 500.

Message actions endpoint should raise validation error if label not provided

---

static/coffee/flows/widgets.coffee

Use the completion variables in Flow service instead of in $rootScope.
Fixes rapidpro/rapidpro/issues/187

Group variables

---

temba/flows/migrations/0025_create_flow_expiration_index.py
temba/flows/models.py
temba/flows/tasks.py
temba/flows/tests.py

- Creates conditional index for managing flow expirations
- Use 1000 flowrun batches during expiration so we don't acquire gigantic DB locks.
- Add lock to task so we don't walk over ourselves on large expirations

Add index for flow expirations, expire flows in batches

---

karma.conf.coffee
karma/flows/test_controllers.coffee
package.json
static/coffee/flows/controllers.coffee
static/coffee/flows/directives.coffee
static/coffee/flows/widgets.coffee
templates/flows/flow_editor.haml

* Allow localized flows to be viewed in orgs without a primary language set
* Remove explicit cache avoidance for partials
* Add FlowController testing
* Use ng-html2js in karma to hack in loading of partials to test modals

Language fixes

---

temba/api/tests.py
temba/api/views.py

E.g. https://app.getsentry.com/nyaruka/rapidpro/group/73800036/

Fixed API count caching when query params include non-ascii chars

---

temba/channels/migrations/0021_auto_20150803_1857.py
temba/channels/models.py
temba/channels/tests.py
temba/perf_tests.py

Switches to using INSERT and DELETE operations and squashing counts every ~100 inserts or so.

Move ChannelCount triggers to using an insert/delete approach

---

temba/flows/models.py
temba/flows/tests.py
temba/perf_tests.py
temba/utils/profiler.py

Biggest wins were that the "MemorySavingQuerySet" was actually refiring the rather expensive query every 1000 records.. we now cache the ids and load 1,000 records at once which is a huge savings.
Also optimized the select_related and prefetch_related so that we only do two queries per batch of 1,000.
Sum results is we should be able to do 600k exports in ~30mins with much more friendly DB characteristics.

Various optimizations that make flow exports 10x faster

---

temba/api/channels.py
temba/api/tests.py
temba/campaigns/tests.py
temba/msgs/tasks.py

Turns out clickatell sends their timezone-less timestamps as GMT+2.. ya, that makes sense.
Also wedged in some tweaks to the tasks for handling trigger events and messages, that we weren't checking for the lock was causing our workers to stack up when things went sideways. (like when redis runs out of room as it did earlier)

Fix timezone for clickatell, tweaks to event firing

---

temba/api/tests.py
temba/channels/models.py

Silly bug around using index() instead of find() was causing us to incorrectly log cases where Twitter returned 403's that weren't due to the contact not following us.

Fix twitter channel log description when failing

---

temba/settings_common.py

See: https://github.com/celery/celery/issues/2741
Did some digging and pretty sure the occasional celery hang is due to our redis connections having a hiccup and celery not recovering. Looks like this timeout should fix that.

Add timeouts for redis connections in celery

---

temba/api/tests.py
temba/api/views.py
temba/perf_tests.py

* Prefetch step messages to avoid repeat fetches
* Use subqueries to filter by flow and contact where possible to avoid large joins

Optimizations for the runs endpoint

---

temba/api/models.py
temba/api/tests.py
temba/orgs/tests.py
temba/utils/cache.py
temba/utils/tests.py

Removes ~50 db hits from the API explorer page where it is repeatedly referenced in the template.

Cache a user's API token to avoid repeat DB hits

---

temba/flows/migrations/0028_populate_flowrun_orgs.py
temba/flows/migrations/0029_populate_run_modified_on.py

These two rather long data migrations take care of populating both orgs on flow runs and modified_on.

Populate flowrun orgs and modified_on

---

temba/api/tests.py
temba/channels/models.py
temba/channels/tests.py
temba/channels/views.py

Since a lot of aggregators use Kannel and a lot of aggregators aren't terribly good at configuring SSL, give the option of ignoring verification on SSL certs.

Allow Kannel connections to not verify SSL certificates

---

media/test_imports/farmers.csv
temba/campaigns/models.py
temba/campaigns/tasks.py
temba/campaigns/tests.py
temba/campaigns/views.py
temba/contacts/models.py
templates/campaigns/campaign_read.haml

* Check when updating a campaign if the group changes, if so update it's fires
* Remove any unfired fires when deleting a group
* Run update fires for campaign in celery
* Don't show inactive groups on campaign read page

Update event fires properly on campaign group changes

---

temba/flows/migrations/0031_auto_20150901_2345.py
temba/flows/models.py
temba/flows/tests.py
temba/ivr/tests.py
temba/tests.py

Marks runs as inactive as soon as they reach a terminal node or have a non-matching ruleset.

Finish flows immediately

---

temba/api/tests.py
temba/channels/models.py
temba/contacts/models.py

When Twitter returns 403/404, contact should be failed permanently 

---

temba/orgs/models.py
temba/orgs/tests.py

Prevents us having to sum all the credit_used rows for every credit assignment.

Cache active topups

---

temba/channels/migrations/0022_update_maybe_squash.py
temba/orgs/migrations/0008_update_maybe_squash.py

Our every 100 inserts squash was too often and causing contention during blasts.
This is probably a temporary fix, I need to figure out how we can do a database lock of some sort during the squash to make this absolutely foolproof but should help in the meantime.

Squash credits and channel counts every 1,000 inserts

---

temba/settings_common.py

Two changes here:
1) Add our PERMISSIONS_APP for smartmin. Not sure how this wasn't there before, but this will speed up the permission check 10-fold.
2) Allow local test runs to skip the migrations (instead relying on current model state of the world like old syncdb used to). The test suite still runs all migrations. Since this is only needed until Django 1.8, I just piggy-backed on the --failfast command for nose.
With both of these changes, my single test run went from 3:30 to 0:14, so ~16x faster.

Speed up test failure cycle

---

karma/flows/test_services.coffee
static/coffee/flows/controllers.coffee
static/coffee/flows/services.coffee
temba/flows/models.py
templates/partials/split_editor.haml

Remove "base" properties in flow definitions in preparation for removing non-localized flow format. Also fixes flash of errors in rule editor when closing the dialog.

Remove base turds

---

temba/api/tests.py
temba/channels/models.py

This might help with being throttled by Twitter since we'll be sending half the # of messages.

Up twitter DM limit to 10k chars

---

temba/orgs/tests.py
temba/orgs/views.py
temba/settings_common.py
templates/orgs/org_surveyor.haml

Adds a placeholder for users that are invited as surveyors. This page is shown if they accept an invite as a surveyor or login for an org for which they are a surveyor.

Reroute surveyor users to download page

---

temba/contacts/models.py
temba/flows/models.py
temba/flows/tests.py

SaveToContact action was doing the wrong thing when users select Phone Number as the field. It used to create a contact field instead of updating the urns accordingly.

Fix phone number updates

---

temba/api/tests.py
temba/api/views.py

File under: Terrible ideas
Can't find evidence of anyone using this besides CasePro (which no longer does): https://logentries.com/app/d6f114f1#/logs?f=1440840240000&t=1443432240000&log_q=where(api%20AND%20messages%20AND%20reverse%20NOT%20casepro)

Removed reverse param to messages endpoint

---

temba/api/serializers.py
temba/api/tests.py

Allow the creation of empty contacts via the api. This is necessary for surveyor which will potentially later fill the contact out with actions inside a flow allowing us to remove the screen asking for name and phone number before launching a flow.
@rowanseymour

Naked contacts

---

temba/api/tests.py
temba/nexmo.py
temba/utils/gsm7.py
temba/utils/tests.py

Nexmo doesn't detect this on our own, so we have to.

Detect non-gsm7 messages and send as unicode on nexmo

---

temba/channels/migrations/0024_auto_20151002_1407.py
temba/msgs/migrations/0032_auto_20151002_1411.py
temba/orgs/migrations/0010_auto_20151002_1417.py

This should avoid any possibility of deadlocks doing these counts. Have to love the #postgres channel.

Obtain locks for squashing counts to prevent deadlocks

---

temba/api/views.py
temba/contacts/models.py
temba/contacts/tests.py

* Fixed `ContactField.get_or_create` when label is not specified 
* Flow definition API endpoint docs tweak

Little fixes

---

temba/values/models.py

This basically does the filtering client side instead of through the query, which ends up being a lot faster as the query itself becomes gigantic. (instead of sending 1M run ids, our query is simple and the result is roughly the same size)

Optimization to speed up result calculations for large orgs

---

temba/flows/models.py

On Nigeria starts, we are starting to run into memory contention as we load all 1.3M contact records into ram to create the the flow start batches. This uses ".only" to only grab is_test and pk, which should help quite a bit on that front.

Only grab pk and is_test as that is all that is needed

---

temba/api/serializers.py
temba/flows/flow_migrations.py
temba/flows/models.py
temba/flows/tests.py

Fix ensure_current_version to pass the proper to_version number. Also don't migrate forward for version 7 if there is no definition in the block.

Fix ensure_current_version

---

media/test_flows/malformed_single_message.json
temba/flows/flow_migrations.py
temba/flows/models.py
temba/flows/tests.py

Fix for issue migrating single message flows:
https://app.getsentry.com/nyaruka/textit/group/87968947/
These were created with 'rulesets' instead of 'rule_sets' (although they were always empty). We now tolerate it in all previous migrations and fix it in version 7.

handle malformed single message flows during migration

---

temba/api/migrations/0005_apitoken_role.py
temba/api/models.py
temba/api/tests.py
temba/api/views.py
temba/orgs/models.py
temba/settings_common.py

Add new property ```APIToken.role```. 
* Migrate current tokens to have role based on user group for org
* Apply role when generating new tokens
* Require role when authenticating against the api
* Take role into account with authenticating with token

Auth tokens

---

static/coffee/flows/app.coffee
temba/assets/models.py
temba/assets/tests.py
temba/assets/urls.py
temba/assets/views.py
temba/channels/models.py
temba/contacts/migrations/0024_exportcontactstask_uuid.py
temba/contacts/models.py
temba/contacts/tests.py
temba/contacts/views.py
temba/flows/migrations/0036_auto_20151014_1703.py
temba/flows/models.py
temba/flows/tests.py
temba/flows/views.py
temba/msgs/migrations/0033_exportmessagestask_uuid.py
temba/msgs/migrations/0034_move_recording_domains.py
temba/msgs/models.py
temba/msgs/tests.py
temba/msgs/views.py
temba/orgs/models.py
temba/orgs/views.py
temba/settings_common.py

This moves to naming files with UUIDs for exports as well as using 301 redirects for downloads so we don't time out trying to download large files before serving to nginx.

Redirect asset downloads

---

karma/flows/test_services.coffee
static/coffee/flows/services.coffee

Fixes issue with form_field ruleset type not getting a proper operand when created by the editor. Issue is due to client side slugging only replacing once.

Fix slugging to replace all bad characters

---

temba/api/tests.py
temba/api/views.py

Fixes https://app.getsentry.com/nyaruka/textit/group/89200237/

API Requests should return 403 if no org rather than throw exception

---

temba/api/__init__.py
temba/api/serializers.py
temba/api/tests.py
temba/api/views.py
temba/contacts/models.py
temba/contacts/tests.py
temba/settings_common.py

* ContactGroup.update_contacts now prevents adding of blocked contacts to groups
* Contact bulk actions endpoint errors if any passed UUIDs are invalid (or test contacts)
* Contact write endpoint validates that a blocked contact isn't being added to a group
* Added REST framework exception handler so that API calls don't return the html error page
* Simplified `Contact.release()`

Better contact related errors

---

temba/channels/tests.py
temba/channels/views.py

Allows users to edit the address for a Nexmo channel after they have added it.
This lets people change the "from" for Nexmo channels to a alphanumeric string instead of always enforcing strings. Obviously that only works in some countries, but is still useful.

Allow nexmo channels to set their address

---

temba/api/__init__.py

Fixes previous change which captures exceptions during API requests so that we don't return an HTML page.

Ensure exceptions from API requests still go to Sentry

---

temba/api/__init__.py

So you don't end up with lots of emails with just "Exception in API request" in the title

Include exception message in log message when handling API request exceptions

---

media/test_flows/call-channel-split.json
temba/api/channels.py
temba/api/models.py
temba/api/tests.py
temba/channels/models.py
temba/contacts/tests.py
temba/flows/models.py
temba/flows/tests.py
temba/flows/views.py
temba/msgs/models.py
temba/msgs/tests.py
temba/triggers/handlers.py
temba/triggers/models.py
temba/triggers/tasks.py
temba/triggers/tests.py
temba/triggers/views.py

We weren't passing any kind of message to flows triggers by missed calls, which makes it impossible to split your behavior based on the channel passed in. A bigger refactor might be needed later to change to passing in channel AND msg to flows, but in the meantime I created a mock Msg wrapper that contains that information. (which we do elsewhere)
Touched some pieces in Trigger and Call and decided to move the various TYPE constants into the Classes themselves.
+unit test.

Missed call channels

---

karma/flows/test_controllers.coffee
static/coffee/flows/controllers.coffee
temba/flows/models.py
temba/flows/tests.py
templates/partials/action_editor.haml

* Nullify contact language if attempting to set to invalid language (not three letter iso code)
* Don't show "Default" as an option in the editor
* Show current language in action if not an org language in the editor

Fixes for SetLanguageAction

---

temba/api/v1/views.py
templates/partials/action_editor.haml
templates/partials/split_editor.haml

Always arriving at the page you expect when you click on a link is a premium feature... so this a feature change rather than bug fix. That code was certified.

Fixed webhook URLs

---

pip-freeze.txt
pip-requires.txt
temba/channels/models.py
temba/channels/views.py
temba/contacts/models.py
temba/flows/models.py
temba/msgs/models.py
temba/msgs/tasks.py
temba/orgs/tests.py
temba/settings_common.py
temba/urls.py
temba/utils/analytics.py

This moves to using the direct librato API for our high frequency events instead of going through segment.
Had to write a new library for librato (https://github.com/nyaruka/python-librato-bg) to support async recording of events, as otherwise these would block calling up to librato for every event. (this was essentially cribbed from segment.io's method)
I added a new call to analytics for the new type of 'analytics', which is a 'gauge' in librato speak.

Move to firing directly against librato for high frequency events

---

media/test_flows/no_base_language_v8.json
media/test_flows/non_localized_ruleset.json
media/test_flows/non_localized_with_language.json
temba/flows/models.py
temba/flows/tests.py

There's some bogus export files out there floating around. How they were created is unclear, but currently we are allowing them to come back into the system in their malformed state. This PR adds a little extra validation to the flow definition post migration to make sure that we have wellformed localization.

Validate exports

---

temba/msgs/tasks.py
temba/urls.py

This makes sure librato is initialized before our workers boot up.

Fix celery analytics by hooking into worker_ready signal

---

pip-freeze.txt
temba/flows/models.py
temba/flows/tests.py

If substituting a variable like `@extra` which is a container, and it has no default value, dump it as JSON.

Render evaluation context branches as JSON

---

temba/schedules/models.py
temba/schedules/tests.py
temba/schedules/views.py
temba/settings_common.py

Simplify date math on calculating next fire to not impose timezone, instead deferring to timezone aware datetime. Add more unit tests on date calculation across day boundaries.

Fix for scheduled messages near day boundaries

---

temba/contacts/templatetags/contacts.py
temba/contacts/tests.py
temba/contacts/views.py
templates/contacts/contact_history.haml
templates/contacts/contact_read.haml
templates/msgs/msg_send_modal.haml

Some tweaks to the contact history:
* Use the last 100 messages to determine the window for events. 
* Give feedback on initial load.
* Don't show more button if there aren't any more messages
One unfortunate side effect is that this will hide any events that occurred before the first message and will also not surface events that have occurred since the last message.
The bonus is that its a far nicer user experience for the vast majority of cases.

Contact History Tweaks

---

temba/contacts/tests.py
temba/contacts/views.py

Event sorting was wrong for upcoming events, reverse() on querysets is of course not the same as reversed(). Now we slice from the queryset first and run that through reversed().

Fix order of upcoming events on contact history

---

pip-freeze.txt

Adds fix for float values in the context. Previously it was assumed that every float value was a Decimal instance, but `@extra` can end up with floats.

Update expressions dependency to 1.1.5

---

temba/api/tests.py
temba/settings_common.py

REST framework 3 by default puts unicode chars in responses as they are, e.g. "x سلم" where as v2 would encode them, e.g. "x \u0633\u0644\u0645". This change restores the old behaviour.

REST framework should encode unicode chars in JSON

---

temba/channels/models.py
temba/channels/tests.py
temba/channels/views.py

Telcel SMSC in MX won't accept MT messages with a full international number.

Allow configuring kannel channels to send messages using national format

---

temba/msgs/migrations/0039_auto_20151204_2238.py
temba/msgs/models.py

This just adds a NullBooleanField for the purged field so we can push this and update it in a non-blocking way in a future migration.

Purge Stage I

---

temba/flows/tests.py
temba/flows/views.py

Properly check for search flag when searching against anonymous orgs with nameless contacts.
Addresses this ticket:
https://textit.uservoice.com/admin/tickets/2466/

Fix missing flow results on nameless contacts

---

temba/api/tests/test_v1.py
temba/api/v1/serializers.py

Users should still be able to update contacts on anon orgs by uuid.
@rowanseymour plz review

Allow updating of contacts on anon orgs by uuid

---

temba/api/v1/serializers.py
temba/api/views.py
temba/campaigns/models.py
temba/contacts/models.py
temba/flows/models.py
temba/flows/tests.py
temba/triggers/models.py
temba/triggers/views.py

Fixes a bug where someone was using a webhook result with a trailing space "Lahora ", and we were failing the lookup, but then creating a new group every time.
This adds a few methods to normalize names and normalize the looking up a group by name.

Fix add to group action to strip group name before trying to look up

---

temba/api/tests/test_v1.py
temba/campaigns/tests.py
temba/contacts/models.py
temba/contacts/templatetags/contacts.py
temba/contacts/tests.py
temba/contacts/views.py
temba/orgs/tests.py
temba/settings_common.py
templates/contacts/contact_read.haml
templates/contacts/contact_update.haml

First step in allowing "user as contact" in Surveyor.
* Add mailto scheme support for ContactURN
* Allow creation of URNs when editing contacts
* Move contact field editing to its own dialog
* Show email urns (linked with mailto)
* Link twitter urns to twitter profile
* Add coverage for contacts/views.py and contacts/models.py
Relevant screen shots:

Email URNs

---

temba/contacts/search.py
temba/contacts/tests.py

We weren't defining the lexer quite right for reserved words..
See "specification of tokens" here:
http://www.dabeaz.com/ply/ply.html#ply_nn4

Fix reserved words matching prefixes of field names

---

temba/api/v1/serializers.py
temba/channels/handlers.py
temba/flows/models.py
temba/flows/tasks.py
temba/flows/tests.py
temba/ivr/models.py
temba/ivr/tests.py
temba/perf_tests.py
temba/values/tests.py

When users start a large group into a flow that was mostly already started, determining the remaining contacts caused the flow start to fail. This switches to the use of contact_ids throughout flow start and eliminates a large exclusion query.

Handle large flow restarts

---

temba/channels/handlers.py
temba/channels/tests.py

follow up  #525 to properly handle receiving from Clickatell 
When receiving from Clickatell with encoding ISO-8859-1,
we decode that ignoring missing characters and we encode to utf-8 before saving
FIxes https://app.getsentry.com/nyaruka/rapidpro/issues/109283753/

re-encode back to utf-8 when receiving from clickatell latin-1

---

temba/api/support.py
temba/api/tests/test_v2.py
temba/api/v2/views.py

* Added convenient mechanism for list endpoints to enforce mutually exclusive params
* Don't allow combining contact with other filters on messages endpoint
* Don't allow both contact and flow on runs endpoint
* Fixed format of error response when exception thrown from get_queryset
* Don't return deleted messages from messages endpoint
* Added missing id params on read explorers
* Moar tests

Some more API v2 tweaks

---

temba/contacts/migrations/0029_norm_twitter_urns.py
temba/contacts/models.py
temba/contacts/tests.py

- Twitter URN normalization should make handles lowercase
- Removes Twitter URN duplicates
- Converts all existing ones to lowercase

Twitter handles aren't supposed to be case-sensitive

---

temba/flows/models.py
temba/flows/tests.py
temba/flows/views.py
temba/triggers/tests.py

Fix definition for join trigger flows to be:
* Properly localized
* Use rule_sets instead of rulesets
* Use new expression syntax instead of filters
Old revisions that don't pass validate_flow_defintiion are hidden from the user so they cannot be restored. Existing broken flows patched by hand, no migration.

Fix join trigger flow

---

temba/api/models.py
temba/flows/models.py
temba/flows/tests.py

When we reach webhooks that have keys that have spaces, or other characters that won't work in our variable replacement, this replaces those chars with _ (one for each).
This also enables webhook calls in returning lists instead of just dicts as we did previously.

Webhook fields

---

static/less/flow_editor.less
static/less/style.less
temba/flows/models.py
temba/flows/tests.py
temba/flows/views.py
templates/flows/flow_editor.haml
templates/flows/flow_list.haml
templates/flows/flow_update.haml

Lets flow designers show how survey flows create contacts.
* Add form option for how contacts are created on Surveyor
* Switch icon marking surveys to be a smartphone instead of android
Add new optional entry in flow definition (without advancing version). Open to alternate naming here.
```
"metadata": {
"contact_creation": ([run] | [login])
}
```

Survey contact creation

---

temba/contacts/models.py
temba/contacts/tests.py

No urn scheme paths are case-sensitive

Lowercase all urn paths during normalize

---

temba/schedules/migrations/0002_schedule_repeat_minute_of_hour.py
temba/schedules/models.py
temba/schedules/tests.py
temba/schedules/views.py
temba/triggers/views.py

Adds repeat minute field on schedules, which is pulled out when creating schedules and used going forward.
Existing schedules will continue to work as they have (resetting minute to 0) but any set minutes going forward will do the right thing. (this only affected repeating schedules after the first fire)

fix drifting minutes on schedules

---

temba/api/tests/test_v2.py
temba/api/v1/serializers.py
temba/api/v2/views.py
temba/campaigns/models.py
temba/campaigns/tests.py
temba/campaigns/views.py
temba/channels/models.py
temba/flows/models.py
temba/flows/tasks.py
temba/flows/tests.py
temba/flows/views.py
temba/orgs/views.py
temba/triggers/models.py
temba/triggers/views.py
temba/values/models.py
templates/flows/ruleset_analytics.haml

We currently allow users to delete flows from the editor page. Right now this does a full delete, removing all flows, revisions, starts, etc.. due to cascading deletes. (ironically not Values even though they are rendered unreachable)
This tends to time out on flows with lots of runs as it is done in the web request.
This adds a new ```release()``` method to Flow, that does the following:
* sets ```is_active``` to False
Then starts a celery task to:
* remove all flow steps
* remove all value objects
* clears caches in redis
* this does NOT clear out runs, because I think those are worth keeping around for auditing purposes.. it also keeps flow revisions and flow starts for the same reasons

Add release() method to Flow, call when deleting

---

temba/api/tests/test_v2.py
temba/api/v2/views.py

Avoids slow queries... possibly from weird query planning on Postgres's part
The queryset for fetching a "page" of messages by a label is essentially...
```python
test_contacts = Contact.objects.filter(org=org, is_test=True)
Msg.all_messages.filter(org=org, labels=law).exclude(visibility='D').exclude(msg_type=None).exclude(contact__in=test_contacts).order_by('-created_on')[:251]
```
Which becomes...
```sql
SELECT "msgs_msg".* FROM "msgs_msg" 
INNER JOIN "msgs_msg_labels" ON ( "msgs_msg"."id" = "msgs_msg_labels"."msg_id" ) 
WHERE (
"msgs_msg"."org_id" = 289 
AND "msgs_msg_labels"."label_id" = 268 
AND NOT ("msgs_msg"."visibility" = 'D') 
AND NOT ("msgs_msg"."msg_type" IS NULL) 
AND NOT ("msgs_msg"."contact_id" IN (SELECT U0."id" FROM "contacts_contact" U0 WHERE (U0."is_test" = True AND …
```

Fetch test contacts in separate query when filtering messages and runs on API v2 endpoints

---

temba/channels/handlers.py
temba/channels/tests.py

Apparently M-Tech sends these when DLR requests expire, not just when messages fail. Vumi wants us to ignore these until they sort their shit out.

Ignore failed DLRs from Vumi

---

temba/contacts/models.py
temba/contacts/tests.py

It was decided that administrators on organizations should be allowed to import contacts, even if those URNs already exist in the db.

Allow admins to import into anonymous orgs

---

temba/channels/tests.py
temba/channels/views.py
temba/settings_common.py
templates/contacts/contact_history.haml

Allows CS users to view channel logs on anon orgs to help with debugging.

Allow CS reps to view channel logs

---

static/coffee/flows/app.coffee
static/coffee/flows/services.coffee
static/less/style.less
temba/flows/flow_migrations.py
temba/flows/tests.py
templates/partials/action_editor.haml

Three quick fixes, not really testable..
* Remove select2 turd when toggling options in flow editor
* Don't say people will return to this flow for start flow action
* Don't show the drag helper if the node is already connected
Also a fix for a sentry error on flow migrations:
https://app.getsentry.com/nyaruka/textit/issues/119742419/

Quick fixes on the flow editor

---

media/test_flows/ivr_call_redirect.json
temba/flows/models.py
temba/ivr/migrations/0004_auto_20150129_1727.py
temba/ivr/migrations/0008_ivrcall_parent.py
temba/ivr/models.py
temba/ivr/tests.py
temba/ivr/views.py

Update so that using the StartFlowAction in a voice flow will use the Twilio redirect verb to route to the new flow without forcing a hangup.

Voice flow redirects

---

media/test_flows/text_trigger_ivr.json
temba/flows/models.py
temba/ivr/tests.py

Fix for text flows triggering ivr flows that was introduced yesterday. Only redirect if both the parent and the child flows are voice flows in  ```StartFlowAction```.

Fix text flow triggering ivr

---

temba/contacts/search.py
temba/contacts/tests.py

So even with help from @ericnewcomer, couldn't find a way to implement this without using a subquery. Tested on Nigeria with a field with values for 2/3 of the contacts and it was 30-90 seconds which isn't much worse than any field query on that org.

Contact searching by empty field value

---

temba/contacts/models.py
temba/flows/migrations/0052_auto_20160405_1401.py
temba/flows/models.py
temba/flows/tests.py
temba/flows/views.py
temba/utils/models.py
templates/flows/flow_export_results.haml
templates/flows/flow_list.haml

Allows users to add up to 10 contact fields as part of their export, select to export only results for people who have responded, and to leave out the individual runs and msg tabs if they'd like.

Flow export improvements

---

temba/contacts/tests.py
temba/contacts/views.py

Turns out if you created a group with the same name as an existing group, we overwrite the contacts on the old group, essentially hijacking the id for the new group.
The big problem here is that people could change a non-dynamic group to a dynamic one, which would then render things like "add to group" and "more from group" invalid in flows as they are now referencing a dynamic group instead of a static one.

Fix bug where users could overwrite groups

---

pip-freeze.txt

Found the reason MMS fails on the production but not locally was I'm using a current version of the requests lib. There's been a myriad of fixes to how it handles authentication since version 1.2.3.

Upgrade requests

---

temba/msgs/migrations/0037_backfill_recipient_counts.py

This blew up when I was migrating an old db dump

Fix migration to use standard object manager

---

temba/msgs/migrations/0054_auto_20160426_2130.py
temba/msgs/migrations/0055_auto_20160427_1937.py
temba/msgs/models.py
temba/msgs/tests.py

We now have a recipients m2m that keeps track of all the URNs that a broadcast sent to. These are populated as messages are created so will be kept in sync.
This also takes care of backfilling all past broadcasts in a super mega migration that will need to be run outside a ship.

Adds recipients to Broadcasts

---

temba/utils/gsm7.py
temba/utils/tests.py

Deals with people copy/pasting special chars from Word docs. On Kannel instances (where GSM7 vs Unicode tends to matter most) these will be replaced if the Channel policy supports it.

Replace crazy characters inserted by word in GSM7 messages

---

media/test_flows/two-in-row.json
temba/channels/tasks.py
temba/flows/models.py
temba/flows/tests.py
temba/msgs/models.py
temba/orgs/models.py

Another attempt at making sure our distributed sending machine doesn't get out of order in sending.
This makes a few relevant changes:
1. We gather all messages to send at once when executing a flow step, even if that spans across actions.
2. We no longer pause when adding things to the queue because that was probably ineffective as the tasks were waiting to fire until the transaction was committed, instead we lock on the contact when sending so that in theory no two tasks should be sending to the same contact at once.
2) does depend on the implicit race to the lock being fair, that is that the first msg added to our queue grabs the lock before the second when there are consecutive messages. I could certainly envision scenarios where that wouldn't be the case though. (say if one box is …

Msg ordering

---

temba/api/models.py
temba/api/tests/test_models.py
temba/api/tests/test_v2.py
temba/api/v1/views.py
temba/api/v2/views.py
temba/orgs/migrations/0018_fix_org_groups.py
temba/orgs/models.py
temba/orgs/tests.py
temba/orgs/views.py
templates/orgs/org_manage_accounts.haml

Ensures that when users are removed from org groups, API tokens which they are no longer authorised to have are deleted. Includes migration to remove existing API tokens which users shouldn't have.
Migration also fixes case where user belongs to more than one group. Not sure how they got into this state but found examples in my TextIt dump.

User groups and API token lock down

---

temba/channels/tasks.py
temba/msgs/models.py

This deals with cases like: 
https://app.getsentry.com/nyaruka/rapidpro/issues/127316032/
In the simple cases of single messages, these kind of interruptions are fine, we catch the exception lower down and mark the msg as errored so we'll retry quickly.
In the case of multiple msgs being sent in a batch though the others weren't being requeued, this takes care of that.

requeue interrupted sends in our send_msg_task

---

temba/contacts/search.py

We were querying against all contact values with the key we wanted, then filtering by org, this caused us to evaluate against way more rows than needed when there was a matching key like "gender" across orgs.
This uses the contact field id instead.

Query against specific org field instead of all fields with same name

---

static/coffee/flows/app.coffee

since that breaks our use of `scope()` in various places.

revert angular debug

---

temba/flows/models.py
temba/flows/tests.py

This fixes the case where if someone has a rule like "no thanks, no thank you, no more" and the person writes "no", then we don't save the rule value as "no no no"
We now match each word once and only once on a single individual rule, and in the order that it appeared in the original string.

Fix the value saved by our rule tests when there are repeating rules

---

temba/api/tests/test_v2.py
temba/api/v1/serializers.py
temba/campaigns/models.py
temba/channels/tests.py
temba/contacts/models.py
temba/contacts/search.py
temba/contacts/tests.py
temba/contacts/views.py
temba/flows/models.py
temba/flows/tests.py
temba/msgs/tests.py
temba/perf_tests.py
temba/tests.py
temba/triggers/models.py
temba/triggers/views.py

* Prevent changing dynamic groups from contact update form
* Make group creation more explicit with `create_static` vs `create_dynamic`
* Fix blocking and failing (permanently) contacts so that we only remove them from static groups
* Fix releasing contacts so that we remove from dynamic groups in way that doesn't blow up
* Remove unused group views
* Disallow contact fields called "is" or "has"
* Improve unit tests

Contact group fixes

---

temba/channels/handlers.py
temba/msgs/migrations/0058_update_triggers.py
temba/msgs/tests.py
temba/sql/0058_msgs.sql
temba/sql/current_channels.sql
temba/sql/current_contacts.sql
temba/sql/current_msgs.sql
temba/sql/current_orgs.sql

Couple tweaks and changes here:
1. Added a few optimizations to how / when we look for test contacts when broadcasts are updated. Specifically we first check whether we are actually going to change anything since that can all be done without hitting the DB before testing for test contacts and we also only check for test contacts when the number of recipients for a broadcast is exactly 1. (the only case where a test contact could be included)
2. I've removed us trying to keep track of status on Broadcast when we get delivery reports. We were already ignoring this on Vumi and now that we no longer show broadcasts in the Inbox (just an outbox) this seems like being consistent is right. It was also slow for Uganda with huge broadcasts. I think we may actually just want to remove status from …

Various perf improvements for bcasts

---

temba/orgs/models.py
temba/orgs/tests.py

Fixes:  
https://app.getsentry.com/nyaruka/textit/issues/129537314/
Which was caused by someone setting 6e33 on a contact field value which we parsed into a Too Damn Big decimal.

Fix decimal parsing so that we only return things we can store

---

temba/channels/views.py

Accept Page Access Tokens 43 characters or longer.

FB Channel Claim Update

---

media/test_flows/two_in_row.json
temba/flows/models.py
temba/flows/tests.py

Kind of crazy this has been lurking so long.
If a flow's first action includes replies, we optimize those in the flow start, creating a single broadcast etc.. When we go and execute the actual actions for each run, we then skip reply actions.
Problem is we can't optimize replies that occur after any other action, as the other actions may later the content of the message. This fix deals with that, making sure to execute replies that occur after other actions even when skipping.

Fix case where we skip reply actions in first flow step

---

temba/flows/models.py
temba/flows/tests.py
temba/flows/views.py
temba/orgs/tests.py
temba/orgs/views.py
templates/orgs/org_export.haml

Remove the single flow export in favor of linking to the bulk export with the current flow's group selected by default. This removes the scenario where users were blocked from exporting flows that depend on other flows and instead gives them to ability export a flow and all of it's dependencies if they chose.

Shared Export

---

temba/flows/models.py
temba/flows/tests.py

Bug fixes for deleted groups in two cases:
* Missing groups when parsing a VariableContactAction (like add groups or send). It looks like this only applies to when groups were truly deleted (not set inactive)
* Missing groups when calling flow.as_json(expand_contacts=True)

Fixes for missing groups

---

pip-freeze.txt
temba/api/support.py
temba/api/tests/test_v2.py
temba/api/v2/views.py
temba/settings_common.py

* Updates to latest DRF so we can remove our custom pagination code
* Adds test to ensure result order is correct for multi-page result sets

API ordering part III

---

temba/flows/models.py
temba/ivr/tests.py
temba/msgs/models.py

Don't create ivr messages with a handled state, but instead switch them from pending to handled when the flow actually does it's work. Change process_message to ignore inbound ivr messages.

IVR msg status

---

temba/api/tests/test_v2.py
temba/api/v2/views.py

* Use type agnostic param names - e.g. `campaign` rather than `campaign_uuid` [1]
* Use `.getlist(..)` for repeated params (i.e. don't support comma separated params)
* Use `str_to_bool` for boolean params (parses "1" etc)
[1] On the campaign events endpoint we allow `campaign` to be a UUID or a campaign name, but wasn't sure about allowing that here.

Tweaks to definitions API for consistency with other v2 endpoints

---

temba/api/tests/test_v2.py
temba/api/v2/serializers.py
temba/api/v2/urls.py
temba/api/v2/views.py
temba/flows/migrations/0062_flowlabel_uuid.py
temba/flows/models.py

Since we have a definitions endpoint which handles (potentially expensive) flow definition fetching, this endpoint does not include flow definition
Adds UUIDs to flow labels for consistency with message labels, groups etc.

Flows API v2

---

temba/flows/models.py

Should fix the exception below during very large flow starts. This is new behavior since we expiring all past runs is a new behavior (with one and only one active flow run at a time)
```
Traceback (most recent call last):
File "/home/textit/releases/v2.0.410/temba/flows/models.py", line 4045, in start
self.flow.start(groups, contacts, restart_participants=self.restart_participants, flow_start=self)
File "/home/textit/releases/v2.0.410/temba/flows/models.py", line 1403, in start
FlowRun.bulk_exit(active_runs, FlowRun.EXIT_TYPE_INTERRUPTED)
File "/home/textit/releases/v2.0.410/temba/flows/models.py", line 2493, in bulk_exit
flow.remove_active_for_run_ids(run_ids)
File "/home/textit/releases/v2.0.410/temba/flows/models.py", line 1731, in remove_active_for_run_ids
r.srem(key, *run_ids)
File …
```

Remove active run ids in batches so we dont time out against redis

---

static/coffee/flows/controllers.coffee
templates/flows/flow_editor.haml

currently clicking the blue badge opens both the send message modal and the ruleset editor.
this fix to only open the send message modal only.

Show the  send broadcast modal only on active participants click

---

setup.cfg
temba/api/tests/test_v2.py
temba/api/v2/serializers.py
temba/api/v2/views.py

Bit different from v1 in that we don't identify a contact to update by the `urns` field, but instead introduce a `urn` field. This allows URNs to be removed/stolen even when looking up contacts by their URN.
Also only updates contacts with the provided field - i.e. if name isn't provided, it won't be changed.

Creating and updating contacts in API v2

---

temba/orgs/migrations/0023_remove_org_multi_org.py
temba/orgs/models.py
temba/orgs/tests.py
temba/orgs/views.py
temba/settings_common.py
templates/orgs/org_edit.haml

Make multi user or multi org tiers brand-optional. Also makes rapid not require brands in the default brand.

Optional Tiers

---

temba/api/tests/test_v2.py
temba/api/v2/fields.py
temba/api/v2/serializers.py
temba/api/v2/views.py
temba/channels/tests.py
temba/contacts/tests.py
temba/orgs/models.py
temba/orgs/tests.py

Introduces a bunch of new custom field classes which simplify the v2 serializers, and provide consistent validation and error feedback
All deserialized lists are now limited to 100 items

Improved API v2 serializer fields

---

temba/msgs/migrations/0060_broadcast_recipient_contacts.py
temba/msgs/migrations/0060_remove_broadcast_recipients.py
temba/msgs/migrations/0061_broadcast_recipients.py
temba/msgs/models.py
temba/msgs/tests.py

Originally this added a new `recipient_contacts` field, leaving the existing `recipients` field for use in the backfill migration. But it's just as easy to use messages for the backfill, so now this removes the existing field, and adds a new field for contacts with the same name.
Other problem with backfilling based on the URNs m2m, is that that is no longer updated for new broadcasts - whereas the messages m2m is always populated.

Record recipient contacts instead of URNs on broadcasts, pt 1

---

temba/orgs/models.py
temba/orgs/tests.py
temba/orgs/views.py
temba/settings_common.py
templates/orgs/org_import.haml

Gate import on a import_flows tier instead of looking at whether they have purchased credits. Make defaults 0 if tiers are not defined.

gate import on tier instead of purchased credits

---

temba/contacts/tests.py
temba/contacts/views.py

Because sometimes messages are saved with a timestamp from the channel which may be earlier than the contact creation time.
Fixes https://github.com/rapidpro/rapidpro/issues/344

Contact.get_activity should include activity an hour before contact creation

---

temba/api/tests/test_v1.py
temba/api/tests/test_v2.py
temba/api/v1/serializers.py
temba/api/v2/fields.py
temba/contacts/models.py
temba/contacts/tests.py
temba/contacts/views.py

API v1 skips tel URN validation for the sake of backwards compatibility.
Doesn't yet add any sort of fancy UI control, but error message shows required format:

Require phone numbers to always have a country code in UI and API v2

---

pip-requires.txt
temba/contacts/models.py
temba/contacts/tests.py
temba/flows/models.py

I spotted a test contact with a preferred channel which should never be the case. This makes sure that action never does anything when simulating.

Don't set preferred channels on test contacts

---

temba/msgs/tasks.py
temba/utils/queues.py
temba/utils/tests.py

Introduces a decorator which wraps tasks with the a redis lock to prevent overlapping executions. This is a pattern we repeat widely for scheduled tasks.
So far have only switched the tasks in the msgs app to use this, as don't want to change too much without some feedback.

Nonoverlapping tasks

---

temba/api/tests/test_v2.py
temba/api/v2/fields.py
temba/api/v2/serializers.py
temba/api/v2/views.py
templates/api/v2/api_explorer.haml

- Changes POSTs to use params in the URL to identity existing objects to update
- Updates API explorer to support submission of both query params and post bodies (see screenshots below)
- Ensures all URNs are normalized before use
- Makes response status codes consistent - 200=Updated, 201=Created, 404=Object not found
- Makes endpoint documentation more consistent
API explorer, before:
After:
Note that when you edit the query string text, the URL above it is automatically updated

Reworked POSTs in API v2

---

temba/flows/models.py
temba/ivr/tests.py

During test IVR calls we weren't marking those messages as handled. This causes our monitor to fail for unhandled messages.

Mark test contacts calls as handled

---

temba/api/tests/test_v2.py
temba/api/v2/serializers.py
temba/api/v2/validators.py

The name fields of `Campaign`, `Group` and `Label` all have to be unique within an org-level. This PR subclasses DRF's `UniqueValidator` so it can grab org at request time from the serialization context.

API v2 field uniqueness

---

temba/channels/tests.py

The phonenumbers lib updated and is now rejecting some malformed nepalese phone numbers in our tests for SMSCental and BlackMyna

Fix tests to use proper nepal format

---

temba/api/tests/test_v2.py
temba/api/v2/serializers.py
temba/api/v2/views.py

to allow lazy creation of labels by name, e.g.
```
POST /api/v2/message_actions.json
{
"messages": [1234, 2345, 3456],
"action": "label",
"label_name": "Testing"
}
```
will create label called _Testing_ if it doesn't exist. However labels aren't created if you are unlabelling, e.g.
```
POST /api/v2/message_actions.json
{
"messages": [1234, 2345, 3456],
"action": "unlabel",
"label_name": "No-such-label"
}
```
won't throw an error but also won't create the label.

API v2: Add label_name field to msg bulk action endpoint 

---

static/less/style.less
templates/contacts/contact_history.haml
templates/contacts/contact_read.haml
templates/msgs/message_box.haml

Addresses https://github.com/rapidpro/rapidpro/issues/308 which affects inbox views and contact history view.
Before:
After:
Difficulty is that the CSS wrapping properties only seem to take affect if the container has a fixed size - so I've added max-width settings. That becomes noticeable on history view if page is really wide:

Long message wrapping

---

temba/api/tests/test_v2.py
temba/api/v2/fields.py
temba/api/v2/serializers.py
temba/api/v2/views.py

We currently limit the size of all posted lists in the API - e.g. you can't create a contact that belongs to more than 100 groups or you can't start a flow with more than 100 urns..
This adds a check for the size of field dict for created contacts, and also ensures all the limits are documented on the endpoint HTML page.
For now all the limits are 100 but we can easily modify these per field.

API v2: limit number of posted contact fields and document limits

---

temba/settings_common.py
temba/utils/haml.py

* Adds custom HAML template loader currently in Dash and used by CasePro
* Switches to new TEMPLATES setting required by Django 1.10
Requires https://github.com/nyaruka/textit/pull/47

Django 1.9: Templates

---

media/test_flows/split_first_child_msg.json
temba/flows/models.py
temba/flows/tests.py

Fixes case were weren't properly setting the msg status to PENDING when a child flow was immediately triggered, preventing android messages from going out.

Fix initial status not changing to pending for child flows

---

temba/flows/models.py
temba/flows/tests.py

Fixes rapidpro/rapidpro#369
See:
https://sentry.io/nyaruka/textit/issues/173141285/
https://sentry.io/nyaruka/textit/issues/173143616/

Fix SaveToContactAction to deal with empty path

---

pip-freeze.txt
pip-requires.txt

- Updates some dependencies to use pip releases rather than repo versions (smartmin, librato_bg)
- Removes version numbers from pip-requires.txt except in case where we have known restrictions (i.e. django). Many of the version numbers currently listed in that file conflict with what actually gets installed by pip-freeze.txt
- Removes django-quickblocks as not used

Dependency updates

---

temba/settings_common.py

So turns our recent test slow down (from ~30-35 mins to 45-50mins, travis time limit is 50) was due to this commit https://github.com/nyaruka/rapidpro/commit/589ec5db6b862f55980368f000aa1eb9838a3069
When we upgraded to Django-compressor 1.6 it started throwing an error message about not being able to find lessc (1.5 had been silently not compiling any less) so I added less to package.json.
This PR disables precompiling of coffeescript and less during testing which may mean we miss problems in templates, but does speed up tests considerably (~20 mins)

Disable coffeescript and less compilation during tests

---

temba/campaigns/models.py
temba/campaigns/tasks.py
temba/campaigns/tests.py
temba/utils/__init__.py
temba/utils/tests.py

Two bugs:
1) Our date parsing (from a string) wasn't properly dealing with the current time being in a different DST than the time being parsed. We now deal with that properly (and tests added)
2) timedelta thinks of days as 24 hours, which doesn't work across DST transitions. We now detect these transitions and shift accordingly. Tests for those as well.

fix DST bugs

---

temba/api/tests/test_v2.py
temba/api/v2/views.py
temba/flows/models.py

This allows surveyor to fetch only dependent flows instead the whole graph through following groups and campaigns.

Lighter dependency option

---

temba/channels/models.py
templates/channels/channel_claim.haml

Some minor tweaks for the High Connexion channel: 
1. Increase character limit to 1500, as requested by Solvencia (and confirmed by High Connexion). 
2. Make it a more visible channel option to users in France, as the two aggregators currently listed above it–Plivo and Clickatell–don't currenlty support bidirectional SMS in France.

High Connexion

---

temba/utils/management/commands/migrate_manual.py
temba/utils/management/commands/migrateoffline.py

Supports any migration module with a `def apply_offline()` function.
* Same syntax as migrate, makemigrations etc
* Can reference migrations by prefix, e.g. "msgs 0023"
* Detects any migration conflicts or if migration has already been applied
* Setting verbosity > 1 enables timing of migration (e.g. "-v 2")

Deploy: Management command for applying migrations manually

---

temba/channels/tests.py
temba/msgs/models.py

Change the channel's view of when the message was received to be 'sent_on' for incoming msgs.
This fixes weird sort order on the contact page..

Always have created_on on Msg be our server time

---

temba/contacts/tests.py
temba/contacts/views.py
temba/flows/views.py

For things that get repeated a lot (simulations, flow updates) only saves one even per day. For imports and exports makes sure that we aren't creating events when we are just refreshing the page to check for status.

Tweaks to reduce our analytics usage 

---

templates/api/v2/api_explorer.haml

Fixes https://github.com/rapidpro/rapidpro/issues/404

Fix query string params not being included in requests from API v2 explorer

---

temba/contacts/tests.py
temba/contacts/views.py

Fix upcoming messages on contact read page to properly show campaign events which are localized. Existing tests are generally good, but they weren't creating localized message events which would have caught this behavior.

Show campaign message properly in upcoming events

---

karma/flows/test_controllers.coffee
karma/flows/test_services.coffee
media/test_flows/favorites.json
temba/flows/migrations/0077_auto_20161215_2232.py
temba/flows/migrations/0078_auto_20161216_1803.py
temba/flows/models.py
temba/flows/tests.py
temba/sql/0075_flows.sql
temba/sql/0078_flows.sql
temba/sql/current_flows.sql

* Same triggers as before, but now handles null next_uuid
* Changes update trigger to check on left_on instead of next_uuid
* Fixed case for redis-based activity resulting in negative counters for null destinations
* Fixes squashing method which results in null destinations not getting squashed during backfill, will squash these by hand once complete

FlowPathCount triggers

---

templates/api/v1/api_root.html
templates/api/v2/api_root.html

It assumes you're using the default doc pages which have tabs so it throws an error and breaks other Javascript on the page leading to things like the dropdown menu not working https://github.com/rapidpro/rapidpro/issues/409

Don't include REST framework's default.js on customized API pages

---

temba/channels/models.py
temba/channels/tests.py

Instead of the default of 30 mins which is causing timeouts for Ukraine.

Set our msg validity to be 12 hours

---

static/less/style.less

Just a styling tweak. Issue was collision with .loader from flow results. Properly nested now.

Fix loader animation background

---

templates/channels/channel_configuration.haml

No functional change on our side as we only use the channel uuid as identification but can aid when debugging carriers that do weird things.

Add the destination address (shortcode usually) to what Kannel posts

---

temba/temba_celery.py

Logs all exceptions that bubble out of celery tasks to sentry (tested on staging and seems to be doing the right thing)

Log celery exceptions

---

temba/api/v2/serializers.py
temba/api/v2/views.py

To 640 to match rest of app. CasePro users want to send longer messages.

Increase the maximum length of message that can be sent over the API

---

temba/contacts/templatetags/contacts.py
temba/contacts/tests.py
temba/contacts/views.py
templates/contacts/contact_history.haml
templates/contacts/contact_read.haml

* Switch to using intercooler for message fetching and status/new message polling
* Simplify history parameters to just `before` and `after` to denote time windows; recent polling inferred when before is not included
* Message history list now infinite scrolls
* Use same loading indicator as flow results run table

Contact history intercooler updates

---

temba/channels/models.py
temba/channels/tasks.py
temba/channels/views.py

Not sure why this has only started being a problem recently. Maybe celery wasn't actually using JSON?
Fixes https://sentry.io/nyaruka/textit/issues/206692165/

Don't pass raw enum to notify_mage_task as it's not JSON serializable

---

temba/settings_common.py
temba/utils/middleware.py
temba/utils/tests.py

To include in nginx log, add following to config for our current "json_log" format:
```
'"temba_org": $upstream_http_x_temba_org, '
```

Return org id as response header so that it can be logged in nginx

---

templates/contacts/contact_read.haml

On upcoming events we are currently showing the last three to occur instead of the next three to occur without expanding. This fixes that to be the next three.

Invert show all for upcoming events

---

temba/flows/models.py
temba/flows/tests.py

We need to reconsider our strategy here come FLOIP, but this will get us a bit farther.
I think we have two way we can go:
1) say that the context (@extra) can be YUGE and we store it in S3 or the like so it costs us nothing. That's probably my vote.
or
2) Provide a way for the user to extra keys within the same webhook block and at that point give them access to everything, then throw away the rest. This is slightly more difficult to reason about I think though.

keep up to 256 extra keys from webhooks

---

temba/channels/models.py
temba/channels/tests.py

Turns out we need that to send things in the right format at the SMSC level.

pass charset parameter to kannel when sending unicode

---

temba/settings_common.py

Uses the standard compress command, but with a list of offline contexts per brand.
Addresses same issue as rapidpro/rapidpro/pull/446

Offline context per brand

---

temba/contacts/models.py
temba/contacts/tests.py
templates/contacts/contact_list.haml

- Enables searching in groups and blocked/stopped contacts. Currently the search box is shown at the top of any contact listing page, but using it always takes the user back to the 'All Contacts' list page and does a search on that group.
- Fixes `Contact.search` so it doesn't try to evaluate the base_query just to see it is provided.

Contact search improvements

---

temba/channels/models.py
temba/flows/tasks.py
temba/flows/tests.py
temba/utils/__init__.py
temba/utils/tests.py

When we are timing out a huge number of runs we can double queue the handling of those and get in a giant loop.
Two changes:
- task grabs a lock for 1 hour instead of 15 mins
- we keep track of run/timeout pairs we have queued to process and never double queue
Should keep us from getting too out of control.

Increase non-overlap on timeout queueing, never double queue

---

temba/channels/handlers.py
temba/ivr/clients.py
temba/ivr/tests.py

* Switch external id to use nexmo's call id instead of conversation uuid. This is needed to successfully hangup calls since the voice api operations with call ids.
* Add logic for accepting inbound calls using the conversation_uuid (this is all they provide in this case) and then switch to call uuid once it is available.

Nexmo uuids

---

temba/flows/models.py
temba/ivr/tests.py

Don't reset outgoing IVR messages to PENDING that are already considered DELIVERED.
Fixes https://github.com/rapidpro/rapidpro/issues/468

Fix for IVR messages showing up in outbox

---

templates/contacts/contact_list.haml

A tiny change but about the only change I'm certain about right now.

Fix groups prefetch not being used on contact list pages

---

temba/channels/views.py
temba/utils/__init__.py
temba/utils/tests.py

`Channel.add_twitter_channel` uses `on_transaction_commit` now so this isn't needed... but I'm also not 100% sure it was needed previously, especially since its only for tests

Removing non_atomic_when_eager decorator which is no longer needed

---

media/test_flows/gather_digits.json
temba/flows/models.py
temba/ivr/tests.py

This change makes it so we no longer create inbound messages during gather timeouts. This will allow calls in a gather-timeout loop to expire properly (and also have a slightly nicer contact history).
Fixes: https://github.com/rapidpro/rapidpro/issues/474

Fix IVR timeout messages

---

temba/flows/models.py
temba/flows/tests.py

We were leaving runs active when nuking their steps during ```flow.release()```. Aside from having active runs against inactive flows, this also throws off monitoring for empty flow run creation.

Deactivate runs when releasing flows

---

temba/channels/models.py
temba/channels/tests.py
temba/channels/views.py
templates/channels/channel_claim.haml
templates/channels/channel_claim_external.haml
templates/channels/channel_configuration.haml

Allows us to use the External Channel config to send to JSON and XML endpoints as well, substituting variables with the right kind of escaping for each.

Improvements to External Channels

---

temba/contacts/models.py
temba/contacts/search.py
temba/contacts/tests.py

We implement searches like `field=""` as a request for contacts not in the set of contacts who _do_ have a value for that field. This is obviously not an efficient way of determining whether a single contact has a value for that particular field.
PR introduces the idea of a base set of contacts within which the search is applied. For membership checks

Optimize contact searching when used to determine single contact's membership

---

static/coffee/flows/services.coffee
temba/flows/models.py
temba/flows/tests.py
temba/flows/views.py
temba/middleware.py
temba/tests.py

* Use flow system user as the user for migrations when they are needed. This will show up in the revision history as "System User" and the support box as the email address.
* Sort our flow list by ```saved_on``` instead of ```modified_on```
* Don't update ```saved_on``` when migrating flows forward, only for user initiated saves
Fixes: https://github.com/rapidpro/rapidpro/issues/305

Use flow user for migrations

---

temba/middleware.py
temba/orgs/views.py

* Use the brand key instead of the 'host' when determining login gating (host is the parent deployment the brand belongs to)

Fix brand login restrictions

---

temba/utils/management/commands/perf_test.py

E.g. `./manage.py perf_test --orgs=1,100 --org-limits=3000,500`

Performance: configurable org specific time limits

---

temba/contacts/models.py
temba/utils/currencies.py
temba/utils/http.py
temba/utils/languages.py
temba/utils/profiler.py
temba/utils/tests.py
temba/utils/voicexml.py

For now, just applied to `ContactGroup._check_dynamic_membership(..)`
Example of sentry report when I patched `_check_dynamic_membership` on staging to sleep for a second: https://sentry.io/nyaruka/textit-staging/issues/230843424/. You can find contact/group details in the stacktrace.
Also some unrelated tidying in the `utils` app.

Performance: decorator to report error when method call takes too long

---

temba/api/models.py
temba/api/tests/test_models.py
temba/flows/tests.py

Send channel and flow UUID with webhook flow events, since API v2 now only exposes UUIDs for these objects.

Send channel and flow UUID with webhook flow events

---

temba/channels/handlers.py
temba/channels/tests.py

These become uncaught exceptions and 500 responses.

Channel handlers shouldn't throw validation errors

---

temba/flows/models.py
temba/flows/tests.py

It seems we added tracking of segment visits by `FlowPathCount` but didn't switch to using them when displaying flows. They're still manually calculated if/when the flow stats cache is marked as inaccurate.

Use FlowPathCount for segment visit counts

---

temba/utils/management/commands/test_db.py

Figured out why sending messages in `test_db` is so slow - most get "fake sent" by a Nexmo channel which is throttled at 1 msg/sec.
Also adds squashing of some count models after generating runs and messages.

Improve performance of the test_db command

---

static/less/legacy.less

E.g. avoid this for labels within folders:

Fix styling of nested lists in sidebar nav pane

---

temba/contacts/models.py
temba/contacts/search.py
temba/contacts/tests.py
temba/utils/management/commands/perf_test.py

`x != ""` means "x has a value"
`x = ""` means "x has no value"
For fields/values this becomes a check as to whether a value exists because `Value` instances can't have empty values. Likewise for URNs this becomes a check as to whether the contact has a URN with that scheme. For attributes (i.e. name) it becomes a check whether that attribute is null or an empty string.

Allow searching for contacts with any value for something

---

temba/msgs/models.py

Sadly this is kinda impossible to test even with ALWAYS_EAGER to false.

prioritize msg handling over timeouts and event fires

---

static/coffee/simulator.coffee

Fix https://github.com/rapidpro/rapidpro/issues/509

fix simulator to not allow empty string message

---

temba/flows/models.py
temba/ivr/tests.py

This is to further combat Twilio not sending hangup notifications at random.

Make sure calls have expiration on initiation

---

static/less/flow_editor.less
templates/flows/flow_editor.haml

Still looks the same 
And clickable on hover has underline

Add flow link on subflow ruleset too

---

temba/msgs/tasks.py

They might have been deleted by a flow deletion - which could be the cause of https://sentry.io/nyaruka/textit/issues/271933284/

Don't assume event fires still exist in process_fire_events

---

temba/channels/tests.py
temba/contacts/models.py
temba/contacts/tests.py
temba/flows/models.py
temba/msgs/models.py
temba/ussd/tests.py

From working on the Msg.attachments change, I figured things would be simpler if we didn't have two separate methods

Combine Contact.send and Contact.send_all into one method

---

temba/api/tests/test_v1.py
temba/api/v2/serializers.py
temba/channels/handlers.py
temba/channels/models.py
temba/channels/tests.py
temba/contacts/models.py
temba/contacts/templatetags/contacts.py
temba/contacts/tests.py
temba/flows/models.py
temba/flows/tests.py
temba/flows/views.py
temba/ivr/tests.py
temba/msgs/models.py
temba/msgs/templatetags/sms.py
temba/msgs/tests.py
temba/tests.py

This part just switches code to using `Msg.attachments` instead of `Msg.media` - we still only support one attachment per message at this point.

Multiple message attachments part 3

---

temba/api/tests/test_v2.py
temba/api/v2/fields.py
temba/api/v2/views.py

Fixes some cases where we blow up instead of returning an error message:
* User passes something invalid for a param which is expected to be an integer, e,g, https://sentry.io/nyaruka/rapidpro/issues/275291981/
* User passes invalid value for `dependencies` param, e.g. https://sentry.io/nyaruka/rapidpro/issues/275266509/
* User passes an object to foreign key field, e.g. https://sentry.io/nyaruka/rapidpro/issues/227900322/
Also fixes contacts endpoint docs https://github.com/rapidpro/rapidpro/issues/561

API v2 fixes

---

temba/channels/handlers.py
temba/channels/tests.py

Fix https://sentry.io/nyaruka/textit/issues/284564732/

Better error message for external channel handler for wrong time format

---

temba/channels/models.py
temba/channels/tests.py
temba/channels/views.py

Macrokisok expect us to use sender ID when sending MT message and we want to keep the verification for the MO to number https://github.com/nyaruka/rapidpro/blob/7d769fe802be477dd82b4e971b8122cc4ca220b1/temba/channels/handlers.py#L1068
I added the config for sender ID and that should be provided by Macrokiosk

Add sender ID config for Macrokiosk channels

---

temba/msgs/tests.py
temba/msgs/views.py
templates/frame.haml
templates/smartmin/modal.haml

I previously removed heavy_data.js which was an old dataepicker library used by django_select2 because smartmin uses bootstrap-datepicker... but need this fix so that forms on modals load any media associated with their fields.
Currently seeing date parse errors in sentry because users are entering unparseable dates, e.g. https://sentry.io/nyaruka/rapidpro/issues/296690098/

Ensure form media is loaded for forms on modals

---

temba/channels/handlers.py
temba/channels/tests.py

Updates Twilio, Telegram, Vider and JioChat channels to save a single message with multiple attachments rather than creating multiple messages. These are the only channels which currently actually create attachments.
Message text no longer includes media URLs, tho this is still included in `@step.value` (#1308)

Multiple media attachments per messages

---

temba/api/tests.py
temba/api/tests/__init__.py
temba/api/v1/tests.py
temba/api/v2/tests.py

Just moving these test files into the sub-packages that they test, since I discovered Django no longer requires test files to all be in a single package called tests, and this just seems a more logical way to organize them.

Move api tests into the packages that they're testing

---

temba/flows/tests.py
temba/flows/views.py
temba/triggers/models.py

Avoids https://sentry.io/nyaruka/textit/issues/300353450/
Also lets users type "foo, bar" rather than blowing up thinking that bar contains a space.

Validate trigger keyword length when creating or updating a flow

---

temba/flows/tests.py

GoFlow is not a fan of our hardcoded UUID values we use in tests. Since we want the new_engine branch to show goflow working against our current tests, I'm making any changes to tests outside of that branch.

Test tweaks

---

temba/api/models.py
temba/api/tests.py
temba/api/v1/tests.py
temba/api/v2/serializers.py
temba/api/v2/tests.py
temba/channels/models.py
temba/channels/types/facebook/__init__.py
temba/channels/types/telegram/__init__.py
temba/flows/tests.py
temba/msgs/models.py
temba/msgs/tests.py

Since we no longer include urls in the message text. This PR also tries to clean up the attachment support code a bit and remove methods we no longer use.

Include attachments in webhook payloads

---

static/coffee/flows/controllers.coffee
static/coffee/flows/services.coffee
temba/flows/models.py
temba/flows/tests.py

* Create new rulesets in editor when toggling type
* Ensure inbound connections are maintained when toggling between actions and rulesets
* Verify that we abandon active runs on ruleset removal

Abandon active runs on ruleset delete

---

media/test_flows/color.json
temba/api/tests.py
temba/api/v1/tests.py
temba/api/v2/tests.py
temba/campaigns/tests.py
temba/contacts/tests.py
temba/flows/tests.py
temba/msgs/tests.py
temba/orgs/tests.py
temba/tests.py
temba/triggers/tests.py

* Moves the flow from `TembaTest.create_flow_definition` to `test_flows/color.json` 
* Replaces calls to uuid/uuid1 with actual UUIDs from that flow or random uuid4s
* Tries to avoid updating the definition on test flows where a definition isn't needed
* General tidying like `self.assertTrue(x in y)` -> `self.assertIn(x, y)`

Rework tests to use real UUIDs

---

temba/channels/handlers.py
temba/channels/models.py
temba/channels/tests.py
temba/channels/types/twitter_activity/__init__.py
temba/msgs/tests.py
temba/utils/management/commands/test_db.py
temba/utils/twitter.py

* Remove a channel even if deactivating it throws an exception
* Remove no longer used `notify_mage` param for `Channel.release` - Mage is notified based on `settings.IS_PROD`
* Fix channel type in Twitter Activity API handler
* Update endpoint used to subscribe to a Twitter Activity API webhook (this appears to have changed)

Fixes for Twitter Activity channels

---

temba/channels/models.py

Fixes the case where a user tries to delete a Twilio channel which we weren't able to migrate to a channel-specific-app, i.e. https://sentry.io/nyaruka/textit/issues/311552652/

Twilio channel removal fix

---

media/test_flows/dual_webhook.json
media/test_flows/stacked_webhook_exits.json
media/test_flows/triggered.json
media/test_flows/webhook_loop.json
temba/flows/tests.py
temba/settings_common.py
temba/tests.py

Because some tests will use goflow to run flows in the future - we can't rely on mocking at the level of the python request. This PR adds a simple HTTP server to our test runner setup, which can generate a particular response based on the parameters passed to it.

Use a real but mockable HTTP server to test webhooks in flows 

---

temba/api/v1/serializers.py
temba/api/v1/tests.py
temba/orgs/models.py
temba/orgs/tests.py

This fixes some failed Surveyor submissions due to not being able to identify the brand of a submitter's org.

Fix surveyor submissions across brands

---

temba/flows/models.py
temba/flows/tests.py

Named groups was never documented and doesn't appear to have been used so removing it now before someone does

RegexTest match groups should only be accessible by index and not name

---

temba/flows/views.py

Just removes @step.contact from completion. I've also updated the knowledge base with details for October 1st changes to @contact inside Send Message to somebody else.

Remove step.contact from completion options

---

temba/channels/handlers.py
temba/channels/models.py
temba/channels/tests.py
temba/channels/types/blackmyna/tests.py
temba/channels/types/external/tests.py
temba/channels/types/facebook/tests.py
temba/channels/types/infobip/tests.py
temba/channels/types/jiochat/tests.py
temba/channels/types/telegram/type.py
temba/channels/types/twitter_activity/tests.py
temba/channels/types/twitter_activity/type.py
temba/channels/types/viber_public/type.py
temba/channels/urls.py
temba/orgs/views.py
templates/channels/channel_claim_viber.haml
templates/channels/channel_configuration.haml

We'll still have to do nginx remappings ourselves, but future peeps will be able to just reroute all of /c/ to courier via a application level load balancer.

Add /c/kn/uuid-uuid-uuid/receive style endpoints for all channel types

---

temba/flows/models.py
temba/flows/tests.py

This makes it match the behavior of our other string matching tests.

strip matched string in test not empty

---

temba/flows/models.py

Cause we don't currently work when there are 2M other active runs on a start.

exit flows in batches so we dont have to grab all runs at once

---

temba/flows/models.py
temba/flows/tests.py
temba/msgs/models.py
temba/msgs/tests.py

Previously `@contact` would become the recipient in a send_msg action. Now `@step.contact` and `@contact` will both refer to the run contact, and when we migrate flows to the new world, we'll map both to just `@contact`.
We sent an email to users about this change a while back.

@step.contact and @contact should both be the run contact

---

templates/flows/flow_editor.haml
templates/msgs/msg_send_modal.haml

Since these weren't compressed, these were overwriting signatures of newer compressed versions of excellent (that is in frame.haml). This remove all other includes since they are already present.

remove duplicate excellent includes

---

temba/orgs/models.py

Sets our recalculation threshold a bit higher so we don't get out of sync.

recalculate topups more often

---

temba/channels/handlers.py
temba/channels/tests.py
temba/settings_common.py

Since not everyone uses Mage, seems like we should only allow access to the MageHandler endpoint if they have configured an access token

Mage handler shouldn't be accessible using example token

---

temba/channels/types/plivo/tests.py
temba/channels/types/plivo/type.py

Plivo channel claim view is a redirection after org plivo connect which really puts the credentials on the session.
This will prevent the the having two 'Plivo number' on the claim page while the one from dynamic channel can not work

Remove the duplicated Plivo number block row

---

temba/contacts/models.py
temba/contacts/tests.py

Previously the window of events was based on the creation of the event not the event fire, but then sorted by the fire creation. This resulted in events that were created outside of the window not being available for the chained sort even if their fire occurred within it.

Fix contact history event fire windowing

---

temba/contacts/models.py
temba/contacts/tests.py

I don't think we actually need to keep category long term, so we can drop writing it entirely when we migrate to a new contact value store, but in the meantime this fixes an issue where we were using and displaying state location names for `TYPE_TEXT` contact fields. This was especially confusing when that remapping was taking place due to a string matching a location alias.

Never use category field for value of contact fields

---

temba/channels/migrations/0059_update_nexmo_channels_roles.py
temba/channels/migrations/0072_migrate_twilio_apps.py
temba/channels/models.py
temba/channels/tests.py
temba/channels/types/nexmo/views.py
temba/channels/types/plivo/type.py
temba/channels/types/plivo/views.py
temba/channels/types/telegram/type.py
temba/channels/types/twilio/views.py
temba/channels/types/viber_public/type.py
temba/flows/models.py
temba/flows/views.py
temba/ivr/clients.py
temba/ivr/migrations/0014_add_twilio_status_callback.py
temba/ivr/models.py
temba/ivr/tests.py
temba/orgs/migrations/0032_fix_org_with_nexmo_config.py
temba/orgs/migrations/0033_fix_org_with_nexmo_config_absolute_urls.py
temba/orgs/models.py
temba/orgs/tests.py
temba/orgs/views.py
temba/settings.py.dev

We've been running with both of these being the same for the past few days so I think we are safe on this.
Next up, use brand specific hosts for whitelabels.

Remove TEMBA_HOST, always use HOSTNAME

---

media/test_flows/color.json
temba/api/tests.py
temba/api/v1/tests.py
temba/api/v2/tests.py
temba/contacts/tests.py
temba/flows/tests.py
temba/msgs/tests.py
temba/orgs/tests.py
temba/tests.py
temba/triggers/tests.py

Currently this test flow is loaded as a static definition, assumed to be at the latest export version. This PR changes it to be like every other test flow.

Import the color flow used in tests so it's always migrated to latest version

---

temba/msgs/models.py
temba/orgs/models.py
temba/orgs/tasks.py
temba/orgs/tests.py
temba/orgs/views.py
temba/settings_common.py
temba/tests.py
temba/utils/cache.py
temba/utils/tests.py
templates/orgs/email/alert_email.html
templates/orgs/email/alert_email.txt

* Changes our get_cacheable_result to defer to the evaluation method for the ttl
* Remove OrgEvent and superfluous cache clearing methods in favor of a singular comprehensive org.clear_credit_cache method
* Optimizations for calculating total credits used

Credit cache changes

---

media/test_flows/flow_loop.json
static/coffee/flows/services.coffee
temba/flows/models.py
temba/flows/tests.py
temba/tests.py

Handles case where the flow version is migrated while an editor is currently open.

Block saving migrated flows

---

temba/flows/models.py
temba/flows/tasks.py
temba/flows/tests.py
temba/utils/models.py

1) Adds squashing of the category flow counts to the same task that squashes other counts
2) Only squash up to 1,000 unique unsquashed combinations
3) For FlowCategoryCount, only squash 10,000 things at a time
I think with those three we should get decent performance and start squashing the hundreds of millions of these we have around.

limit scope of squashing so we can recover from giant unsquashed numbers

---

temba/msgs/tests.py
temba/msgs/views.py
templates/msgs/message_box.haml

Currently we prefetch channel_logs for the views that have them (sent/failed/outbox) but we try to look up channel_logs in all views (inbox etc) - leading to a lot of extra pointless db hits.
Have also added some num-query checks to the tests for good measure.

Msg view tweaks

---

temba/celery_autoscaler.py

* log current stats in `_maybe_scale` as celery.INFO
* we need to add `-l INFO` when starting celery on the CLI
* simplify calculation of mem/cpu bound workers
* if there are available resources, set limit to `max_concurrency`

Superautoscaler updates

---

temba/flows/models.py

These just mean two users are editing a flow at the same time so just show user an error message

Don't log FlowUserConflictException exceptions to Sentry

---

media/test_flows/webhook.json
temba/api/v1/tests.py
temba/flows/models.py
temba/flows/tests.py

Also stops setting `rule_category` and `rule_value_decimal` on steps as these aren't used anywhere. The only properties of steps that we currently rely on are step_uuid/rule_uuid/rule_uuid and its messages m2m.

Stepless tests part 1

---

temba/settings_common.py
temba/utils/analytics.py

METRICS_HOSTNAME is used by Librato when reporting metrics per host

Define METRICS_HOSTNAME

---

temba/utils/dates.py
temba/utils/tests.py

* Don't blow up with logically invalid dates (e.g. 31-02-2017)
* Ensure regex matches begin and end with word boundaries, e.g. otherwise "231231-12-1234567" can match as "31-12-1234"

Date parsing fixes

---

temba/flows/models.py
temba/flows/tests.py

otherwise we keep requeuing the timeout constantly waiting for the msg to be sent, which it never will be.

clear timeouts for msgs which dont have credits assigned to them

---

temba/channels/tests.py
temba/msgs/tests.py
temba/orgs/tests.py
temba/orgs/views.py

Fixes: rapidpro/rapidpro/issues/727
Change prevents repeat redirect badness with /org/choose when a redirect is configured.

Brand redirect

---

temba/flows/models.py
temba/flows/tests.py

ContainsPhraseTest shouldn't blow up if test string is empty, i.e.
"x" only contains the phrase ""... already evaluates to false
"" only contains the phrase ""... already evaluates to true
"x" contains the phrase ""... pretty sure this should evaluate to true?
https://sentry.io/nyaruka/textit/issues/416490098/
https://sentry.io/nyaruka/rapidpro/issues/459289471/
HasEmailTest should find email addresses with punctuation before and after: https://github.com/resistbot/rapidbot/issues/66

Tweaks to string tests

---

temba/tests.py
temba/utils/tests.py

This isn't configured in our TextIt settings yet so flowserver tests won't be created if you're using that settings file

Make testing with flowserver dependent on configuring FLOW_SERVER_URL

---

temba/tests/tests.py

a.k.a the smallest PR
Now that we're comparing bigger dicts in our tests, we want to see the diffs, but default is only to show diffs up to 640 chars. I'm always upping this locally.

Increase maxDiff in tests

---

temba/utils/dates.py
temba/utils/tests.py

Looks like dates from goflow sometimes have a trailing zero removed so you have 1/10 chance of getting a second fraction with 8 digits

Date parsing should accept ISO dates with up to 9 second fraction digits

---

templates/frame.haml

Let brands specify a list of includes in the document head so they can have their own custom third party integrations.

allow brands to specifiy includes for the document head

---

temba/api/v1/serializers.py
temba/channels/handlers.py
temba/channels/models.py
temba/channels/types/__init__.py
temba/channels/types/twitter/type.py
temba/channels/types/yo/type.py
temba/contacts/models.py
temba/contacts/tests.py
temba/flows/models.py
temba/flows/views.py
temba/msgs/models.py
temba/settings_common.py
temba/utils/goflow/serialize.py
temba/utils/goflow/tests.py

* Add some extra fields to goflow/editor serialization that we need in goflow for picking channels
* Replace contact.channel in goflow serialization with URN query params for each URN's channel
* Move Yo constants into the Yo type
* Remove the never-used (?) Dummy channel type

Channel and GoGlow Contact tweaks

---

temba/settings_common.py

Just created a new django project, then copied in their default middlewares. That includes the clickjacking prevention and the nice-sounding "SecurityMiddleware"

update middlewares to Django defaults

---

temba/contacts/migrations/0073_backfill_contact_fields.py
temba/contacts/models.py
temba/contacts/tests.py

It wouldn't be a great migration if we didn't do it more than once right?
We were saving datetime values always in UTC which seems wrong to me. Now rewrites them to always save in the org timezone (someday contact timezone) which feels much more right.

always serialize contact field datetime values in the org timezone

---

temba/flows/models.py
temba/flows/tests.py
temba/flows/views.py

* Only show current test contact activity (instead of all test contacts)
* Don't blow up if old path data is missing exits
Fixes: https://sentry.io/nyaruka/rapidpro/issues/480677178/events/16580633977/

Fixes for test contact activity

---

temba/flows/models.py

Fixes, '>' not supported between instances of 'NoneType' and 'int'
* https://sentry.io/nyaruka/rapidpro/issues/508758620

Fixes for errors detected in production after switching to py3

---

temba/api/v2/tests.py
temba/api/v2/views.py

In response to ticket.. we have indexes for this so should be safe as an API endpoint.

Add API endpoint to view failed messages

---

temba/flows/models.py
temba/flows/tests.py

Fixes https://sentry.io/nyaruka/rapidpro/issues/529161850/
Old messages don't have a UUID set on them

Don't assume messages have a UUID in FlowRun.add_messages

---

pip-freeze.txt
temba/contacts/models.py
temba/contacts/tests.py

So that imports don't create contacts with a modified on in the past.

finalize contact imports

---

temba/msgs/tests.py
templates/msgs/msg_failed.haml
templates/msgs/msg_sent.haml

Fix the export buttons not currently visible

Fix to display Export buttons on sent msgs folder and failed msgs folder

---

media/test_flows/action_packed.json
media/test_flows/migrate_to_9.json
static/coffee/flows/services.coffee
temba/channels/migrations/0087_migrate_twilio_endpoints.py
temba/flows/models.py
temba/flows/tests.py
temba/flows/views.py
templates/flows/flow_editor.haml

Reduce likelihood of group broadcast flows by not allowing them to be imported or copied
👣 🔫

Disallow group flows

---

.travis.yml
temba/api/v1/tests.py
temba/flows/models.py
temba/flows/tests.py
temba/tests/base.py

* Changes `@also_in_flowserver` so that in passes in a bool param called `in_flowserver` to each test method
*  Update webhook rulesets to use `"<METHOD> <URL>"` as their result input to match goflow

More flowserver tests

---

temba/channels/migrations/0088_fix_twiml_configs.py
temba/msgs/models.py
temba/msgs/tests.py
temba/settings.py.dev
temba/settings_common.py
temba/utils/cache.py

Blows up when we try to send a broadcast with the same text to a group within the last two days.. times feels a little bit long.. maybe 12 hours is better?

do not allow dupe broadcasts to groups

---

temba/api/migrations/0015_webhookresult_contact.py
temba/campaigns/migrations/0015_campaignevent_message_new.py

Because it adds a field and populates it in same transaction

Fix django migrations which can lead to locks 

---

temba/msgs/tests.py
temba/msgs/views.py
temba/triggers/models.py

We haven't been displaying flow names on messages for a while now so I think these still being pretched is just an oversight (see https://github.com/nyaruka/rapidpro/commit/16eaf5034db5f79c3ab56a0cff90681d8909a364#diff-3e1211851df539d5e91a77aed0d52b6b)

Don't try to prefetch steps on msg views

---

temba/flows/tests.py
temba/flows/views.py

To avoid https://sentry.io/nyaruka/rapidpro/issues/563381730/ which seems to be an inactive flow being requested as a subflow

Return error message if non-existent asset requested from assets endpoint

---

temba/flows/migrations/0158_backfill_recent_step_uuids.py

This can occur because 1) we have a bad run path 2) we trimmed away the steps in the path because it was too long. I'm pretty sure 1) is way more common than 2).
So these will remain as `NULL` uuids in `FlowPathRecentRun`.. and when we see how many there are we can decide what to do with them
Unblocks the backfill migration (see https://sentry.io/nyaruka/textit/issues/562968838/)

Don't blow up when we can't find path steps for a given recent run flow segment

---

temba/flows/models.py

We need to set this in `handle_ruleset` if a subflow has no waits

Child context fix

---

temba/contacts/models.py
temba/contacts/tests.py

- anonymize urns before deleting to avoid collisions with new inbound
- release sessions before releasing urns

Fixes for contact release

---

temba/contacts/models.py
temba/contacts/tests.py

- Release messages connected to urns even if they are attached to a different contact
- Don't blow up when trying to parse or form a deleted scheme

Contact Protect Luxe and Reduxe

---

temba/flows/server/trial.py

Getting failing trials when message text ends with space

Strip message text on events before doing flowserver trial comparison

---

temba/channels/types/twitter/tests.py
temba/channels/types/twitter/type.py
temba/channels/types/twitter_activity/tests.py
temba/channels/types/twitter_activity/type.py
templates/channels/types/twitter_activity/claim.haml

Old Twitter only available to Beta users (until we remove it entirely with Mage)

🐦 Make twitter activity API the default Twitter channel type

---

temba/flows/server/client.py
temba/flows/server/tests.py
temba/flows/server/trial.py
temba/flows/tests.py
temba/tests/matchers.py
temba/utils/tests.py

* Don't ignore last exit_uuid when comparing paths in flow server trials
* Improve reporting of trial differences (include org name etc)
* Improve reporting of 400 errors from flow server (include full request)

⚛ Flow server trial tweaks

---

media/test_flows/hierarchy.json
temba/flows/server/tests.py
temba/flows/server/trial.py

So that we include all ancestor runs and not just the immediate parent
We've been seeing this manifest itself as errors from the flow server complaining it can't find a parent run.

🔬 Fix reconstructing sessions for runs being trialled in the flowserver

---

media/test_flows/survey_campaign.json
temba/api/v2/tests.py
temba/campaigns/models.py
temba/campaigns/tests.py
temba/flows/tests.py
temba/orgs/tests.py

Properly release previous events when reimporting campaigns
See: https://sentry.io/nyaruka/textit/issues/577362138/

🚽 Release campaign events on import

---

temba/flows/models.py
temba/flows/views.py

Unit test already exists for this, just moving functionality so runs deleted outside of simulation endpoint do the right thing (such as Flow deletion)
See: https://sentry.io/nyaruka/textit/issues/593697011/

💾 Move action log delete to flow run release

---

temba/channels/models.py
temba/channels/types/twitter_activity/tests.py
temba/channels/types/twitter_activity/type.py
temba/channels/types/twitter_activity/views.py
temba/channels/views.py
temba/utils/twitter.py
templates/channels/types/twitter_activity/claim.haml

* deletes existing webhooks if there is only one webhook registered
* saves webhook id so we release the right webhook
* activate the channel at the same time we claim so any errors are immediately surfaced to user

🐦 tweaks to twitter activity claiming 

---

temba/api/v1/serializers.py
temba/api/v1/tests.py
temba/flows/models.py

Now both rulesets and actionsets are loaded from the specific flow revision. Should prevent errors like https://sentry.io/nyaruka/rapidpro/issues/618412808/events/25612811061/

Fix surveyor run submission when action set has been deleted

---

temba/api/v2/serializers.py
temba/api/v2/tests.py

Fixes https://sentry.io/nyaruka/textit/issues/564362751/
* this is not applicable for `ContactBulkActionSerializer` because it uses ContactField serializer that only reads valid contacts

🦹 Raise API.ValidationError for inactive contacts

---

temba/channels/types/twilio/tests.py
temba/ivr/clients.py
temba/ivr/tests.py
temba/tests/twilio.py

This is the way I find to be able to set the API URL and not break TWIML channels
https://github.com/twilio/twilio-python/blob/master/twilio/rest/__init__.py#L146
https://github.com/twilio/twilio-python/blob/master/twilio/rest/api/__init__.py#L24

Have a way to set the custom URL for TWiML on the client

---

temba/contacts/models.py
temba/contacts/tests.py

Fixes failing `test_contact_search_evaluation` test

📅 Don't use datetime_to_str for contact search values

---

temba/orgs/views.py
temba/utils/analytics.py
temba/utils/tests.py

Fixes: https://sentry.io/nyaruka/textit/issues/563557980
Initial fix solved only part of the problem. I was not aware that in
`super().post_save()` we create the Org and create example Flows for the
Org. The issue is that for every flow create we track the event
`nyaruka.flow_created` which causes *User Not Found* error on Intercom
service.

📉 Setup user tracking before creating an Org

---

media/test_flows/keywords.json
temba/flows/handlers.py
temba/flows/models.py
temba/flows/server/trial/tests.py
temba/flows/tests.py

Two sorta unrelated fixes but I found them both looking at a flowserver trial of the same flow, and created a test flow based on that:
* Starting messages from subflows shouldn't be added to the parent run
* Don't start a flowserver trial when Flow.find_and_handle is called from a trigger - i.e. that's not a resume event.

💬 Flowserver trial fixes

---

temba/orgs/views.py

Fixes: https://sentry.io/nyaruka/textit/issues/563557980
At the moment user signups for an account the `request.user` is an
Anonymous user (no email).
To track a `temba.org_signup` event we must use authenticated user
object.

Use authenticated user for events on Org.signup

---

temba/contacts/models.py
temba/contacts/tests.py

New world renders @contact as a simple number if they only have an anon id. Old world renders @contact.id as a simple number but @contact as a zero-padded value. PR makes anon ids always simple number values

#️⃣ Don't zero pad anon ids in context

---

pip-freeze.txt
temba/flows/tests.py

* Fixes `can't` matching `can` (https://github.com/rapidpro/expressions/pull/31)
* Fixes booleans in the context becoming ints (https://github.com/rapidpro/expressions/pull/32)

➗ Update to latest expressions

---

temba/msgs/tests.py
temba/orgs/tests.py
templates/smartmin/base.html

Stop embedding refresh code on pages that don't require it.
This fixes XSS issues on public facing pages.

🖍 Embed script only if `View.refresh` is set

---

temba/api/v2/fields.py
temba/api/v2/tests.py

Fixes https://sentry.io/nyaruka/textit/issues/691197682/

🦔 Fix validating URNField when input isn't a string

---

temba/orgs/views.py

We never validate input data like Org.name, User.first_name,
User.last_name and that creates opportunities for attackers to embed and
execute malicious code. We need to make sure that we escape such data
before using `mark_safe`

᯼ Escape data before using `mark_safe`

---

temba/utils/templatetags/temba.py
temba/utils/tests.py
templates/campaigns/campaignevent_update.haml
templates/contacts/contact_customize.haml
templates/contacts/contact_list.haml
templates/msgs/msg_send_modal.haml
templates/triggers/trigger_register.haml
templates/triggers/trigger_update.haml

The correct way to embed JS in templates is to use `escapejs` and
`JSON.parse` to read data.

ጪ Correctly embed JS in templates

---

.travis.yml
media/test_flows/migrate_to_11_5.json
temba/api/models.py
temba/flows/flow_migrations.py
temba/flows/models.py
temba/flows/tests.py
temba/utils/http.py

* Result value from webhook/resthook rulesets becomes status code 
* Response body is instead saved to `@extra.<result-name>`
* Flow migration to rewrite expressions involving `@flow.response_1` or `@flow.response_1.value` where `response_1` is from a webhook/resthook ruleset to use `@extra.response_1` instead

🌐 Webhook changes and latest goflow

---

templates/contacts/contact_list.haml

Fixes: https://sentry.io/nyaruka/rapidpro/issues/699941889/events/

⋇ Revert back to escapejs for contact group query

---

pip-freeze.txt

smartmin==2.0.2 has the fix for file_path truncation
Django==2.0.9 fixes a potential data loss bug
- https://docs.djangoproject.com/en/2.1/releases/2.0.9/

🈯 Bump Smartmin and Django versions

---

temba/flows/models.py
temba/flows/tests.py

Initially we have archived flow run.values as a list. Current archive
format uses a more natural object mapping. We need to support
flow run exports from archives and support the older format.

🌥 Fix flow results export to read old archive format

---

templates/contacts/contact_list.haml

After gating refresh function in base.html to prevent XSS attacks, we
broke Contacts.managefields modal. A successful contact field update is
going to refresh the PJAX content on the page.
Prevents: https://sentry.io/nyaruka/textit/issues/704642216/

🌤 Refresh Contacts.list after managing fields

---

temba/flows/flow_migrations.py
temba/flows/tests.py

Flow migrations shouldn't create groups, creates zombie groups on revision migration

Fix remap groups

---

temba/api/v2/tests.py
temba/api/v2/views.py

🌐 Fix passing false/true to archived param of flows API endpoint

---

temba/api/v2/fields.py
temba/api/v2/tests.py
temba/api/v2/views.py
temba/api/v2/views_base.py
temba/campaigns/tests.py
temba/campaigns/views.py
temba/contacts/models.py
temba/contacts/tests.py
temba/contacts/views.py
temba/settings_common.py
templates/campaigns/campaign_read.haml
templates/campaigns/campaignevent_read.haml
templates/contacts/contactgroup_delete.haml

This prevents users to delete contact groups that have active campaigns.
Initially we were only preventing users to delete contact groups that
had active triggers and active flows.
Two new actions, 'Activate' and 'Archive', have been added to the read
Campaign page. These actions enable users to quickly archive or activate
a campaign.
An archived campaign will get an "(Archived)" suffix to the title and
this is also visible on the read CampaignEvent page.
Gear actions depend on the *is_archived* status. For an archived
campaign we only show 'Activate' action, and for active campaign we show
'Add Event', 'Edit' and 'Archive' actions. CampaignEvent gear actions
for an archived campaign only allow users to delete a CampaignEvent.
Updates on the API endpoint for Campaign prevent users to …

🔩 Prevent deleting groups with active campaigns

---

temba/flows/models.py
temba/flows/tests.py

Fixes blow ups like https://sentry.io/nyaruka/rapidpro/issues/784092119/?referrer=alert_email

🧯 Make sure Flow.update clears prefetched nodes after potentially deleting them

---

temba/contacts/tests.py
temba/flows/tests.py
temba/flows/views.py

Added `AllowOnlyActiveFlowMixin` that filters flows on is_active=True.
This prevents users from accessing released flows through the Web view.
Archived flows are can't be started or edited.

🧼 Honour Flow.is_active on the Web view 

---

temba/flows/server/serialize.py
temba/flows/tests.py

The real fix here might be a rethink on mailroom simulation and where the editor should be pulling environment from, but this will get phone number tests working again in simulation...
Fixes https://app.intercom.io/a/apps/l6e7tr01/inbox/inbox/unassigned/conversations/20423530793

🏴󠁧󠁢󠁷󠁬󠁳󠁿 Include default country in serialized environments used for simulation

---

temba/orgs/models.py
temba/orgs/tests.py

Fixes Sentry error: https://sentry.io/nyaruka/textit/issues/863324930/
`.all()` method was deprecated in 2016 and replaced by a `list()` method
* https://github.com/stripe/stripe-python/blob/master/CHANGELOG.md#1280---2016-01-04

💦 Replace deprecated `all()` with `list()` method, Stripe Python API

---

temba/airtime/models.py
temba/api/models.py
temba/channels/models.py
temba/channels/types/twitter_activity/type.py
temba/channels/views.py
temba/contacts/models.py
temba/flows/models.py
temba/flows/views.py
temba/ivr/models.py
temba/middleware.py
temba/msgs/models.py
temba/orgs/models.py
temba/utils/export.py

This is more flexible because we utilize standard Python logging
framework to push exceptions to Sentry or log them to a file.

😽 Replace traceback.print_exc() with logger.error

---

temba/flows/tests.py
temba/flows/views.py

Allow posts to the simulation endpoint to include the definition to use during each sprint

🥄 Use provided flow definition when simulating

---

temba/api/support.py
temba/settings_common.py

Currently different dashboards can't honor the rate limit back downs because they don't know about each other

🚄 Throttle API endpoints by user 

---

static/coffee/simulator_go.coffee

Fixes when using @("")
Uncaught TypeError: Cannot read property 'text' of null
at window.renderSimEvent (c75858dca344.js:398)
at window.updateSimResults (c75858dca344.js:393)
at Object.<anonymous> (c75858dca344.js:393)
at fire (jquery.js:2913)
at Object.fireWith [as resolveWith] (jquery.js:3025)
at done (jquery.js:7400)
at XMLHttpRequest.<anonymous> (jquery.js:7822)

📶 fix simulator to field with empty value

---

temba/contacts/tests.py
temba/tests/base.py
templates/contacts/contact_read.haml

just noticed this from testing surveyor contacts who often don't have any identifying info

📛 Default page title when contact has no name or URN

---

temba/campaigns/models.py
temba/contacts/models.py
temba/contacts/tests.py
temba/flows/models.py
temba/msgs/models.py
temba/tests/base.py

Except in querysets - as we still need to hit db indexes that use `is_test=True`
Previously removed these from the engine components but not elsewhere.

🗑️ Remove remaining is_test checks

---

temba/contacts/models.py
temba/contacts/tests.py
temba/contacts/views.py

If query is invalid a user will see an error message.
Fixes: https://sentry.io/nyaruka/textit/issues/878003816/

🥴 Prevent users from updating dynamic groups if query is invalid

---

temba/channels/types/twilio/type.py

Older channels don't have this attribute set on them, so use the org setting instead.

🏵️ fallback to org domain when no channel domain set

---

temba/flows/__init__.py
temba/flows/checks.py
temba/flows/tests.py
temba/flows/views.py

Added a system check previously to error if STORAGE_URL wasn't set and now this one checks if MAILROOM_URL isn't set and warns you that you won't be able to do simulation.

⚠️ Show Django warning if mailroom URL not configured

---

temba/flows/models.py
temba/flows/tests.py
temba/msgs/tasks.py

* exits sessions in bulk exit when we are being interrupted (say from the user archiving a flow)
* ignores flow starts created by mailroom (null created_on) when figuring out if there is already a start

🎽 exit sessions in bulk exit, ignore mailroom flow starts

---

temba/api/v2/fields.py
temba/api/v2/serializers.py
temba/api/v2/tests.py
temba/api/v2/views.py
temba/api/v2/views_base.py

Act on the messages that exist, return the ids of those that don't

🥧 message_actions API endpoint should update messages that exist

---

temba/locations/models.py
temba/locations/tests.py
temba/locations/views.py

Not clear why the are even duplicated on the form but as first step prevent the duplicates to be inserted in the DB

🔢 Fix boundary aliases duplicates creation

---

temba/flows/models.py

Mailroom will take care of expirations (or the old task will for legacy flows). No change to unit tests needed because the update expirations task actually fires a check expirations task at the end of it.

do not immediately expire flow when updating expirations

---

temba/flows/server/tests.py
temba/locations/models.py
temba/locations/tests.py
temba/locations/views.py

Part 2 for https://github.com/nyaruka/rapidpro/pull/2358
Boundary unlike other models do not have an org field so their aliases should make sure the filter by org

🔢Really fix aliases duplicates displayed on the form

---

temba/utils/models.py

Theory of change:
* previous attempt at subselecting rows was actually slower since we already have a perfect index
* removing order by also simplifies things as postgres will just use the `_unsquashed` index which is already in the order we want.
In practice this does seem to work as well so there's that. :)

simplify squash in a way that seems to be faster

---

temba/contacts/search/parser.py
temba/contacts/tests.py

Closes: https://github.com/rapidpro/rapidpro/issues/868
Add support for `!=` operator for system fields: name and language, and
for contact fields that have: text, state, district or ward type.

🌹 Support != search operator

---

temba/flows/models.py
temba/flows/tests.py

Just making sure we always write uuid,name,etc to definitions and revisions with the values from the db.

update defs with db values both when writing and reading

---

static/coffee/flows/directives.coffee

Definitions are fine, but viewing them isn't.

🔥 View absolute attachments in old editor

---

temba/channels/types/whatsapp/tasks.py
temba/channels/types/whatsapp/tests.py
temba/channels/types/whatsapp/type.py
temba/channels/types/whatsapp/views.py
temba/settings_common.py

This is a first stab at making the WhatsApp template endpoints configurable as per https://github.com/rapidpro/rapidpro/issues/928

Make WhatsApp template endpoint configurable

---

temba/api/v2/tests.py
temba/campaigns/tests.py
temba/contacts/tests.py
temba/flows/tests.py
temba/orgs/models.py
temba/orgs/tests.py
temba/utils/json.py
temba/utils/tests.py

When using input parameter of type float for Decimal we get a memory
representation of that number which is 'correct' but confusing to users.
If value is a float, the binary floating point value is losslessly
converted to its exact decimal equivalent. This conversion can often
require 53 or more digits of precision. For example,
`Decimal(float('1.1'))`
converts to
`Decimal('1.100000000000000088817841970012523233890533447265625')`.
(https://docs.python.org/3.6/library/decimal.html#decimal-objects)
Fixes: https://github.com/rapidpro/rapidpro/issues/914

🔘 Ensure input is string in org.parse_number

---

temba/channels/models.py
temba/contacts/models.py
temba/contacts/tests.py
temba/flows/models.py
temba/flows/tasks.py
temba/flows/tests.py
temba/mailroom/queue.py
temba/mailroom/tests.py
temba/msgs/legacy.py
temba/msgs/models.py
temba/msgs/tasks.py
temba/msgs/tests.py
temba/settings_common.py
temba/utils/cache.py
temba/utils/queues.py

* Sends broadcasts by creating a mailroom task
* Uses a simplified send function to continue sending broadcasts in tests
* Simplify `Flow.start` to no longer use `start_msg_flow_batch`
* Removes `start_msg_flow_batch` celery task (flows queue should be empty now)
* Moves code only used by legacy engine to `temba.msgs.legacy`

📣 No more celery for starting flows and sending broadcasts

---

temba/contacts/models.py
temba/contacts/templatetags/contacts.py
temba/contacts/tests.py

Anon orgs didn't have any icon to give a clue on how a contact is communicating without this. Also formats the same as phone numbers for those orgs that AREN'T anon.

properly format whatsapp numbers and add icon

---

temba/contacts/models.py
temba/contacts/tests.py

If passed a key, `ContactField.get_or_create` should never return a field with a different key.
We have an import that is failing because we're trying to check that we have a field dependency, and it's matching by label, but against an existing field with a different key. Later on when we're doing final validation of the import, it fails because we still don't have a field with the right key: https://sentry.io/organizations/nyaruka/issues/956362836/?project=20737&query=is%3Aunresolved
One knock-on effect is that we're trying to create a key/label and the label matches but the key doesn't, then we need to modify the label to make it unique.

🧯Fix looking up fields by label

---

temba/api/v2/tests.py
temba/api/v2/views.py
temba/contacts/models.py
temba/contacts/omnibox.py
temba/contacts/tests.py
temba/contacts/views.py

- Group being imported into should be in `status=INITIALIZING` whilst being populated
- Hide such groups in the UI, don't return them from API, omnibox queries, etc

🚦 Don't make groups available until they're ready

---

temba/contacts/search/parser.py
temba/contacts/tests.py
temba/utils/dates.py
temba/utils/tests.py

Datetime contact fields are serialized in Org.timezone so we must also
search using timestamps in Org.timezone.
Contact.created_on is in UTC and search must also be in UTC

📠 Update search parser to convert timestamps into UTC

---

temba/api/v2/serializers.py
temba/api/v2/tests.py

i.e. from a `save_run_result` action

🧯 Fix API runs serializer when result doesn't have category

---

temba/ivr/tasks.py

Gates all IVR tasks with TESTING until they are ripped out entirely. These are all handled within Mailroom now and these firing was causing issues for calls that failed in Mailroom for one reason or another.

🔥 disable ivr tasks

---

temba/channels/models.py
temba/channels/tests.py

Mailroom doesn't look at org configs, only channel configs (that way people can have multiple twilio accounts connected if they wanted in the future)
This sets the appropriate config options for callers when created off of the org settings.

🔥  populate account sid and and auth token on twilio callers when added

---

temba/utils/__init__.py
temba/utils/tests.py

than the current context precision. Fixes https://sentry.io/organizations/nyaruka/issues/1105935574/?project=21956&referrer=alert_email which is currently breaking upartners syncing
I think what's happening here is that the postgres JSON adapter is giving us a decimal with more digits (not sure how it got there in the first place) than `getcontext().prec`.. so then `quantize` blows up. Tried finding a way to reduce the precision but the only thing I could get to work was just letting `Decimal.__format__` decide how it should be formatted.

🧮 Fix format_number to be able to handle decimals with more digits 

---

package-lock.json
package.json

* Split by urn fixes #677
* Fallback for bad urn split migrations
* Add generic key localization form for send email #674
* Fix vulnerabilities with npm audit

Update floweditor to 1.6.7

---

temba/api/v2/tests.py
temba/flows/legacy.py
temba/flows/models.py
temba/flows/tests.py
temba/msgs/tests.py
temba/orgs/tests.py
temba/utils/management/commands/test_db.py
temba/utils/tests.py

* Reworks some more tests to not use legacy engine
* Remove `FlowStart.start` so there's only `FlowStart.async_start` which queues to mailroom or invokes a simplified legacy version for tests
* Don't update `FlowStart.contact_count`

🧹 Remove some more use of legacy engine in tests

---

.travis.yml

I was wrong in previous PR that switched to bionic on Travis, Python is 3.6.8 on Bionic Beaver, not 3.7.

switch to python verson on bionic (3.6.8)

---

.coveragerc
.coveragerc_todo
temba/auth_tweaks/migrations/0002_ensure_anon_user.py

Would mean you have to write a migration test for your new data migration or accept the shame of covering it with `#pragma: no cover`

🧪 Include migrations in coverage checks?

---

.travis.yml
temba/channels/types/nexmo/client.py
temba/channels/types/nexmo/tests.py

Fixes https://sentry.io/organizations/nyaruka/issues/1142731925/?project=21956 (which was me testing stuff)

🛡️ Releasing Nexmo channel shouldn't blow up if API call fails

---

temba/schedules/migrations/0010_populate_days_of_week.py
temba/schedules/tests.py

Prod boxes already updated so no rush to ship or anything.

add populating repeat_minute_of_hour to migration

---

templates/flows/flow_create.haml

Wasn't tall enough when language was shown, causing scroll bars and dual scrolling for me and just invisible scroll bars for rest.

fix styling on create flow dialog

---

temba/msgs/tasks.py
temba/msgs/tests.py
temba/settings_common.py

Only retries explicit errors so no danger of walking on mailroom. Long term this should live in Courier.

add task to retry errored messages

---

templates/orgs/org_chatbase.haml
templates/orgs/org_country.haml
templates/orgs/org_edit.haml
templates/orgs/org_nexmo_account.haml
templates/orgs/org_smtp_server.haml
templates/orgs/org_transfer_to_account.haml
templates/orgs/org_twilio_account.haml
templates/orgs/user_edit.haml

Addresses https://github.com/rapidpro/rapidpro/issues/1052 
These are the views used by the formax which really need the block super to that the formax container includes a form with CSRF token

Add missing block super in extra script blocks

---

temba/contacts/fields.py
temba/msgs/views.py
temba/triggers/tests.py

The JS error was Chrome being mad because it was trying to do client side validation on a hidden field and couldn't show the error message that nothing was in there. (omnibox puts its values in a hidden input field)
This fixes to render as not required (IE, the hidden field isn't required) and additionally properly validates that the field is populated when required. (this was broken and only client side validation was taking place)
fixes: https://github.com/rapidpro/rapidpro/issues/1032

fix omnibox required behavior

---

temba/api/v2/serializers.py
temba/api/v2/tests.py
temba/contacts/models.py
temba/contacts/views.py

We had two concepts of max # of fields, a constant on ContactField and a setting.
This just changes us to use the setting everywhere. Fixes: https://github.com/rapidpro/rapidpro/issues/985

🇲🇰  unify max contact fields

---

templates/utils/forms/omnibox_choice.haml

I don't believe this affects the user outside of a console error. 
Passed objects as attributes should be removed if empty
https://lit-element.polymer-project.org/guide/properties#conversion

Fix omnibox console error

---

templates/contacts/contactfield_list.haml

 🛩  smaller field names

---

templates/triggers/trigger_schedule.haml

fixes: https://github.com/rapidpro/rapidpro/issues/1068
but note that: https://github.com/rapidpro/rapidpro/issues/1069 remains.
Fought with that a bit and ya, maybe we should find a new datetime picker. @ericnewcomer want to try? :)

fix weekly buttons resetting on form validation

---

temba/schedules/migrations/0010_populate_org.py
temba/schedules/migrations/0011_populate_days_of_week.py
temba/schedules/migrations/0012_auto_20190930_1347.py

Hi everyone, I'm opening this PR because of the `schedules.0011_populate_org` migrate must be first then `schedules.0010_populate_days_of_week`. When migrating populate_days_of_week first, all schedules objects hasn't been orgs associated yet.
Thanks a lot for your attention.
Regards

Fix order for migrations on schedules

---

temba/flows/tests.py
temba/tests/base.py
temba/tests/matchers.py

Root of the issue here is that goflow event times are always sequential, so for a `msg_received` event, it's going to be close to the msg time, but not necessarily the same. And for flow result exports, we don't use real msgs from the database - we msg events on the run.
Sorry to everyone who can't see the emoji... it's so cute 🤷‍♂

🦦 Fix intermittently failing excel export tests

---

temba/classifiers/types/bothub/tests.py
temba/classifiers/types/bothub/type.py
temba/utils/management/commands/mailroom_db.py

Hi @nicpottier , I open this PR, to create a Bothub classifier object in the database. When running tests for the mailroom, get a list and verify if Bothub classifier type exists.
Thanks a lot for your attention.
Regards

Add Bothub classifier on mailroom_db

---

temba/orgs/views.py

"host" is the whitelabel install (textit / rapid), brand is what we are really after here.

use brand when granting orgs, not host

---

temba/mailroom/client.py
temba/mailroom/tests.py
temba/orgs/models.py

The latter is from when we were stuffing validation results inside flow definitions

🔧 Replace flow/validate mailroom call with flow/inspect

---

temba/flows/models.py
temba/flows/tests.py
temba/flows/views.py
temba/mailroom/client.py

Started on https://github.com/rapidpro/rapidpro/issues/1123 and then realised I'm touching the same code as https://github.com/nyaruka/rapidpro/pull/2648 needs to be updated to change..
So making this as a precursor PR to both of those. `Flow.GOFLOW_VERSION` currently has two meanings and will have soon have two values - so replaced that with two different constants.

Split Flow.GOFLOW_VERSION into 2 more useful constants

---

temba/api/v2/tests.py
temba/locations/models.py
temba/locations/tests.py
temba/orgs/models.py
temba/tests/base.py

Fixes https://github.com/rapidpro/rapidpro/issues/1122 and deleting an org with a boundary alias

🧯 Fix deletion of orgs and locations so that aliases are properly deleted

---

temba/flows/tests.py
temba/flows/views.py
templates/flows/flow_results.haml

If you want a contact's results, go to their contact page.

Remove contact filtering from flow results page

---

.travis.yml
temba/contacts/tests.py
temba/mailroom/client.py
temba/mailroom/tests.py

Changing the name of this in mailroom to match other endpoints and also because it's not really for validation anymore: https://github.com/nyaruka/mailroom/blob/master/web/flow/flow.go#L79

🔧 Test against latest mailroom

---

temba/channels/models.py
temba/channels/types/external/tests.py
temba/channels/types/external/type.py
templates/channels/types/external/claim.haml

This PR is related to enabling quick replies on Courier's external channel: https://github.com/nyaruka/courier/pull/275

Display quick replies option on external channel claim/config

---

temba/airtime/tests.py
temba/api/tests.py
temba/api/v2/tests.py
temba/archives/tests.py
temba/assets/tests.py
temba/campaigns/tests.py
temba/campaigns/views.py
temba/channels/tests.py
temba/channels/types/android/tests.py
temba/classifiers/tests.py
temba/contacts/tests.py
temba/contacts/views.py
temba/flows/legacy/tests.py
temba/flows/tests.py
temba/locations/tests.py
temba/msgs/tests.py
temba/orgs/tests.py
temba/public/tests.py
temba/request_logs/tests.py
temba/tests/base.py

* Fix campaign events not being protected by org
* Every test runs with two orgs in the database
* More testing with objects belonging to the other org
* Replace `_CRUDLTest` based tests with regular `TembaTest`

🔒 More testing with another org

---

templates/api/v2/api_explorer.haml

E.g. flow_starts because you can create but you can't update: https://app.intercom.com/a/apps/l6e7tr01/inbox/inbox/155936/conversations/26086593136

🔥 Fix for API explorer endpoints that have a body editor but not a query string editor

---

temba/flows/models.py
temba/flows/tests.py
temba/flows/views.py

At very least then we can read this in the browser console

🆘 Return validation errors from engine as detail field

---

temba/locations/models.py
temba/locations/tests.py
temba/locations/views.py

API does not use `as_json` so it is good

Fix boundary aliases filtering by org

---

temba/flows/models.py
temba/flows/tests.py

We have a TODO to drop some fields on `FlowStart` that we no longer use but can't do that until we've removed the last usage.

Stop using FlowStart.modified_by so that it can be removed

---

temba/flows/models.py
temba/flows/tests.py
temba/flows/views.py

Legacy flows use metadata as an ever accumulating bod, new flows have been just setting this to the output of flow inspection. 
Best I can tell the only thing mailroom expects to be able to read from metadata is `ivr_retry`.. so need to make sure we preserve that.
You can observe this problem if you change `ivr_retry` on an IVR flow, then do anything to trigger an editor save, and the previous value will be lost.

🏺 Ensure ivr_retry value is preserved when saving revisions

---

temba/flows/models.py

API flow_starts endpoint calls `FlowStart. async_start` directly instead of `Flow.async_start` like the broadcast view

💒 Ensure flow starts created via the API are only sent to mailroom after commit

---

.travis.yml
code_check.py

Digging into why [this Transifex PR](https://github.com/rapidpro/rapidpro/pull/1201) is failing and it seems they now word wrap generated PO files to 79 (?) chars so..
```
msgid "This URL should be called by ArabiaCell when new messages are received."
```
becomes
```
msgid ""
"This URL should be called by ArabiaCell when new messages are received."
```
and our approach of using grep to find significant differences fails because it's just comparing lines starting with  `msgid`

🌐 Use actual PO library to check for msgid differences

---

code_check.py

We don't use this it for any of the new frontend stuff so there's no point in creating new versions of djangojs.po files that just have date header changes

🔧 code_check.py doesn't need to check for changes in djangojs.po

---

temba/campaigns/views.py
temba/contacts/views.py
temba/flows/views.py
temba/msgs/views.py
temba/triggers/views.py

I think early on we hadn't figured out how to pass CSRF tokens globally through our JS HTTP calls. We now do that so all of these action views being exempt is not needed. (and a theoretical security risk). 
Tested locally, will test on staging too before we go out live but tokens are definitely being sent.

Remove csrf exemption for views that don't need it

---

templates/includes/nav.haml

@ericnewcomer the logic for whether the dashboard/android nav icons are displayed was changed (I assume inadvertently) in https://github.com/nyaruka/rapidpro/commit/fed9072f89108a93130d4074ac44e07f57ab0ca3#diff-f7eddc65257916aab23541ef0fe91a3e
Causing https://app.intercom.com/a/apps/l6e7tr01/inbox/inbox/conversation/27385925560
but also the ordering.. was that intentional?

🤖 Restore logic for when dashboard and android nav icons should appear

---

temba/flows/models.py

If for some reason some older runs stick around due to the archiver failing to create/delete them, exports can get horked as we use most recent archive to determine which "live" run ids to include in the export.
Notwithstanding archiver fix that is needed, this switches to using a set of run ids that have been "seen" doing the archive export and excludes those one by one as they come up.

Instead of dates, keep track of seen runs when excluding runs

---

temba/mailroom/queue.py
temba/mailroom/tests.py

These can then be picked up by mailroom and added to the trigger as `user` and `origin`

🏁 Add start_type and created_by to queued flow starts

---

temba/api/v2/serializers.py
temba/api/v2/tests.py
temba/campaigns/tests.py
temba/contacts/models.py
temba/contacts/tests.py
temba/contacts/views.py
temba/tests/mailroom.py
temba/utils/management/commands/mailroom_db.py

Still can't get rid of campaign event re-evaluation in RP (imports), but this gets rid of it in the case of group membership changes.

👪 Always use mailroom for group changes

---

locale/en_US/LC_MESSAGES/django.po
locale/es/LC_MESSAGES/django.po
locale/fr/LC_MESSAGES/django.po
locale/pt_BR/LC_MESSAGES/django.po
locale/ru/LC_MESSAGES/django.po
temba/contacts/search/parser.py
temba/contacts/search/tests.py
temba/contacts/tests.py
temba/tests/mailroom.py

Addresses https://github.com/rapidpro/rapidpro/issues/1289. For example:
becomes
and can be localized.

🐕‍🦺 Add error messages for all error codes from mailroom query parsing

---

.travis.yml
temba/campaigns/tests.py
temba/contacts/models.py
temba/contacts/search/parser.py
temba/contacts/search/tests.py
temba/contacts/tests.py
temba/contacts/views.py
temba/orgs/tests.py
temba/tests/mailroom.py

The search/parse mailroom endpoints always returned `fields` which was a mixture of contact fields, attributes and schemes which RP then had to sort out, but a while we ago we added a more detailed metadata blob more like what you get from flow flow inspection. This is switching the RP calling code to use that, tho ended up having to cleanup how we do mocking of searching in general.

🔍 Use newer metadata field from mailroom search endpoints

---

temba/archives/models.py
temba/tests/s3.py
temba/utils/s3.py
temba/utils/s3/__init__.py
temba/utils/s3/s3.py
temba/utils/s3/tests.py

I naively assumed the payloads returned in the event stream from S3 select calls would contain batches of whole JSONL records, but they're actually just chunks of 65K bytes, so requires some care reconstructing those into the original records.

🚰 Fix reading of S3 event streams

---

temba/campaigns/tests.py
temba/contacts/models.py
temba/contacts/tests.py

Doh https://sentry.io/organizations/nyaruka/issues/1839182650/?project=28903&referrer=alert_email
I was thinking last_seen_on can only be modified inside mailroom so didn't have to worry about RP's legacy campaign event scheduling code but of course when you create/update a campaign event, so have to re-evaluate fires for all contacts in the campaign group and that happens in RP.
This is the immediate fix but sooner than later we should move that task to mailroom. It takes a campaign event and re-calculates all fires.

⌚ Fix creating of campaign events based on last_seen_on

---

templates/frame.haml

Part of https://github.com/nyaruka/floweditor/issues/898

Use Django language code on html tag

---

temba/contacts/tests.py
temba/utils/models.py
temba/utils/tests.py

Fixes https://github.com/rapidpro/rapidpro/issues/1323 tho please note doesn't fix other problem of ES search results not reflecting changes just made.
This however fixes bulk actions that don't effect whether a contact should be in the current search - e.g. adding and removing from groups as long as the search query doesn't mention those groups

🔎 Fix bulk actions against querysets from ES searches

---

temba/contacts/models.py
temba/contacts/search/parser.py
temba/contacts/tests.py

Turns out yes you can end up evaluating a dynamic group with last_seen_on because the contact create code is still using legacy searching for dynamic groups: https://sentry.io/organizations/nyaruka/issues/1867955474/?project=20737&referrer=alert_email

🤦 Add support for last_seen_on in legacy search code

---

temba/middleware.py
temba/policies/views.py
templates/policies/policy_list.haml

Fixes bug whereby new users landing on the welcome page have not yet accepted policies but can open modals on that page that do not handle policy redirects gracefully.
* Force policy redirect on welcome page
* Add support for "next" for policy redirects to retain user navigation intent
A follow-on to this would be determine why in this case the redirect is not breaking out of the modal.

Policy redirect bug

---

templates/flows/flow_editor.haml

Focus and borders on the old editor look bad. Even though it's gone in a month, this is worth fixing.

Update widget focus and borders on legacy editor

---

temba/api/v2/serializers.py
temba/api/v2/tests.py

In the engine, these obviously don't have to be an org language, but they are expected to be a valid ISO639-3 language

🌐 Validate language codes as ISO639-3 on API endpoint

---

templates/contacts/contactfield_list.haml

Fix margin on fields warning alert

---

temba/orgs/tests.py
temba/settings_common.py

They have all the other permissions, just can't get a token from the workspace settings page.

🍪 Editors should have API tokens

---

temba/orgs/models.py
temba/orgs/tasks.py
temba/orgs/tests.py
temba/settings_common.py

Takes care of checking orgs with topups every hour to see if they should be suspended. Also flips them back from being suspended when topups are added.

💵 Suspend topup orgs that have no active credits

---

temba/airtime/tests.py
temba/api/v2/tests.py
temba/campaigns/tests.py
temba/channels/tests.py
temba/channels/types/jiochat/tests.py
temba/channels/types/telegram/tests.py
temba/channels/types/twitter/tests.py
temba/channels/types/wechat/tests.py
temba/channels/types/whatsapp/tests.py
temba/contacts/tests.py
temba/dashboard/tests.py
temba/flows/legacy/definition/tests.py
temba/flows/legacy/tests.py
temba/flows/management/commands/tests.py
temba/flows/tests.py
temba/ivr/tests.py
temba/mailroom/tests.py
temba/msgs/tests.py
temba/orgs/tests.py
temba/schedules/tests.py
temba/tests/base.py
temba/tickets/tests.py
temba/triggers/tests.py
temba/utils/tests.py

Rather than cover it in `#pragma: no cover` I want to drop that method in #2986 but there is a bunch of test code using - so this PR cleans that up to avoid making that other PR's diff any crazier.

Remove usage of Contact.get_or_create_by_urns from tests

---

temba/api/v2/tests.py
temba/campaigns/tests.py
temba/contacts/models.py
temba/contacts/tests.py
temba/flows/legacy/definition/actions.py
temba/flows/tests.py
temba/msgs/tests.py
temba/utils/management/commands/mailroom_db.py

Removes triggering of `Contact.handle_update` from `Contact.save` since there are no longer any places where modifying a contact should trigger group/campaign evaluation in RP (still same places using `Contact.get_or_create` but it does it explicitly)

Remove update handling from contact.save

---

temba/api/v2/serializers.py
temba/campaigns/models.py
temba/campaigns/tests.py
temba/campaigns/views.py

Not queue them to mailroom for scheduling - which is the source of all the "campaign event not found" sentry errors

🗑️ Archiving a campaign should only recreate events

---

temba/api/v2/tests.py
temba/api/v2/views_base.py

If you POST to this endpoint with a URN that doesn't exist we actually let you create a contact with that URN - however to know if that URN doesn't exist, we need to normalize it with the org country. Otherwise if a user POSTS a local tel number, the lookup fails to find that contact, but then mailroom errors trying to create that contact.

☎️ URN lookups on the contact API endpoint should be normalized with org country

---

temba/api/v2/serializers.py
temba/api/v2/tests.py
temba/api/v2/views.py
temba/globals/models.py

* Filter by is_active when updating fields on API endpoint to fix https://sentry.io/organizations/nyaruka/issues/1939081165/?project=20737
* Require name when creating globals to fix https://sentry.io/organizations/nyaruka/issues/1913245478/?project=20737

🏑 Fields and globals API fixes

---

temba/api/v2/serializers.py
temba/api/v2/tests.py
temba/api/v2/views.py
temba/mailroom/tests.py

From looking in the logs I can't see anyone passing expressions over these endpoints so suspect users don't even know they can. Addresses https://github.com/rapidpro/rapidpro/issues/1359

🚿 Drop support for migrating legacy expressions on API endpoints

---

temba/channels/types/rocketchat/client.py
temba/channels/types/rocketchat/tests.py
temba/channels/types/rocketchat/type.py
temba/channels/types/rocketchat/views.py

Should use Channel.callback_domain instead of trying to resolve request URI

Fix and simplify rocketchat callback URL generation

---

temba/contacts/models.py
temba/contacts/tests.py

We export using labels which aren't necessarily in sync with keys. If we don't match the key then we can end up trying to create a field with the same name, so name gets a number appended and we end up with https://sentry.io/organizations/nyaruka/issues/2005139819/?project=20737&referrer=alert_email

🧯 Match headers and contact fields with labels as well as keys during imports

---

templates/orgs/org_choose.haml

No org warning is always shown

🧯 Fix choose org page

---

temba/contacts/models.py
temba/contacts/tests.py

Fixes https://sentry.io/organizations/nyaruka/issues/2064518360/?project=21956&referrer=alert_email

🧯 Fix contact exports when orgs only have orphaned URNs in a given scheme

---

temba/api/v2/tests.py
temba/contacts/tests.py
temba/flows/tests.py
temba/locations/tests.py
temba/msgs/tests.py
temba/orgs/models.py
temba/tests/base.py

Where this really makes difference to query counts is pages like the org home page where it shaves off ~70 queries but we don't have any tests for that.

🐘 Cache lookups of auth.Group instances

---

temba/channels/types/external/views.py

By customers request, they have an external channel that wants to take messages longer than 640.
WhatsApp already is way up there (4096) so I think this is safe.

increase max length on external channels to be configurable up to 6400

---

media/test_flows/dependencies_v13.json
temba/flows/models.py
temba/flows/tests.py

We weren't checking ticketer or classifier deps during import so references to these were getting new random UUIDs, which is not the end of the world as part of a cross-org-import since they're mostly likely broken dependencies anyway, but wrong if it's a clone that going thru the import code.

🏥 Fix importing dependencies when cloning in same workspace

---

.github/workflows/ci.yml
media/test_flows/background.json
package-lock.json
package.json
temba/api/v2/serializers.py
temba/flows/models.py
temba/triggers/tests.py
temba/triggers/views.py

I think it's correct to say the only trigger type than use a background flow is a scheduled trigger. Anything else involves input from the the contact, which then get's weird if there's an waiting session because it's not interrupted but it also doesn't see the input which would have been used to resume it.
I think we also want to allow background flows for campaign events but that requires a little more thought: https://github.com/rapidpro/rapidpro/issues/1423

🤫 Background flow fixes

---

temba/msgs/models.py
temba/msgs/tests.py
templates/msgs/label_delete.haml

Replace https://github.com/nyaruka/rapidpro/pull/3106 
We only delete a folder when it has no msg labels

Allow only deleting msg folders without active children labels

---

package-lock.json
package.json

* Allow expressions in add labels form
* CurrencyElement fix for airtime router
* Bump axios from 0.19.0 to 0.21.1 (security)
* Fix prod build include generation
* Bump socket.io from 2.3.0 to 2.4.1 (security)
* Update to newer version of open-wc/testing-karma
* New contact list, temba list, block options, and others for agents
* Modax hide on redirect

Update components and editor to latest versions

---

temba/utils/dates.py
temba/utils/tests.py

Now that all prod boxes will make requests with microseconds, this isn't used

🕰️ Remove no longer needed support for parsing millisecond timestamps

---

temba/middleware.py
temba/settings_common.py

Was looking at making some optimizations around permission checking but first wanted to simplify the current set of middlewares so that we have...
* `OrgMiddleware` - responsible for determining the org and setting it on the request/response
* `TimezoneMiddleware` - responsible for setting the timezone (currently just based on org but might one day be based on user)
* `LanguageMiddleware` - responsible for setting the language (currently just based on user but might one day look for default on org)

🧹 Middleware cleanup

---

templates/channels/channel_read.haml

Fixes https://github.com/rapidpro/rapidpro/issues/1439. New Android channel currently looks like...
Now like..
Or if you add a name, like...

📺 Fix rendering of nameless channels

---

temba/channels/tests.py
temba/channels/views.py

Return error instead of https://sentry.io/organizations/nyaruka/issues/2234386424/?project=21956&referrer=alert_email

Fix handling of attempts to sync old unclaimed channels

---

templates/channels/channellog_log.haml

add spacing between individual channel log events

---

temba/channels/tests.py
temba/channels/types/zenvia/tests.py
temba/channels/types/zenvia/type.py

The current integration is broken as the API has changed.
So hide that until we add support on the new API

Disable old zenvia

---

temba/orgs/tests.py
temba/orgs/views.py

Couple of times have seen errors like https://sentry.io/organizations/nyaruka/issues/2277034731/?project=21956&referrer=alert_email which I think happen when more than one user is editing users at the same time, thus a new user exists at form submission time who didn't exist when form was rendered.

👪 Fix manage accounts form blowing up used by multiple users at same time

---

pip-freeze.txt

Looks like this was the issue I was running into with casepro and the error message about not being able to load the beat schedule db was completely misleading

Upgrade to latest celery 4.x to fix issue with redis 3.x client

---

temba/channels/types/whatsapp/tests.py
temba/channels/types/whatsapp/type.py

All the other places we use the v3.3 are for the old Facebook type we no longer use

Update to use latest API version to get WA templates

---

temba/utils/models.py
temba/utils/tests.py

It's easy enough to migrate a `JSONAsTextField` field to `JSONField` as long as there's no invalid JSON in that DB column - however if you have two boxes to deploy to, the one still using `JSONAsTextField` needs to be able to work with a DB column which is now real JSONB.

🥛 Tweak JSONAsTextField to allow DB column to be migrated to JSONB

---

temba/flows/models.py
temba/flows/tests.py
temba/flows/views.py

Noticed we show fields like expiration time / ignore triggers for flows types like surveyor and background

📝 Fix flow update forms to show correct fields based on flow type

---

templates/flows/flow_results.haml

In page sort was causing issues when results in the first 3 were re-ordered. This sort should really be flow order anyways so I just removed the alpha sort that was causing this issue. If we want to do alpha instead of flow order, it's easy to sort this in the view context instead.

Show results in flow order

---

temba/utils/analytics.py
temba/utils/tests.py

Proper solution is to check is_authenticated instead of is_anonymous as mentioned on  https://docs.djangoproject.com/en/3.2/ref/contrib/auth/#django.contrib.auth.models.User.is_anonymous
And fixes https://sentry.io/organizations/nyaruka/issues/1532503323/

Proper skip anonymous user for analytics

---

temba/orgs/models.py

We delete the language foreign keys so have to clear it when we save the org.

Clear primary language

---

temba/utils/models.py
temba/utils/tests.py

Probably ultimately want the editor to strip these and make trying to save a flow definition with them (or inspect it), an error.

🔧 Strip out NULL characters when serializing JsonAsTextField values

---

temba/flows/models.py
temba/flows/views.py

Flow metadata is a BOD right now of things that come from mailroom, from the RP UI, things that are persisted, things that are calculated on the fly.. so pulling out issues as a separate thing to help clarify that that is now a thing which we always calculate on the fly.
Obviously for backward compatibility they're still being saved into metadata and returned to the editor there - but after we merge https://github.com/nyaruka/floweditor/pull/994 we can clean that up.

🍂 Fetching and saving revisions should return flow issues as separate field

---

temba/flows/models.py
temba/msgs/models.py
temba/orgs/models.py
temba/orgs/tests.py
temba/tests/base.py

* handle broadcasts with parents (https://sentry.io/organizations/nyaruka/issues/2398445632/?environment=production&project=20737)
* handle webhook results with contacts (https://sentry.io/organizations/nyaruka/issues/2398213753/?environment=production&project=20737)
* don't trigger mailroom session interruption during org deletion (https://sentry.io/organizations/nyaruka/issues/2398318703/?environment=production&project=20737)
There's also a problem with msg labels used by flows but I want to fix that separately as part of work on flow dependencies.

🔨 Org deletion whack a mole

---

package-lock.json
package.json
static/css/tailwind.css
static/scss/tailwind.scss
templates/includes/recipients_contact.haml

* Switch badge buttons to use flexbox to ensure icon centering. 
* Update icon color to match text.
* Have single recipient use `temba-icon` instead of `.icon`
* Add missing deps for `npm tw-build`
Fixes: https://github.com/rapidpro/rapidpro/issues/1490

Update layout and color for badge buttons

---

temba/campaigns/views.py
temba/flows/views.py
temba/orgs/views.py
temba/triggers/views.py

Just noticed that in 3 places we define the same utility mixin to filter the view queryset by org.. so moving that into `temba.org.views`

🧹 Simplify org filtering on CRUDLs

---

temba/mailroom/client.py
temba/mailroom/tests.py

I think this is another one from when we removed simplejson.. fixes https://sentry.io/organizations/nyaruka/issues/2420898690/?environment=production&project=21956
Also fixes for calls to flow/change_language endpoint

🧯 Fix migrating flows who's definitions contain decimal values

---

templates/campaigns/campaign_list.haml

Nest group buttons on campaign list so they don't grow to largest cell

Fix campaign group buttons

---

package-lock.json
package.json
static/css/temba-components.css

Looks like latest chrome won't let you override custom css properties defined on `:host`. This moves all host defined defaults to the main config and removes them from the individual components.

Fix icon colors on latest chrome

---

templates/triggers/trigger_create_schedule.haml

Refactoring schedule forms is proving trickier than I thought so here's the quick fix..

🧯 Fix creating scheduled triggers not being able to see weekday options

---

temba/mailroom/queue.py
temba/mailroom/tests.py

Mailroom will load the actual user to pass to goflow as an asset

🔧 Tweak queuing of flow starts to include created_by_id

---

temba/contacts/tests.py
temba/mailroom/client.py
temba/mailroom/tests.py
temba/orgs/tests.py
temba/tests/mailroom.py
temba/tickets/models.py
temba/tickets/tests.py
temba/tickets/views.py

Better to have everything that changes tickets in one place. When we add notifications for ticket events it will live in mailroom.

📬 Use mailroom endpoints for ticket assignment and notes

---

.coveragerc
.coveragerc_todo
code_check.py
temba/utils/management/commands/sync_transifex.py

Adds a command to rebuild messages and pull translations from transifex...
```
./manage.py sync_transifex --token=12345678901234567890
fetching translation for pt-br..
> checking for download...
> downloading translation...
> locale/pt_BR/LC_MESSAGES/django.po updated
fetching translation for fr..
> checking for download...
> downloading translation...
> locale/fr/LC_MESSAGES/django.po updated
fetching translation for es..
> checking for download...
> downloading translation...
> locale/es/LC_MESSAGES/django.po updated
fetching translation for ru..
> checking for download...
> downloading translation...
> locale/ru/LC_MESSAGES/django.po updated
mo files updated
```
So no rebuilding any locale files for PRs - just when anything is merged into rapidpro/rapidpro, we run this.

📯 Don't check locale files, add command for manual syncing

---

temba/triggers/models.py
temba/triggers/tests.py
temba/triggers/types.py
temba/triggers/views.py

Initially it seemed nice to group some trigger types together into folders but we need type specific list pages if we're to make triggers manually sortable.

🧬 Replace trigger folders with type specific filtered list pages

---

temba/flows/tests.py
temba/flows/views.py
temba/orgs/tests.py
templates/flows/flow_broadcast.haml

I think these are sufficiently different (even the order is different) that we can get away with changing them and trust users to read the labels/help text. Intentionally avoiding the word "active" as that has a different meaning now.
Also has workaround for bug where we don't show errors for the query box (see https://github.com/nyaruka/temba-components/issues/103) by making that a non-field error. Tho still affected by this bug https://github.com/nyaruka/temba-components/issues/102 which renders error messages for omnibox field twice.

🎬 Rework flow start modal to show options as exclusions

---

temba/orgs/models.py
temba/orgs/tests.py

Re-saves `Flow.has_issues` on final flow inspection at end of import process

🕵️‍♂️ Fix issues on imported flows

---

static/css/tailwind.css
static/js/formax.js
static/scss/tailwind.scss
temba/api/models.py
temba/api/urls.py
temba/api/views.py
temba/formax.py
temba/orgs/tests.py
temba/orgs/views.py
temba/settings_common.py
templates/formax.haml
templates/orgs/org_resthooks.haml
templates/smartmin/modal.haml

All formax open sections now a tad wider:
But now there's a wider option to accommodate the zapier widgets (also now using the new zapier app directory with popular textit zaps):

Update to zapier app directory, wide formax option and fixes

---

temba/campaigns/tests.py
temba/campaigns/views.py

Not entirely sure how because the dropdowns in the UI always show something, but we've let a few events be created with blank start_mode values that then blow up when we fire them https://sentry.io/organizations/nyaruka/issues/2571945045/?project=1281372&referrer=alert_email

📅 Prevent saving of campaign events without `start_mode`

---

temba/utils/languages.py
temba/utils/tests.py

Fixes https://github.com/rapidpro/rapidpro/issues/1551

Override `kir` language name

---

temba/api/v2/tests.py
temba/mailroom/client.py
temba/mailroom/tests.py
temba/orgs/views.py
temba/tests/mailroom.py
temba/tickets/models.py
temba/tickets/tests.py
templates/tickets/ticketer_read.haml
templates/tickets/types/zendesk/configure.haml

You should always be able to remove a ticketer even if it's horked

🙉 Pass `force=True` when closing tickets as part of releasing a ticketer

---

temba/request_logs/tests.py
temba/request_logs/views.py
temba/settings_common.py
temba/tests/crudl.py
temba/tickets/tests.py
templates/tickets/ticketer_read.haml

Not sure why we don't let admins view these since we're going to the trouble of redacting them on the engine side...

Make ticketer HTTP logs accessible to org admins

---

temba/flows/tests.py
temba/flows/views.py
templates/flows/flow_editor.haml

Starting looking adding this on editor side and seemed to make more sense to add this as a feature flag based on country being set. That way any orgs already using locations still see the functions, but no new orgs can enable location support on brands where we don't support it.

📍 Pass location support flag to editor as a feature flag

---

templates/frame.haml
templates/smartmin/base.html

Still need to determine what changed to cause this, but definitely found where we had cascade registration for triggering refreshes. Moved a couple things from the extra-script which is loaded on every pjax completion up the chain so they only ever load once.

Move list refresh registration out of content block

---

temba/tests/s3.py
temba/utils/s3/select.py
temba/utils/s3/tests.py

```sql
SELECT s.* FROM s3object s WHERE s.created_on > CAST('2021-09-28T18:27:30.123456+00:00' AS TIMESTAMP)
```
becomes
```sql
SELECT s.* FROM s3object s WHERE CAST(s.created_on AS TIMESTAMP) > CAST('2021-09-28T18:27:30.123456+00:00' AS TIMESTAMP)
```

Fix S3 select query generation for date fields

---

temba/api/v2/tests.py
temba/api/v2/views.py

Every other endpoint calls this param just `uuid`

Tweak tickets API endpoint to accept a `uuid` URL param

---

temba/assets/models.py
temba/campaigns/models.py
temba/classifiers/types/wit/client.py
temba/contacts/models.py
temba/contacts/views.py
temba/flows/legacy/__init__.py
temba/flows/models.py
temba/flows/views.py
temba/mailroom/client.py
temba/mailroom/modifiers.py
temba/msgs/models.py
temba/orgs/tests.py
temba/tests/mailroom.py
temba/tests/matchers.py
temba/tests/s3.py
temba/tests/twilio.py
temba/utils/__init__.py
temba/utils/export.py
temba/utils/http.py
temba/utils/management/commands/perf_test.py
temba/utils/management/commands/test_db.py
temba/utils/models.py
temba/utils/s3/s3.py
temba/utils/urns/urns.py

Just a little cleanup..
* Classes don't need to inherit from `object` (Python 3+)
* Can use `list`, `dict` etc instead of `Dict`, `List` (Python 3.9+)
* `str.removeprefix` (Python 3.9+)

Tweaks for newer Python

---

templates/flows/flow_create.haml

Currently if you enter keywords then switch to Surveyor type, and submit you get https://sentry.io/organizations/nyaruka/issues/2808019846/?environment=production&project=20737&referrer=alert_email

Clear keyword triggers when switching to flow type that doesn't support them

---

templates/orgs/email/user_forget.html
templates/orgs/email/user_forget.txt

Make forgot password email look a little nicer and be easier to localize

---

temba/orgs/tests.py
temba/tests/requests.py
temba/utils/__init__.py
temba/utils/tests.py

`dict_to_struct` used to be used for msg handling but now it was just being used in some tests so have replaced it with a simpler test utility

🧹 Dict to struct cleanup

---

templates/flows/flow_editor.haml

For the record, the legacy_extra link was to a placeholder that was never published was an empty article, making it the help root for now.

Update help links for the editor

---

temba/utils/analytics.py
temba/utils/tests.py

* Fix identify on signup
* Use same event structure for Crisp as others
* Remove keys with None value on calls to track()

Analytics tweaks

---

temba/campaigns/tests.py
temba/flows/models.py
temba/flows/tests.py
temba/flows/views.py
temba/ivr/models.py
temba/orgs/tests.py
temba/tests/base.py

The engine should enforce this and ignore bad values but we can also do a better job on the RP side

Improve validation of flow expires values

---

temba/channels/tests.py
temba/channels/views.py
temba/contacts/models.py
temba/tests/mailroom.py

rather than wait for mailroom to fail trying to create them which currently leads to sentry errors in both mailroom and rapid e.g.
https://sentry.io/organizations/nyaruka/issues/2323400685/?project=1281372&query=is%3Aunresolved
https://sentry.io/organizations/nyaruka/issues/2750945343/?project=20737&query=is%3Aunresolved

Relayer syncing should ignore bad URNs

---

temba/contacts/views.py
templates/contacts/contact_read.haml

I've limited it to beta users for now. This is going to be mostly for me to debug and test problems with that field being set.

Display current flow on contact read page

---

temba/flows/tests.py
temba/flows/views.py

changing file path to use original filename at the end instead UUID. 
As discussed here: https://github.com/nyaruka/courier/issues/383

use original filename to upload file

---

temba/api/v2/serializers.py
temba/api/v2/tests.py
temba/contacts/tests.py
temba/contacts/views.py

You can't create groups called "Active", "Blocked" etc. That might be a little confusing for users right now especially those who are seeing those system group names translated, but I think in future we want to move toward those being more like groups in other ways. For now we just want to give users a validation error instead of [blowing up with a db constraint error](https://sentry.io/organizations/nyaruka/issues/3052343027/?environment=production&project=20737&referrer=alert_email).

Fix group name validation to include system groups

---

temba/api/v2/serializers.py
temba/api/v2/tests.py
temba/api/v2/views.py
temba/campaigns/tests.py
temba/contacts/models.py
temba/contacts/tests.py
temba/contacts/views.py
temba/orgs/tests.py
temba/triggers/tests.py
temba/triggers/views.py
templates/contacts/contact_list.haml

Note that this PR is not adding any such groups, except an _Open Tickets_ group in testing - just getting the UI and API ready for them.
They appear at the top of the list with a padlock icon..
and no menu items to delete them...

Smart system groups part 5

---

templates/flows/flow_broadcast.haml

Because we're no longer planning to remove it

Remove warning about feature on flow start modal being removed

---

templates/contacts/contact_read.haml
templates/contacts/contact_update.haml
templates/contacts/contact_update_fields.haml
templates/contacts/contact_update_fields_input.haml
templates/flows/flow_broadcast.haml
templates/spa_frame.haml

Add the id for the shared modal used on the spa pages on query selectors. Shrink temba-component text input size to match descaled ui.

Fix modals on spa pages

---

temba/api/v2/tests.py
temba/assets/tests.py
temba/campaigns/tests.py
temba/channels/types/facebook/tests.py
temba/channels/types/facebookapp/tests.py
temba/contacts/tests.py
temba/flows/legacy/tests.py
temba/flows/tests.py
temba/orgs/tests.py
temba/request_logs/tests.py
temba/tests/base.py
temba/tickets/tests.py
temba/triggers/tests.py
temba/utils/templatetags/tests.py
temba/utils/tests.py

Need to avoid name collisions in tests as well

Require passing a name to `TembaTest.create_flow`

---

temba/flows/models.py
temba/tickets/models.py
temba/tickets/tests.py

I still want to overhaul imports and introduce more consistency across models but for now need this to fix imports of flows with ticketing.

Add `Topic.get_or_create` to handle topics in flow imports

---

temba/flows/models.py
temba/flows/tests.py
temba/utils/models/base.py

Fixes https://sentry.io/organizations/nyaruka/issues/3273003316/?referrer=alert_email&alert_type=email&alert_timestamp=1652521597059&alert_rule_id=34991&environment=production

Fix generating cloned flow names so they can't end with trailing spaces

---

temba/api/v2/tests.py
temba/campaigns/tests.py
temba/channels/tests.py
temba/contacts/tests.py
temba/dashboard/tests.py
temba/flows/legacy/tests.py
temba/flows/tests.py
temba/mailroom/tests.py
temba/notifications/tests.py
temba/orgs/tests.py
temba/tests/base.py
temba/tickets/tests.py

Was working on `orgs.User` stuff and noticed that we are very inefficient about checking permissions in views and it's being hidden in tests because `TembaTest.user` is being added directly to `auth.Group[name=Viewers]` - which is not how we grant permissions in the real world.
Figured I'd fix that in the tests before adding a fix to make the permission checking more efficient - and while I'm messing with test users, make them more realistic.

Make test users more realistic

---

templates/contacts/contact_read.haml

Fix rendering of dates on upcoming events list

---

static/js/temba.js
templates/flows/flow_broadcast.haml

Adds helper function to fallback to the shared modax but only if the requested one doesn't exist. Issue here was it was launching with one id, but attaching events to a different one.

Fix scripts on contact page start modal

---

temba/flows/tests.py
temba/flows/views.py
temba/msgs/models.py
temba/msgs/tests.py

```
http://s3.com/attachments/<orgid>/<flowid>/steps/6a65f14f-b762-4485-b860-96a322292775/steve%20marten.jpg
```
becomes
```
http://s3.com/test_orgs/<orgid>/media/6a65/6a65f14f-b762-4485-b860-96a322292775/steve%20marten.jpg
```
which almost matches what the media API endpoint uses except it preserves the file name which courier still needs

Update Media to use similiar storage path as media API endpoint

---

temba/flows/tests.py
temba/msgs/tests.py
temba/tests/base.py

So I can use it in https://github.com/nyaruka/rapidpro/pull/3917

Add decorator to mock UUID generation in tests

---

temba/campaigns/tests.py
temba/channels/tests.py
temba/channels/types/dialog360/tests.py
temba/channels/types/whatsapp/tests.py
temba/contacts/tests.py
temba/utils/views.py
templates/gear_links_include.haml
templates/spa.haml
templates/spa_page_menu.haml

Reworks `ContentMenuMixin` to put the menu in the context, and include new and legacy formats

Remove `view.get_gear_links`, put content menus in context

---

templates/orgs/user_account.haml

added 'authentication' to the temba anchor URL text

account page two factor authentication link fixed

---

temba/api/v2/fields.py
temba/api/v2/serializers.py
temba/api/v2/tests.py
temba/api/v2/views.py
temba/contacts/models.py
temba/contacts/search/omnibox.py
temba/contacts/tests.py
temba/contacts/views.py
temba/tests/base.py

Will add this in other places but this PR is complicated enough for now
```json
{
"uuid": "9a00cb2f-b63b-4796-bc17-e1939fd29303",
"name": "Frank",
"urn": "twitterid:2352463463#franky",
"urn_display": "franky"
}
```
if org is anon...
```json
{
"uuid": "9a00cb2f-b63b-4796-bc17-e1939fd29303",
"name": "Frank",
"urn": "twitterid:********",
"urn_display": "0000023525",
}
```
if contact doesn't have a URN...
```json
{
"uuid": "9a00cb2f-b63b-4796-bc17-e1939fd29303",
"name": "Frank",
"urn": null,
"urn_display": null,
}
```
but I have a sense that @ericnewcomer is going to want the anon id even when there's no URN so starting to question stuffing it in there

Add `.contact.urn_display` to runs endpoint

---

templates/channels/channellog_list.haml
templates/channels/channellog_list_spa.haml

Use elapsed_ms rather than request_time on channel log templates

---

templates/flows/flow_list_spa.haml

Rules:
* Names have a max width, ellipsized if exceeding
* Labels have a flex-wrap if needed
* Labels and names are in the same cell so they don't impact other flows
This isn't necessarily better in all cases, but better in most of them. Here is one case where I'd say it's not necessarily better, but is fine for me.
Was:
Now:

Nicer collapsing on flow list columns

---

LICENSE
temba/triggers/views.py
templates/triggers/trigger_list.haml

i'm assuming it's ok to leave all of the BTS instances of `triggers.trigger_create` as is for now, but let me know if it would be preferred to update those (and/or the translations)  to `trigger_new` and `New Trigger` for consistency, respectively

fixed create trigger

---

temba/channels/models.py
temba/channels/tests.py
temba/flows/legacy/tests.py
temba/mailroom/tests.py

Fixes https://sentry.io/organizations/nyaruka/issues/3541064485/
```
KeyError: 'status_code'
File "django/core/handlers/exception.py", line 55, in inner
response = get_response(request)
File "django/core/handlers/base.py", line 197, in _get_response
response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "contextlib.py", line 79, in inner
return func(*args, **kwds)
File "django/views/generic/base.py", line 84, in view
return self.dispatch(request, *args, **kwargs)
File "temba/orgs/views.py", line 169, in dispatch
return super().dispatch(request, *args, **kwargs)
File "smartmin/views.py", line 117, in dispatch
return wrapper(request, *args, **kwargs)
File "smartmin/views.py", line 113, in wrapper
return super(SmartView, self).dispatch(request, *args, **kwargs)
File …
```

Fix to allow displaying logs that timed out

---

temba/orgs/models.py
temba/triggers/tests.py
temba/triggers/types.py
temba/triggers/views.py
templates/triggers/trigger_create_missed_call.haml

Users shouldn't be using this except for missed calls on Android devices

Only show Missed Call trigger as option for workspaces with an Android channel

---

temba/flows/models.py
temba/msgs/models.py
temba/tickets/models.py
temba/utils/export/models.py

Next step is adding a common export base for things that have an associated contact, so then we can have a uniform set of contact columns across the different export types (excluding actual contact exports)

Add common base class for exports that have a date range

---

templates/api/v2/api_explorer.haml
templates/api/v2/api_root.html

* Add some margins to li and adjust code blocks so they don't overlap
* Nicer margins around ul
* Consistent widths for docs and explorer at 80%

Small styling tweaks for api docs

---

temba/channels/models.py
temba/channels/tests.py
temba/channels/views.py
temba/flows/models.py
temba/flows/tests.py
temba/middleware.py
temba/notifications/models.py
temba/orgs/context_processors.py
temba/orgs/models.py
temba/orgs/tests.py
temba/orgs/views.py
temba/settings.py.dev
temba/settings_common.py
temba/settings_compress.py
temba/tickets/types/mailgun/views.py
temba/tickets/types/zendesk/views.py
temba/utils/brands.py
temba/utils/tests.py

Problems with current approach:
* We have to modify settings.BRANDING in the middleware, adding the key/host as "brand" so we can get that from request.branding, e.g. when we need to save an org with the brand key/host.
* We also modify keys.. which mean the same as aliases
This PR makes it so that we use slug to associated orgs and brands, and then brands have a host list which is what we match against requests.

🖼️ Rework branding 

---

temba/api/support.py
temba/api/v2/tests.py
temba/middleware.py

DRF auth happens after middleware in the view level

Update API auth classes to set `request.org` and use that to set `X-Temba-Org` header

---

temba/api/models.py
temba/api/support.py
temba/api/v2/tests.py
temba/api/v2/views.py
temba/orgs/models.py
temba/orgs/tests.py
temba/orgs/views.py
templates/api/v2/api_explorer.haml
templates/api/v2/api_root.html
templates/orgs/org_token.haml

Replaces `User.api_token` with explicit `User.get_api_token(org)`

Always explicitly provide org when requesting a user API token

---

temba/contacts/models.py
temba/contacts/tests.py
temba/contacts/views.py

Don't show location field types as options on deploys where locations aren't enabled

---

temba/flows/tasks.py
temba/flows/tests.py
temba/settings_common.py

One of these is really really slow and I think it's the start one because it updates all the runs

🪓 Split task to trim starts and sessions into two separate tasks

---

temba/channels/views.py
temba/utils/analytics/base.py
temba/utils/analytics/tests.py
temba/utils/crons.py

Which allows backends to more easily send guage values in bulk

🚚 Replace `gauge` on analytics backend with `gauges`

---

templates/spa_frame.haml

* frame_top was being included twice on spa pages
* add missing mapping root
* add id for temba-menu so it can be specifically styled

Fix frame-top includes

---

temba/msgs/models.py
temba/msgs/tests.py

Actually need to push this asap because the migration to replace `base` with `und` didn't update the `text` field hence we're seeing a few sentry errors trying to render scheduled messages.

📣 Stop reading from `Broadcast.text`

---

static/js/urls.js
temba/dashboard/views.py
temba/orgs/views.py
templates/dashboard/home.haml
templates/dashboard/home_spa.haml
templates/spa_frame.haml

* Exposes dashboard to all users with perm (don't have to be multi org)
* Only shows cumulative message count chart (removed channel / org breakdown below as this was broken before and a bit goofy overall and we should do something better here anyways)

Add simplified dashboard to menu

---

temba/api/v2/fields.py
temba/api/v2/tests.py
temba/api/v2/views.py
temba/api/v2/views_base.py

* Exclude unhandled messages when fetching `folder=incoming` - otherwise we end up returning messages with attachments that mailroom hasn't yet had time to resolve https://textit.sentry.io/issues/3948812308/
* Don't use lookup values with the wrong type - i.e. don't try to match name with an integer value https://textit.sentry.io/issues/3949513511
* If fetching `folder=sent`, sort by -sent_on same as UI and same as the index we made for that.

🧰 API fixes 

---

package.json
temba/campaigns/tests.py
temba/campaigns/views.py
temba/channels/models.py
temba/orgs/views.py
templates/flows/flow_list_spa.haml
templates/spa_frame.haml
templates/tickets/ticket_list_spa.haml
yarn.lock

* Call `menu.refresh` once per page load
* Debounce calls to `menu.refresh` with quiet period of 200ms, now can make calls more freely without fear of over running
* Switch home icon to home and workspace to settings cog

More aggressive menu refreshing

---

temba/channels/types/external/tests.py
temba/channels/types/jasmin/tests.py
temba/channels/types/junebug/tests.py
temba/channels/types/kannel/tests.py
temba/channels/types/shaqodoon/tests.py
temba/channels/types/telesom/tests.py
temba/channels/types/twiml_api/tests.py
temba/channels/types/viber_public/tests.py
temba/channels/types/whatsapp/tests.py
temba/utils/tests.py

Run these locally without internet access
I'll keep find if a way to make github actions run them tests in a similar fashion just after installing all the dependencies we need from the internet

Make sure tests can run without making requests to external URLs

---

static/js/labels.js
temba/orgs/views.py
temba/tickets/views.py
templates/includes/short_pagination.haml
templates/msgs/message_box_spa.haml
templates/orgs/user_read.haml
templates/smartmin/list.haml
templates/spa.haml
templates/spa_frame.haml
templates/spa_page_header.haml
templates/tickets/ticket_list.haml
templates/tickets/ticket_list_spa.haml
templates/triggers/trigger_list_spa.haml

* Remove global client side title updates (defers to view as before)
* Add client side `page-title` updates for ticket list as this is the only place its currently required
* Make old `labels.js` tolerant to spa page titles
* Put `labels.js` for spa inside a compress for cache busting
* Remove erroneous titles from spa modals
* Add empty `temba-store` when there is no org set
* Make sure `onSpload` event registrations on DOM are only ever fired once
* A few more `goto()` links to avoid page reloads and menu_path
Fixes: #4357
Fixes: #4358

Slew of title and label fixes

---

temba/api/v2/serializers.py
temba/channels/models.py
temba/channels/tests.py
temba/channels/views.py
templates/channels/channel_read.haml
templates/channels/channel_read_spa.haml
templates/channels/email/sms_alert.html

Started trying to cleanup Android channel alerts which need to become incidents/notifications (currently channel checking cron is not performant at all).. but first need to cleanup what we display on the read page.

Simplify what we display for Android channels

---

temba/utils/models/fields.py
temba/utils/models/tests.py

Want to get JSON fields like`Org.config` which currently use our `JSONAsTextField` class onto the real `models.JSONField` so that they're real JSONB in the database, with validation, and we can use JSON operators in Django querysets.
Except probably fields like `FlowSession.output` and `FlowRevision.definition` where there would probably be a performance penalty because of their size.
Step one is making the existing fields behave more like real JSON fields so no more automatically converting values like `{}` to NULL.

Stop saving `JSONAsTextField` values as null for empty dicts and lists

---

temba/channels/models.py
temba/channels/types/twilio/tests.py
temba/channels/types/twilio/type.py
temba/channels/types/twilio/views.py
temba/channels/types/twilio_messaging_service/tests.py
temba/channels/types/twilio_messaging_service/type.py
temba/channels/types/twilio_whatsapp/tests.py
temba/channels/types/twilio_whatsapp/type.py
temba/channels/views.py

Addresses https://github.com/nyaruka/rapidpro/issues/4227
Old UI
New UI

Add `ChannelType.check_credentials` and use for Twilio claims and updates

---

temba/api/v2/serializers.py
temba/api/v2/tests.py
temba/api/v2/views.py

Flow is already part of the "api" format that we use for archiving

Expose flow on messages API endpoint

---

temba/utils/management/commands/mailroom_db.py

Because we now have a migration calling it.. which then throws off the uuid constants used by mailroom tests

Fix mailroom db command to patch uuid generation after migrations are run

---

temba/contacts/tests.py
temba/utils/views.py

https://textit.sentry.io/issues/4004534394/?alert_rule_id=5195&alert_timestamp=1678802103157&alert_type=email&environment=production&project=20737&referrer=alert_email
Can't use headers to pass back anything that can be non-ASCII... seems we need to rethink passing back of page titles this way

🚒 Strip out invalid HTTP header characters from page title response headers

---

temba/contacts/models.py
temba/orgs/models.py
temba/orgs/tests.py
temba/orgs/views.py

Flagging is currently done via the context menu.. or the update form.
This PR adds suspension/unsuspension to the context menu and removes both that and flagging from the update form.

👮 Fix suspending and unsuspending orgs

---

temba/msgs/models.py

Avoids sentry errors like https://textit.sentry.io/issues/4028647796/?alert_rule_id=5195&alert_timestamp=1679530070033&alert_type=email&environment=production&project=20737&ref_fallback=ga&referrer=alert_email

NOOP instead of assert if archiving msg which is already archived etc

---

temba/api/v2/fields.py
temba/api/v2/serializers.py
temba/api/v2/tests.py
temba/api/v2/views.py
temba/contacts/models.py
temba/contacts/tests.py
temba/mailroom/client.py
temba/mailroom/tests.py
temba/tests/mailroom.py

Without param...
```
"urns": ["tel:+250700009999", "twitterid:357475478548745"]
```
With param...
```
"urns": [
{
"channel": {
"uuid": "c9a5d98a-4c89-4f25-af96-81f06b67e019",
"name": "Vonage"
},
"scheme": "tel",
"path": "+250700009999",
"display": null
},
{
"channel": null,
"scheme": "twitterid",
"path": "357475478548745",
"display": "cathy"
}
]
```
Without param in anon org...
```
"urns": ["tel:********", "twitterid:********"]
```
With param in anon org...
```
"urns": [
{
"channel": {
"uuid": "c9a5d98a-4c89-4f25-af96-81f06b67e019",
"name": "Vonage"
},
"scheme": "tel",
"path": "********",
"display": null
},
{
"channel": null,
"scheme": "twitterid",
"path": "********",
"display": "cathy"
}
]
```
No channel indicates a URN which is not sendable.

Add undocumented param to contacts API endpoint which allows URNs to be expanded

---

temba/locations/migrations/0028_alter_adminboundary_level_alter_adminboundary_name_and_more.py

Sometimes you add a migration, and suddenly migrations are running in a different order exposing a dependency issue we hadn't seen before. Can't wait to get indexes out of sql files and into Django models so it's Django's problem to keep things like this in the right order.

Tweak migration dependency

---

temba/contacts/models.py

https://github.com/nyaruka/mailroom/pull/63 changes response to be..
```
{
"modified": {
"10001": {...},
"10002": {...}
},
"skipped": []
}
```
instead of 
```
{
"10001": {...},
"10002": {...}
}
```

Make `contact.modify` work with new and old format

---

temba/channels/tests.py
temba/orgs/views.py
temba/tests/base.py
temba/tests/crudl.py
temba/tickets/tests.py
temba/utils/views.py
templates/frame.haml
templates/no_nav.haml
templates/orgs/login/login.haml
templates/spa_frame.haml

Only `nav=old` will use old UI. So `nav=1` or `nav=2` gets new UI, and we just use `nav=old` as default temporarily in unit tests until those can be rewritten.

Change cookie checking for UI so that we always default to new UI

---

temba/channels/types/dialog360/type.py
temba/channels/types/facebookapp/type.py
temba/channels/types/facebookapp/views.py
temba/channels/types/instagram/type.py
temba/channels/types/instagram/views.py
temba/channels/types/plivo/type.py
temba/channels/types/plivo/views.py
temba/channels/types/twilio/type.py
temba/channels/types/twilio/views.py
temba/channels/types/vonage/type.py
temba/channels/types/vonage/views.py
temba/channels/types/whatsapp/type.py
temba/channels/types/whatsapp_cloud/type.py
temba/channels/types/whatsapp_cloud/views.py
temba/channels/views.py
temba/utils/whatsapp/views.py

Currently channel type classes import their view classes... so view classes can't import type classes easily.. so things like config constants end up in the views module, when ideally they'd live in the channel type. The claim view already solves this by having a `.channel_type` attribute but additional views don't have this. This PR adds a mixin which makes that attribute available to other channel type specific views.

Add mixin for channel type specific views that gives access to the type class

---

temba/channels/models.py
temba/channels/tests.py
temba/channels/types/viber_public/tests.py
temba/channels/views.py
temba/tests/base.py
templates/channels/channel_read.haml
templates/channels/channellog_list.haml

We want users to get to logs from msgs and calls... not listing logs themselves which won't be possible when they're just files in S3. But we still need a story for logs that don't have a message or a call.. so for now we still keep a simplified list view of logs.

📇 Channel logs in S3 part 2: stop filtering by `.msg` and `.call`

---

temba/channels/models.py
temba/channels/tests.py
temba/channels/types/facebookapp/type.py
temba/channels/types/instagram/type.py
temba/channels/views.py
temba/settings_common.py

Also changes anonymization of logs: staff users will see anonymized by default and have to eplicitly break out of that with a url parameter (that we'll probably turn into something in the UI).
Making it easier to switch to loading channel logs from JSON blobs in S3.

📺 Rework channel log rendering to always start from JSON

---

poetry.lock
pyproject.toml
temba/flows/tests.py
temba/msgs/templatetags/tests.py
temba/tests/base.py
temba/utils/haml.py
templates/smartmin/list.haml
tools/convert_template.py

https://github.com/nyaruka/rapidpro/pull/4566 isn't looking so mergeable so maybe we need a more incremental approach.
This switches the on-demand haml to html conversion to use the same latest settings that we want to use for a bulk converion from haml to html.

🗽 Add djlint and latest django-hamlpy

---

package.json
static/js/frame.js
temba/flows/views.py
temba/utils/fields.py
temba/utils/views.py
templates/flows/flow_editor.haml
templates/flows/flow_list.haml
templates/includes/short_pagination.haml
yarn.lock

* Remove double loading of flow editor scripts
* Add icons for background, flow, and surveyor flows
* Fix spload sometimes not firing on first navigation after page load
* Add icons to flow type selection
* Fix disabled modals being able to close

Flow fixes and type icons

---

temba/locations/management/commands/import_geojson.py

I made changes to posm to make sure the geojson has parent_id for all levels but this will help in case the geojson does not have that.

Fix parent ID lookup in import geojson

---

temba/channels/types/twilio/views.py

Account SID form widget was marked as disabled instead of the field itself. This led to weird form behavior when other fields caused a form validation error.
Fixes #4692

Fix for updating Twilio Credentials

---

temba/channels/templatetags/channels.py
temba/channels/templatetags/tests.py
temba/channels/tests.py
temba/mailroom/events.py
temba/mailroom/tests.py
temba/settings_common.py
templates/channels/channellog_list.haml

We'll display logs up to 14 days, S3 will expire them at 15 days.

Update channel log retention to 2 weeks

---

temba/channels/models.py
temba/channels/tasks.py
temba/channels/tests.py
temba/flows/models.py
temba/orgs/models.py
temba/orgs/tests.py

Contacts and tickets both can reference flows which creates a bit of circular dependency mess - this gets around it by deleting some flow stuff before contacts and tickets, then finally deleting the actual flow last.

🗑️ Fix problems with org deletion

---

templates/channels/types/instagram/claim.haml

Old link no longer works, and tweak the message to be more clear.

Update Instagram docs broken link

---

temba/orgs/views.py
temba/utils/views.py
templates/channels/channel_read.haml
templates/channels/channellog_list.haml
templates/channels/channellog_msg.haml
templates/channels/channellog_read.haml
templates/contacts/contact_list.html
templates/contacts/contact_read.html
templates/contacts/contactimport_create.html
templates/contacts/contactimport_preview.html
templates/contacts/contactimport_read.html
templates/flows/flow_editor.html
templates/frame.haml
templates/orgs/org_create.haml
templates/orgs/org_edit.haml
templates/orgs/org_manage_accounts.haml
templates/orgs/org_sub_orgs.haml
templates/orgs/user_update.haml
templates/request_logs/httplog_read.haml
templates/smartmin/base.html
templates/spa.haml
templates/tickets/ticket_list.haml

More consistent blocks for titles.
Now we just use block title. This is the title that is at the top of the content pane, not the page title in the tab. So, markup is allowed. For example to show an object with an icon, we might do something like this: 
```django
{% block title %}
<div class="flex">
<temba-icon name="{{flow_icon}}"></temba-icon>
<div id="title-text">{{flow.name}}</div>
</div>
{% endblock title %}
```
The key is to wrap the plain text portion you want to appear in the tab inside a div with the id "title-text". This isn't new, but now is a bit more  consistent throughout the app. This is used whether the page is initially loaded or navigated to in the spa.

Remove spa-title and spa-style

---

temba/contacts/tests.py
temba/flows/tests.py
temba/flows/views.py
templates/flows/flow_broadcast.html

Flow is hidden when starting from the flow page. When selecting a flow after contact selection, the exclusions are now empty until a flow is selected. Then the appropriate checkboxes appear.

Allow flow selection on flow broadcast form

---

static/js/frame.js
templates/channels/channel_claim_number.html

Fixes bug where:
1. Initial load a page that doesn't trigger `onSpload`
2. Navigate immediately to a page that does
3. onSpload wouldn't be called
Also, first PR from an airplane.

Fix onSpload fire

---

temba/contacts/templatetags/contacts.py
temba/contacts/templatetags/tests.py
temba/orgs/tests.py
templates/contacts/contact_list.html

For a non anon org, contacts look like...
But a for anon orgs, you only see either name / anon id, and then we waste a column on a redacted URN:
This PR makes it that column one is always name, column two is always anon id in place of a URN:

Always show name / anon id for anon orgs in contact lists

---

temba/tests/base.py

This worked when test redis was always accessible via localhost... our settings already enforce that redis during tests is on port 10, otherwise 15.. so I don't think we need to be so paranoid.

Fix flushing redis in tests

---

temba/api/v2/tests.py
temba/api/v2/views.py

I think the reason it doesn't is because the first version of CasePro fetched its message views on the fly from RP and it needed it to be this way. I don't see anyone calling the API endpoint with the label param currently.

Fetching messages by label should include archived messages

---

temba/msgs/tests.py
temba/msgs/views.py
templates/contacts/contact_list.html
templates/includes/short_pagination.html
templates/msgs/broadcast_create_schedule.html
templates/msgs/message_box.html
templates/public/public_welcome.html

* Selection at the end of broadcast creation pipeline to send now or schedule for later
* Switch Send Message to New Broadcast and point it to the broadcast pipleline. This includes on contact lists and the message inbox

Add 'Send Now' to broadcast creation

---

temba/settings_common.py
temba/triggers/models.py
temba/triggers/tests.py
temba/triggers/types.py
temba/triggers/views.py
temba/utils/templatetags/temba.py

We used to do this.. not sure why we got rid of it. But it seems nicer to have a a folder of triggers called "OptIns" that includes Opt-In and Opt-Out.. or if we added another type of ticket trigger it would live with "Tickets"

Group trigger types into folders

---

temba/channels/tests.py
temba/channels/views.py
temba/notifications/incidents/builtin.py
temba/notifications/models.py
temba/notifications/tests.py
temba/notifications/types/builtin.py
templates/notifications/email/incident_started.channel_disconnected.html
templates/notifications/email/incident_started.channel_disconnected.txt

Currently the target_url for notifications for incidents is just the incident list page... but it makes more sense that if you click on a channel disconnected incident notification.. it takes you to the channel read page, and viewing that page is what clears the notification.

Allow the target_urls of incident notifications to differ by type

---

temba/campaigns/models.py
temba/campaigns/tasks.py

This fixes the issue of timing out when a user try to archive a campaign with many events.

Add celery task to recreate campaign events when archiving

---

temba/api/models.py
temba/contacts/tests.py
temba/orgs/models.py
temba/settings_common.py

Contains https://github.com/nyaruka/rapidpro/pull/4868

Allow perms to be made API specific so that we can limit agent UI access

---

temba/flows/tests.py
temba/flows/views.py

Previously editing of keyword triggers from flow update only looked at "Global" keyword triggers (no group filtering) - but now it will consider any trigger with that keyword.

Fix updating keyword triggers for flows

---

templates/triggers/trigger_list.html

Fix to display channel on trigger list if set on any trigger type

Make sure we display trigger channel if set

---

temba/orgs/models.py
temba/orgs/tests.py
temba/orgs/views.py
temba/settings_common.py
templates/orgs/org_join.html
templates/orgs/org_join_accept.html
templates/orgs/org_join_signup.html

Includes some UI tweaks:
becomes:
and 
becomes
and 
becomes

Fix and cleanup views for accepting invitations

---

temba/utils/whatsapp/tasks.py
temba/utils/whatsapp/tests.py

Whatsapp templates sync
For 360diallog, we do not get the template ID and we make an ID we store in external ID by combining the language and name.
The name can go up to 512 characters but the external ID has up to 64 characters.
This make sure we truncate the ID we make up from the name limited to 64 characters.
Fixes https://textit.sentry.io/issues/4547227349/

Make sure the missing external ID we make is truncated to 64 characters

---

temba/api/models.py
temba/api/support.py
temba/api/urls.py
temba/api/v2/tests.py
temba/api/v2/urls.py
temba/api/v2/views.py
temba/orgs/models.py
temba/orgs/tests.py
temba/settings_common.py
templates/api/docs.html
templates/api/v2/docs.html
templates/api/v2/explorer.html
templates/orgs/user_token.html

Stop showing API tokens on docs pages, and rework templates to sbetter support different APIs
before 
after

Simplify how we render API docs pages

---

templates/api/v2/explorer.html

note you still see your API token when you expand an endpoint card

Tweak appearance of API explorer

---

temba/api/v2/serializers.py
temba/api/v2/tests.py
temba/api/v2/views.py

It needs to change to support more complex templates.. and it doesn't feel like a thing we need to expose to end users

Undocument the templates API endpoint and add locale field to translations

---

temba/channels/types/mailgun/__init__.py
temba/channels/types/mailgun/tests.py
temba/channels/types/mailgun/type.py
temba/channels/types/mailgun/views.py
temba/settings_common.py

The final user facing version should probably get a general API key, list domains, add webhook automatically.

Add skeleton staff only mailgun channel type

---

temba/orgs/tests.py
temba/orgs/views.py
templates/orgs/org_smtp_server.html

Form was kinda annoying in that it would show one error at a time and errors weren't located with their fields.

Cleanup flow SMTP formax and show parent settings as default to match mailroom changes

---

temba/campaigns/tests.py
temba/channels/tests.py
temba/channels/types/viber_public/tests.py
temba/classifiers/tests.py
temba/contacts/tests.py
temba/flows/tests.py
temba/globals/tests.py
temba/msgs/tests.py
temba/orgs/tests.py
temba/tests/crudl.py
temba/tickets/tests.py
temba/triggers/tests.py

`assertCreateSubmit`, `assertUpdateSubmit`, `assertDeleteSubmit` all now require specifying the user... sometimes you want to use these with a user besides `admin`

Tweak CRUDL submission test methods to take user as an argument 

---

temba/campaigns/tests.py
temba/channels/tests.py
temba/channels/types/viber_public/tests.py
temba/classifiers/tests.py
temba/contacts/tests.py
temba/flows/tests.py
temba/globals/tests.py
temba/msgs/tests.py
temba/orgs/tests.py
temba/tests/crudl.py
temba/tickets/tests.py
temba/triggers/tests.py

They're kinda janky right now because sometimes a form shows different things depending on the user

Rework CRUDL tests to take explicit lists of users

---

temba/channels/android/sync.py
temba/channels/android/views.py
temba/channels/tests.py
temba/contacts/models.py
temba/mailroom/client.py
temba/mailroom/queue.py
temba/mailroom/tests.py
temba/msgs/models.py
temba/tests/mailroom.py

Removes the need for RP to know about queueing contact tasks.. or creating messages/events.
And it doesn't add any new HTTP overhead because we were already calling mailroom `contact/resolve` to create such messages/events.

Use mailroom endpoints to create messages and events during Android syncing

---

temba/contacts/tests.py
temba/flows/tests.py
temba/msgs/tests.py
temba/orgs/views.py
temba/tickets/tests.py

Fixes https://textit.sentry.io/issues/5130725031/?project=21956. 
User opens export modal and there's no blocking export, other user opens export modal starts blocking export, first user submits modal. Currently leads to assert error, this PR makes form submission redirect to show blocker.

Fix export blocking due to multiple users exporting at same time

---

temba/channels/models.py
temba/contacts/models.py
temba/flows/models.py

blowing up because a trigger which is already released, is being released again and trying to deactivate a channel of type TT that no longer exists https://textit.sentry.io/issues/5175827020/

Don't re-release released triggers

---

templates/orgs/user_edit.html

Even on mobile there's space to have these side by side
and if you're not on mobile it currently looks like...

Tweak layout of user edit form

---

temba/flows/tasks.py
temba/flows/tests.py

...so things are always interrupted before archiver gets to them. I think this is why we some times see errors like https://textit.sentry.io/issues/5226712172

Tweak time limit for sessions to 89 days

---

templates/dashboard/home.html
templates/frame.html
templates/no_nav.html
templates/public/public_welcome.html

We'll display the messages once in `alert-messages` block
https://github.com/nyaruka/rapidpro/blob/631e6b4cf628dd8b7e1aaff1af0a0664b4c576f6/templates/frame.html#L258-L269

Remove messages block that duplicates alert-messages

---

templates/contacts/contact_list.html
templates/contacts/contactimport_preview.html
templates/orgs/login/confirm_access.html
templates/orgs/login/login.html
templates/orgs/login/two_factor_backup.html
templates/orgs/login/two_factor_verify.html

as alert component:
as alert styled div:
as alert component:
as alert styled div:
as alert component:
as alert styled div:

Don't use error level alerts for form errors

---

temba/contacts/models.py

Use icons in campaign event dropdown to indicate field type

---

temba/channels/types/plivo/tests.py
temba/channels/types/rocketchat/tests.py
temba/channels/types/whatsapp/tests.py
temba/flows/tests.py
temba/mailroom/client.py
temba/mailroom/tests.py
temba/tests/requests.py

And for convenience added `MockJsonResponse` for tests.

Mailroom client should use content-type header on responses to know whether to parse as JSON

---

temba/settings_common.py

And remove some unused settings.
Fixes https://textit.sentry.io/issues/5424094171 for big workspaces (that one has ~1190 things to export)

Increase DATA_UPLOAD_MAX_NUMBER_FIELDS from 1000 to 2500

---

temba/channels/tests.py
temba/notifications/tests.py
temba/orgs/tests.py
temba/settings_common.py

And then use `mail.outbox` to test rather than patching our email send functions

Send emails in tests

---

temba/airtime/migrations/0028_airtimetransfer_uuid.py

It currently sets the same UUID on all transfers. Need to set default in separate operation.

Fix migration to add uuid field to airtime transfers

---

temba/api/v2/tests.py
temba/contacts/tests.py
temba/flows/tests.py
temba/mailroom/__init__.py
temba/mailroom/client/__init__.py
temba/mailroom/client/client.py
temba/mailroom/client/exceptions.py
temba/mailroom/client/tests.py
temba/mailroom/client/types.py
temba/msgs/tests.py
temba/orgs/tests.py
temba/tests/mailroom.py
temba/tickets/tests.py

There is a point to all this... have the client class be able to import app models and app models be able to access the client without creating an import loop.

More reorg of mailroom types

---

temba/channels/android/views.py
temba/contacts/models.py
temba/contacts/views.py
temba/mailroom/client/client.py
temba/mailroom/client/tests.py
temba/tests/mailroom.py

Now that the import loop is broken. Pushes more logic down into the client which is better for re-use.

Use models instead of primitives in mailroom client

---

temba/channels/models.py
temba/channels/tests.py
temba/orgs/tests.py
temba/templates/models.py
temba/templates/tests.py

We don't often hard delete anything but:
1. These aren't things people are authoring in RP - they can always be re-synced from the channel if they still exist
2. Marking things as inactive and then active again is kinda weird
3. The thing you probably should be able to soft delete is the template.

Hard delete template translations that no longer exist on the channel side

---

temba/api/internal/tests.py
temba/flows/tests.py
temba/templates/models.py
temba/templates/tests.py
temba/templates/views.py
temba/tests/base.py
templates/templates/includes/translation.html
templates/templates/template_list.html
templates/templates/template_read.html

* Exclude empty templates from list
* Show base translation apart on read page
* Use "languages" wording instead of "translations"

Templates UI updates

---

temba/channels/types/whatsapp_legacy/type.py

https://textit.sentry.io/issues/5607593587/
Channel.release handles template translations, individual channel types don't need to worry about it

Fix deactivating a legacy WhatsApp channel

---

temba/tickets/tests.py
temba/tickets/views.py

All outgoing messages for tickets used to be broadcasts and then we'd read `.created_by` from the `Broadcast` because there was no created_by field on `Msg`... but that changed a while ago.

Remove old code for getting message created_by from broadcasts

---

temba/flows/tests.py
temba/flows/views.py
temba/msgs/tests.py
temba/msgs/views.py
templates/flows/flow_list.html
templates/includes/short_pagination.html

I think the move to _Download_ wording for things that can't be re-imported was a mistake, since we use _Export_ wording elsewhere in the emails, notifications etc. It wouldn't be crazy to have an export list page that shows the recent exports of any type.
Also think we need to make it easier to find the button to send messages.
Before:
After:
* _New Label_ feels weird here but we still don't have a way to open models from the lefthand menu
Before:
After:
Before:
After:

Tweak menu items for msg views and flow results

---

temba/channels/types/firebase/tests.py
temba/channels/types/firebase/views.py

needs https://github.com/nyaruka/courier/pull/762

Support FCM changes

---

templates/orgs/integrations/dtone/account.html

Adjust button to be connect
Moved the transfer log button inside the open section
Fix disconnect to open confirmation modal

Fix DTOne formax section

---

temba/api/models.py
temba/api/tests.py
temba/api/v2/tests.py
temba/orgs/tests.py
temba/orgs/views.py

Now only Editor and Administrator role tokens exist (effectively the same), and it's possible for an Administrator to have an Editor token that they can't see in the UI. We're going to move to users only having a single token (the one they see in the UI) and this is step 1 - making the tokens use the role that the user _currently_ has in the workspace.

API tokens should use the current role of the user

---

package.json
templates/flows/flowstart_list.html
templates/frame.html
templates/request_logs/httplog_webhooks.html
yarn.lock

The monitor is presented on the top of each spa page. I noticed two list pages that didn't scroll properly which is now more likely to happen when the monitor is visible. So this PR also includes that.

Add outbox monitor for large queues

---

temba/channels/types/external/tests.py
temba/channels/types/external/views.py
templates/channels/types/external/claim.html

`{{channel}}` was not mention on the claim page and not properly validated as well in https://github.com/nyaruka/rapidpro/pull/5487
This PR fixes that

Validate channel variable in the body for EX channels

---

temba/api/views.py
temba/campaigns/views.py
temba/channels/types/facebookapp/views.py
temba/channels/types/instagram/views.py
temba/channels/types/whatsapp/views.py
temba/channels/views.py
temba/contacts/views.py
temba/flows/views.py
temba/globals/views.py
temba/msgs/views.py
temba/orgs/views/base.py
temba/orgs/views/views.py
temba/tickets/views.py
temba/triggers/views.py
temba/utils/views/mixins.py

* Rename `ModalMixin` to `ModalFormMixin` so it's clear it's not needed for non-form modals
* Fix places it is being wrongly combined with `ContextMenuMixin` or `SpaMixin`

More modal cleanup

---

temba/orgs/views/base.py

Currently most delete views use `ModalFormMixin` which introduces a `SmartFormView` base class which uses things like `success_message` and `success_url`... but these should be just using `redirect_url` of `SmartDeleteView`.

Fix BaseDeleteModal to not use ModalFormMixin

---

temba/api/v2/tests.py
temba/contacts/models.py
temba/contacts/tests.py
temba/orgs/tests.py

All in on status groups shouldn't be actual groups

Create status groups with randomized names to avoid conflicts with real group names

---

temba/channels/models.py
temba/channels/tests.py

Fixes https://textit.sentry.io/issues/5995273839/

Fix displaying the log missing HTTP response

---

temba/orgs/tests.py
temba/orgs/views/views.py

Not critical because the only thing these views can change is the user's role in the current org.. but important to fix this in case one day we extend what can be updated here.

Tweak user update and delete forms to return 404 for users not in the current org

---

temba/api/v2/views.py
temba/archives/models.py
temba/archives/tests.py
temba/archives/views.py
temba/utils/__init__.py
temba/utils/tests.py
templates/archives/archive_list.html
templates/archives/archive_message.html
templates/archives/archive_run.html

* Use top paging like other views
* Use same page size
* Put period on left of table
* Use std django filter to format size (correctly uses `MB` instead of `Mb`)
before:
after:

Fix paging on archive list pages and make styling consistent with other list views

---

temba/contacts/views.py
temba/flows/views.py
temba/globals/views.py
temba/orgs/views/base.py
temba/orgs/views/views.py
temba/templates/views.py
temba/tickets/tests.py
temba/tickets/views.py
temba/triggers/views.py

* Make `BaseListView` filter by `is_active=True`
* Make `BaseUpdateView` filter by `is_active=True` and `is_system=False`
* Make `BaseDeleteView` noop for `is_system=True`

Do more filtering in new base views

---

temba/tickets/models.py
temba/tickets/tests.py
temba/tickets/views.py

Trying to make it easier to add topic/team filtering everywhere we fetch tickets.

Some cleanup to tickets list view

---

temba/channels/types/dialog360_legacy/tests.py
temba/channels/types/dialog360_legacy/type.py
temba/channels/types/whatsapp_legacy/type.py
temba/utils/whatsapp/__init__.py
temba/utils/whatsapp/tests.py

Fixes https://textit.sentry.io/issues/6082875470/ too

Use debug logging for channel types errors, D3 and WA

---

package.json
static/css/temba-components.css
temba/api/v2/tests.py
temba/api/v2/views.py
temba/contacts/tests.py
temba/contacts/views.py
temba/tickets/tests.py
temba/tickets/views.py
templates/contacts/contact_interrupt.html
templates/contacts/contact_read.html
templates/frame.html
templates/orgs/user_edit.html
templates/tickets/ticket_list.html
yarn.lock

* Add interrupt modal
* Switch interrupt to use uuid
* Add email filtering for api users
* Fix safari font rendering
* TembaUser now fetches each user on demand and monitors Store for changes
* Active flow now visible on contact chat / tickets
* Add option to show interrupt button that can trigger an event
* Add built-in alpha sort option for select
* Fix race condition with store fetching/caching for requests to the same endpoint in quick succession
* Fix leaked ContactHistory component with ongoing updates/fetches
* clear activity timeout on unmount

Move active flow and interruption into chat, make temba-user fetch individually

---

temba/flows/models.py
temba/flows/tests.py
temba/orgs/models.py
temba/tickets/tests.py
temba/utils/models/squashable.py

We're about to move node counts to the new count model and they have a special property - they all end up zero, and zero is already representable in the count model as non-existence. So let's not even store zeros.

Change new count model squashing to discard zero counts

---

temba/flows/models.py
temba/flows/tests.py

This is almost always the message text and in the case of open ended questions it just repeats the result value.
I'd like to remove this and see what pushback we get if any.

Remove input/text columns from results exports

---

temba/channels/android/views.py
temba/utils/analytics/base.py
temba/utils/analytics/tests.py

Everything interesting is being reported by other components like courier these days

Remove gauges from analytics abstraction

---

temba/contacts/tests/test_fieldcrudl.py
temba/contacts/tests/test_groupcrudl.py
temba/flows/tests/test_export.py
temba/flows/tests/test_flowcrudl.py
temba/tests/mailroom.py

Part 1 of getting rid of needing real mailroom to run unit tests

Don't require real mailroom flow inspection when using @mock_mailroom

---

temba/tests/mailroom.py

Another tiny step toward not using real mailroom in tests

Don't really clone flow definitions in tests

---

temba/sql/migrations/0007_squashed.py

Hopefully migrations run in the same order for everyone in 10.0.x otherwise this might be something that needs backported

Ensure that SQL app migrations run after other apps

---

temba/flows/tasks.py
temba/flows/tests/test_flow.py
temba/flows/views.py

This is potentially very expensive if there are millions of sessions and I don't think users even have an expectation that ongoing sessions will be modified.

Remove updating session wait expirations when a flow is edited

---

temba/orgs/backend.py
temba/settings_common.py

oops turns out we've always looked up usernames case insensitively

Revert "Remove no longer needed custom auth backend"

---

temba/campaigns/models.py
temba/campaigns/tests/test_campaign.py
temba/campaigns/tests/test_event.py
templates/campaigns/campaign_read.html

* Whole row is clickable (norm in UI)
* Use button treatment for flow like trigger UI
* Includes contact fire count
before: 
after:

Improve campaign read page and include contact fire count wtih events

---

temba/campaigns/models.py
temba/campaigns/tests/test_event.py
temba/campaigns/views.py
templates/campaigns/campaign_read.html
templates/campaigns/campaignevent_read.html

* Show on event list when an event is being re-scheduled....
* Show on read page and also show number of scheduled contacts:
Current view for comparison:

Improve campaign event read page and prefetch fire counts

---

templates/no_nav.html

Fix signin button alignment

---

temba/contacts/models.py
temba/contacts/tests/test_contactcrudl.py

Currently we have an issue of displaying the contact fires for the same campaigns events multiple times since when a campaign event is update a new contact  fire is created with update the fire version
This PR makes sure we display only the contact fire with the highest fire version

Fix displaying updated campaign events fires multiple times

---

templates/account/email/login_code_message.html
templates/ai/llm_connect_form.html

Fix when compressing static files
```
Error parsing template account/email/login_code_message.html: accound/email/base_message.html
Error parsing template ai/llm_connect_form.html: smartmin_form.html
```

Fix typos in templates

---

temba/staff/views.py
templates/orgs/user_list.html

For a lot of users it's not easy to spot yeses amongst noes
becomes...

Tweak how we show user verified/2FA status on list pages

---

templates/orgs/user_list.html

Tweak styling of user list again

---

temba/api/internal/tests.py
temba/notifications/models.py
temba/notifications/tests/test_incident.py
temba/notifications/tests/test_notification.py
temba/notifications/tests/test_notificationcrudl.py
temba/notifications/urls.py
temba/notifications/views.py
templates/notifications/email/export_finished.html
templates/notifications/email/export_finished.txt
templates/notifications/email/incident_started.channel_disconnected.html
templates/notifications/email/incident_started.channel_disconnected.txt
templates/notifications/email/incident_started.channel_outdated_app.html
templates/notifications/email/incident_started.channel_outdated_app.txt
templates/notifications/email/incident_started.channel_templates_failed.html
templates/notifications/email/incident_started.channel_templates_failed.txt

* Add notification read view to clear the notification and redirect to the target URL
* Use read view instead of target url for email notifications
* Include read url in API results
* Leave existing notification clearing functionality on views as is for now
Next steps
1. Updating menu component to use redirect view (https://github.com/nyaruka/temba-components/pull/498)
2. Remove notification clearing functionality on views

Explicit clearing of notifications via redirect view

---

temba/users/adapter.py
templates/allauth/elements/provider.html
templates/allauth/layouts/base.html
templates/socialaccount/snippets/provider_list.html

Also populate email address earlier in the pipeline. This fixes issue where auto signup doesn't occur if OIDC provider supplies an alternate attribute for email.

Make SSO invite accept buttons more clear

---

temba/staff/views.py
temba/users/models.py
temba/users/tests/test_user.py

Issue:
A user tries to login and then a confirmation email is send to them and that create the emailaddress object with primary as False, that break the staff trying to verify the user
https://textit.sentry.io/issues/6747765741/
Solution is to check the email address by email and not primary field and also when a staff update the email, the email should again be verified

Adjust user set verified

---

temba/contacts/models.py
temba/contacts/tests/test_contact.py
temba/mailroom/client/client.py
temba/mailroom/client/tests.py
temba/tests/mailroom.py

Which wasn't being used anyway

Tweak mailroom.contact_interrupt to not expect a return value.
